### ISSUE TITLE
Unexpected character encountered异常

### ISSUE THREAD

**Issue by ZS124821** [nilaoda/BBDown#102]
尊敬的开发者，您好：
        今天下载无水印《万国志》（BBDown.exe ep287059 -p all -tv），从第三集开始报异常：Unexpected character encountered while parsing value: h. Path '', line 0, position 0.麻烦开发者查看具体原因，希望得到您的回信。

**Comment by nilaoda** [comment]
测试后，这是一个BUG，将会在新版本中修复。

**Comment by xukongop** [comment]
我今天也遇到了这个报错
