### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by DuoFuShun** [nilaoda/BBDown#104]
由于目标计算机积极拒绝，无法连接。
现在提示这种信息，每个视频都下载不了了。。

**Comment by nilaoda** [comment]
是不是开了系统代理呢？

**Comment by DuoFuShun** [comment]
> 是不是开了系统代理呢？

是的 是的，解决了，非常感谢，开启了代理后，就可以下载了。。。 可能是我的代理环境比较乱导致的，非常抱歉
