### ISSUE TITLE
能否在使用`--audio-only`时就自动将下载的mp4文件变成音频格式文件

### ISSUE THREAD

**Issue by cyddgh** [nilaoda/BBDown#105]
感谢BBDown的开发者。请问BBDown可否直接将下载的mp4文件变成音频格式？因为我将mp4文件放入小米手机后，系统识别为视频文件而不是音乐文件。

目前我的工作流是：
先从B站下载仅包含声音的文件，使用如下语句
`BBDown --audio-only  "https://www.bilibili.com/video/BV1b64y1d7pw"`
然后将下载后的文件更名为video.mp4，使用ffmpeg进行格式转换，使用如下语句
`ffmpeg -i video.mp4 -vn -y -acodec copy video.aac`

因为BBDown在win上同时提供了ffmpeg文件，能否在使用`--audio-only`时就自动将下载的mp4文件变成音频格式文件？

**Comment by WindProtect** [comment]
附议，有些视频只想下音频来听，如果带参数 `--skip-mux` 虽然可以只拿到音频但是名字要自己手动改标题。

**Comment by chaozh** [comment]
支持

**Comment by nilaoda** [comment]
下个版本会把仅音频封装为m4a，相比aac这类裸流，m4a会更好一些
