### ISSUE TITLE
下载带字幕的视频时出错

### ISSUE THREAD

**Issue by HuangRuixiao-eng** [nilaoda/BBDown#106]
cmd中使用 `bbdown --audio-only "https://www.bilibili.com/video/BV1tQ4y1R7MR?from=search&seid=1823651800388864056"`下载时，在显示

> 下载字幕 ja => 日本語...

后出现

> Error reading JObject from JsonReader. Path '', line 0, position 0.

的错误，下载无法完成。
已使用大会员账号登录。

**Comment by HuangRuixiao-eng** [comment]
以上问题在win10 powershell中出现，换用cmd后无此问题。

**Comment by nilaoda** [comment]
[1.4.0](https://github.com/nilaoda/BBDown/releases/tag/1.4.0) 中已经修复
