### ISSUE TITLE
反馈一下BBDown的某些功能

### ISSUE THREAD

**Issue by Summeriee** [nilaoda/BBDown#109]
关于封装视频时候的功能，请问大佬在下次更新那时候方便加个开关用以关掉封装封面海报以及作品简介的功能吗？

最这两天和圈内的一些同好在聊这个软件的时候，被他们吐槽了一下，然后我突然就想来给你反馈一下这个功能

**Comment by tonyhsie** [comment]
我也建議可以不要把圖片封裝進視頻檔案裡，或是加個選項來取消它
因為這個動作反而會讓檔案總管的預覽功能失效

所有影片的預覽，通通都只顯示封面圖片，而不是影片內容了

**Comment by nilaoda** [comment]
下个版本会增加相关选项

**Comment by Summeriee** [comment]
> 我也建議可以不要把圖片封裝進視頻檔案裡，或是加個選項來取消它
> 因為這個動作反而會讓檔案總管的預覽功能失效
> 
> 所有影片的預覽，通通都只顯示封面圖片，而不是影片內容了

我目前都是手动封装的，使用 --skip-mux 来停止BBDown中的混流功能，然后自己手动封装音/视频
