### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by Ryanrrt** [nilaoda/BBDown#115]
![Snipaste_2021-06-16_13-59-57](https://user-images.githubusercontent.com/77424745/122165719-30e55f00-ceab-11eb-983c-374710c081f7.png)

麻烦看下是我设置的问题吗？
系统：
版本	Windows 10 家庭中文版
版本号	21H1
安装日期	‎2020/‎9/‎2
操作系统内部版本	19043.1052
体验	Windows Feature Experience Pack 120.2212.2020.0

**Comment by nilaoda** [comment]
解决了吗
