### ISSUE TITLE
合并失败

### ISSUE THREAD

**Issue by LittleDeng1** [nilaoda/BBDown#118]
疑似分p标题带引号导致
![image](https://user-images.githubusercontent.com/62782358/123905493-09ab8900-d9a5-11eb-8afa-c15d7b449ca5.png)

**Comment by nilaoda** [comment]
希望提供BV号

**Comment by LittleDeng1** [comment]
BV1UM4y1u7Zq
P8
@nilaoda

**Comment by nilaoda** [comment]
已修复.等待新版发布
