### ISSUE TITLE
解析番剧ep号的链接下方BV号出错

### ISSUE THREAD

**Issue by Summeriee** [nilaoda/BBDown#120]
B站的番剧一般都显示ep号，用ep号解析不出那一集，而是解析所有分P，随便找个番剧试了一下：
https://www.bilibili.com/bangumi/play/ep410595
这个是番外特别篇某集的ep号，使用该ep号解析时，不会出现该集的链接，而是会解析出所有正片分P的链接，我个人一般使用 -tv -info，单独 -info，也是会出现这种情况
![image](https://user-images.githubusercontent.com/84846129/124875777-de0b4d00-dffb-11eb-9e5f-19b06d8803ef.png)

其他圈内用爱发电的大佬开发出的解析软件也会出现这种情况，解析不出该集，而是会解析出所有正片分P，我觉得是该ep号的问题

但是另一个软件(无法使用TV端解析无法下水印版)在使用BV号解析，就正常了

尝试了BBDown单独使用 -info(不使用TV端解析)，就解析出链接了
![image](https://user-images.githubusercontent.com/84846129/124876559-b8cb0e80-dffc-11eb-8334-dc5b8f08623a.png)

但是BBDown使用BV号+TV端接口解析时就会出错
![image](https://user-images.githubusercontent.com/84846129/124876010-20348e80-dffc-11eb-8ec8-621eb6e65d51.png)

希望大佬修复完善BV号使用TV端接口的解析

**Comment by nilaoda** [comment]
已修复，请等待下个版本发布.
