### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by BoxuanZng** [nilaoda/BBDown#121]
[Sigure/Yutto](https://github.com/SigureMo/yutto/)
作者，建议你学习一下这个储蓄库，增加一个--requirement;-r参数，可以从文件里自动读取BV,AV,SS,EP号下载视频、番剧等
这样就可以解放双手（啊不是）只用一个cmd/win terminal就可以持续下载视频、番剧了🙏🙏🙏

**Comment by nilaoda** [comment]
建议编写批处理实现此功能
