### ISSUE TITLE
v1.4.0 -app BUG

### ISSUE THREAD

**Issue by Summeriee** [nilaoda/BBDown#123]
在login和logintv都成功登陆的情况下，-app 解析会员视频会出错(-tv 和 默认的Web端解析正常)
![image](https://user-images.githubusercontent.com/84846129/125117204-76025700-e120-11eb-9e3d-f3760f412b4b.png)
![image](https://user-images.githubusercontent.com/84846129/125117640-1a849900-e121-11eb-99e6-5b08b46a0493.png)
![image](https://user-images.githubusercontent.com/84846129/125117656-1f494d00-e121-11eb-902d-af535968db73.png)

但是能够成功解析非会员视频
![image](https://user-images.githubusercontent.com/84846129/125117798-4f90eb80-e121-11eb-88c8-39957b85bb01.png)
![image](https://user-images.githubusercontent.com/84846129/125117876-6df6e700-e121-11eb-8523-e3f15a804084.png)

**Comment by nilaoda** [comment]
你需要填写安卓app端的access_key才可以解析会员视频

**Comment by BoxuanZng** [comment]
要怎么抓包

**Comment by nilaoda** [comment]
> 要怎么抓包

用HttpCanary之类的东西吧

**Comment by BoxuanZng** [comment]
为什么Fiddler找不到

**Comment by daofeng2015** [comment]
> 你需要填写安卓app端的access_key才可以解析会员视频

阿b的access_key是全平台通用的,只是安卓app端和tv端的api接口不一样而已

**Comment by nilaoda** [comment]
> > 你需要填写安卓app端的access_key才可以解析会员视频
> 
> 阿b的access_key是全平台通用的,只是安卓app端和tv端的api接口不一样而已

如果是这样的话可以复制一份`BBDownTV.data`到`BBDownApp.data`

**Comment by Summeriee** [comment]
> 你需要填写安卓app端的access_key才可以解析会员视频
好了，之前以为登陆上去就行了，没留意要手动填写 access
![image](https://user-images.githubusercontent.com/84846129/125155649-daaac980-e193-11eb-9034-044bb7243930.png)


并且按照这位朋友说的，我刚才填的是TV端的 access_token，能解析出APP端的链接，这样就不用去抓 access 了

**Comment by daofeng2015** [comment]
> > > 你需要填写安卓app端的access_key才可以解析会员视频
> > 
> > 
> > 阿b的access_key是全平台通用的,只是安卓app端和tv端的api接口不一样而已
> 
> 如果是这样的话可以复制一份`BBDownTV.data`到`BBDownApp.data`

而且现在安卓和ios端都是grpc了..以前的某个版本的apk泄露了proto文件.自己找下就只能怎么搞了

**Comment by nilaoda** [comment]
> > > > 你需要填写安卓app端的access_key才可以解析会员视频
> > > 
> > > 
> > > 阿b的access_key是全平台通用的,只是安卓app端和tv端的api接口不一样而已
> > 
> > 
> > 如果是这样的话可以复制一份`BBDownTV.data`到`BBDownApp.data`
> 
> 而且现在安卓和ios端都是grpc了..以前的某个版本的apk泄露了proto文件.自己找下就只能怎么搞了

嗯 已经是按照gRPC实现了
