### ISSUE TITLE
关于tv登录问题

### ISSUE THREAD

**Issue by root0day** [nilaoda/BBDown#125]
使用BBDown logintv也是生成二维码 
而云视听小电视客户端没有扫码功能
如何登录呢
使用哔哩哔哩客户端登录
然后扫码嘛

**Comment by Aman1109** [comment]
你登陆TV端的时候不就是使用手机APP扫码的吗，logintv自然也是这样操作。

**Comment by Aman1109** [comment]
> 使用BBDown logintv也是生成二维码
> 而云视听小电视客户端没有扫码功能
> 如何登录呢
> 使用哔哩哔哩客户端登录
> 然后扫码嘛
你登陆TV端的时候不就是使用手机APP扫码的吗，logintv自然也是这样操作。

**Comment by Aman1109** [comment]
> 使用BBDown logintv也是生成二维码
> 而云视听小电视客户端没有扫码功能
> 如何登录呢
> 使用哔哩哔哩客户端登录
> 然后扫码嘛

你登陆TV端的时候不就是使用手机APP扫码的吗，logintv自然也是这样操作。

**Comment by nilaoda** [comment]
使用手机APP扫码
