### ISSUE TITLE
关于 macOS 上 libgdiplus 的安装

### ISSUE THREAD

**Issue by hronro** [nilaoda/BBDown#134]
我因为一些原因无法通过 homebrew 安装 libgdiplus，我直接安装了 mono，已经可以在 `/Library/Frameworks/Mono.framework/Libraries` 下找到 libgdiplus 的动态库了，但运行 `BBDown login` 还是报错。

请问这可能是什么原因导致的？

![CleanShot 2021-07-19 at 12 30 31](https://user-images.githubusercontent.com/15059605/126103274-4750f0cd-c0b0-44c5-8c9b-dc40a6b9f074.png)

**Comment by nilaoda** [comment]
我没有Mac机器，没办法测试

之后会尝试使用其他第三方库生成二维码来避免类似问题

你可以先抓包cookie然后使用`-c "cookie"`来加载

**Comment by hronro** [comment]
@nilaoda cookie 的话应该没法用 App 的 API 吧

**Comment by thomasbergersen** [comment]
这是库不全 使用HomeBrew安装 会把依赖项全部安装
