### ISSUE TITLE
Error reading JObject from JsonReader. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by qingyi11** [nilaoda/BBDown#138]
how to fix it?

**Comment by nilaoda** [comment]
贴一下命令

**Comment by lvzhenbo** [comment]
![image](https://user-images.githubusercontent.com/32427677/126997359-f0158597-7e76-42c0-a758-afdcb4896b74.png)

**Comment by nilaoda** [comment]
@lvzhenbo  我这边一切正常呢。。你可以加入`--debug`看看具体情况

![image](https://user-images.githubusercontent.com/20772925/127009190-7c48d8cc-1b63-46a3-a995-6d5fac50f21d.png)

**Comment by lvzhenbo** [comment]
哦，看了眼是cookie失效了，重新登录就好了。建议添加一个检测cookie失效并且重新登录的逻辑。

**Comment by qingyi11** [comment]
> 
> 
> 贴一下命令

是cookie的问题，正如楼上所说，可以添加设置5天检测一下cookie是否能用的功能
