### ISSUE TITLE
啥时候打包一个Mac版啊

### ISSUE THREAD

**Issue by rehack** [nilaoda/BBDown#14]
如题

**Comment by wenxin9999** [comment]
> 感谢，已测试成功 ![未标题-1](https://user-images.githubusercontent.com/9047357/90903156-1e6fd580-e400-11ea-8c68-00c983516e81.png)
> 
> ➜  Downloads ffmpeg -version
> ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
> built with Apple LLVM version 10.0.0 (clang-1000.10.44.4)
> configuration: --prefix=/usr/local/devenv/ffmpeg
> libavutil      56. 51.100 / 56. 51.100
> libavcodec     58. 91.100 / 58. 91.100
> libavformat    58. 45.100 / 58. 45.100
> libavdevice    58. 10.100 / 58. 10.100
> libavfilter     7. 85.100 /  7. 85.100
> libswscale      5.  7.100 /  5.  7.100
> libswresample   3.  7.100 /  3.  7.100
> ➜  Downloads ./BBDown BV13Z4y1u7nb -tv
> BBDown version 1.2.2, Bilibili Downloader.
> 请注意：任何BUG请前往以下网址反馈：
> https://github.com/nilaoda/BBDown/issues
> 
> [2020-08-21 22:40:27.780] - 获取aid...
> [2020-08-21 22:40:30.647] - 获取aid结束: 371282851
> [2020-08-21 22:40:31.766] - 获取视频信息...
> [2020-08-21 22:40:31.766] - 视频标题: 接着奏乐接着舞，没想到曹操能来啊！
> [2020-08-21 22:40:31.766] - 发布时间: 2020/7/5 下午10:58:28
> [2020-08-21 22:40:31.790] - 下载封面...
> [2020-08-21 22:40:33.096] - P1: [209264030] [接着奏乐接着舞，没想到曹操能来啊！] [02m09s]
> [2020-08-21 22:40:33.096] - 共计 1 个分P, 已选择：ALL
> [2020-08-21 22:40:33.096] - 开始解析P1...
> [2020-08-21 22:40:35.856] - 共计1条流(flv480, 共有1个分段).
>                             0. [清晰 480P] [AVC] [~771 kbps] [12.12 MB]
> [2020-08-21 22:40:35.857] - 开始下载P1视频, 片段(1/1)...
> [2020-08-21 22:41:53.525] - 下载P1完毕                                       
> [2020-08-21 22:41:53.525] - 开始合并分段...
> [2020-08-21 22:41:53.537] - 开始混流视频...
> [2020-08-21 22:41:53.635] - 清理临时文件...
> [2020-08-21 22:41:53.638] - 任务完成
> ➜  Downloads ./BBDown --version       
> 1.2.2
> ➜  Downloads

能出个 macos 的教程么，新手百度搞不定
现在提示这个 
Required argument missing for command: 'BBDown'.

BBDown version 1.5.4, Bilibili Downloader.
欢迎到讨论区交流：
https://github.com/nilaoda/BBDown/discussions

Required argument missing for command: 'BBDown'.
