### ISSUE TITLE
关于下载失败: An exception occurred during a WebClient request

### ISSUE THREAD

**Issue by KAKETAKAGE** [nilaoda/BBDown#140]
番剧下载经常性(可能有2/3)失败, 并且立即重新下载也必定失败. 没试过普通视频
移动网络 -mt无效.

相同网络下, 使用 `唧唧Down` 下载普通视频不会出现下载失败问题.
是因为 `唧唧Down` 有分片下载失败重下机制吗? 但我没看到提示分片重新下载.

因此我觉得可能不是 网络问题(不考虑运营商问题的情况下), 或者是B站对番剧下载有特殊限制?

**Comment by nilaoda** [comment]
建议使用aria2

**Comment by KAKETAKAGE** [comment]
已解决, 谢谢.
为什么不默认使用aria2进行下载?
