### ISSUE TITLE
启动的时候可以顺便启动Aria2，用RPC管理，这样就可以实现断点续传和多线程多任务下载了

### ISSUE THREAD

**Issue by wwsq1149** [nilaoda/BBDown#142]
参考downkyi  https://github.com/leiurayer/downkyi
原来的下载方式是给Aria2附加命令行，可以用命令添加下载任务、查看下载状态。开放RPC端口、可以用Aria2NG之类的网页端管理下载任务。不然自带的下载经常 An exception occurred during a WebClient request，用Aria2下载偶尔也会出错，对于动辄多P上G的大视频手动重新下载并且重新等待太耗耐心了

**Comment by xhlove** [comment]
aria2有aria2的问题，代理、dns解析，rpc响应这些都会有些莫名其妙的问题。

对于视频下载来说，多任务更不适合rpc管理了，因为它代理切换其他任务也跟着切换了。

而且加入aria2后跨平台的兼容性又是一个大问题，有些bug在win上没有，在linux上就有可能出现。

所以最合理的是每一个下载任务的这些配置都是独立的。

**Comment by wwsq1149** [comment]
@xhlove 那断点续传呢，或者错误时多尝试几次，不然从头开始的时候心态都炸了

**Comment by xhlove** [comment]
断点续传个人认为适合比较大的单文件，但是这个时候建议用IDM之类的。

**Comment by wwsq1149** [comment]
好吧~_~

**Comment by wwsq1149** [comment]
@xhlove 
IDM一个一个下载有些麻烦，我再研究下看是不是我网络的问题，谢谢了

**Comment by hez2010** [comment]
断点续传已实现，请等待后续更新：https://github.com/nilaoda/BBDown/pull/145
