### ISSUE TITLE
BBDown 下载出错，不支持的 没有语言 en-GB

### ISSUE THREAD

**Issue by ID-AMS** [nilaoda/BBDown#143]
![KRE81XUD)_(4NZV23`A44A5](https://user-images.githubusercontent.com/79731603/127768763-1de828b2-129c-4269-828c-f472b504a4d4.png)
报错网站：https://www.bilibili.com/video/BV1yf4y1R7mU

**Comment by nilaoda** [comment]
相关问题：https://github.com/nilaoda/BBDown/discussions/58#discussioncomment-1263242
