### ISSUE TITLE
合并失败: Protocol not found

### ISSUE THREAD

**Issue by o0o0o0o0o0o0o** [nilaoda/BBDown#146]
下载 BV1NA411E7Yr 时：

<img width="717" alt="截屏2021-08-07 下午7 43 04" src="https://user-images.githubusercontent.com/22792458/128619066-12490923-6302-4acf-8691-f6709a3f4100.png">

**Comment by nilaoda** [comment]
你的ffmpeg版本可能有问题，我这里是正常合并的

![image](https://user-images.githubusercontent.com/20772925/133893494-e091cb3c-5758-45a0-ad05-850c2055f22c.png)

**Comment by kkkingim** [comment]
带:的文件名会解析成协议，我这边这个ffmpeg 也会有这个问题  
    ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers 
    built with Apple clang version 12.0.0 (clang-1200.0.32.29)

https://unix.stackexchange.com/questions/412519/ffmpeg-protocol-not-found-for-normal-file-name
