### ISSUE TITLE
希望可以引用BBDown作为Bili的下载工具

### ISSUE THREAD

**Issue by Richasy** [nilaoda/BBDown#159]
## 提议

@nilaoda 你好，

我是 [哔哩](https://github.com/Richasy/Bili.Uwp) 的开发者，BBDown的使用效果很棒，我希望可以指定其为下载工具。

具体的方式为：

在应用的播放界面提供一个可视化的配置面板，根据当前正在播放的视频生成BBDown的命令，引导用户通过BBDown实现下载视频的目的。

## 截图

*仍在开发中*

![image](https://user-images.githubusercontent.com/27713596/134837969-50b2069f-779f-402a-8224-400114bb9ff3.png)

![image](https://user-images.githubusercontent.com/27713596/134838758-d8588780-0f9d-4de8-a676-9f825795c456.png)

**Comment by nilaoda** [comment]
哔哩是十分优秀的客户端，很高兴看到BBDown能够出现在其中🤝

**Comment by Richasy** [comment]
非常感谢你的帮助，那我先close这个issue了，期待BBDown的后续更新，我会保持跟进。
