### ISSUE TITLE
出现No such file or directory

### ISSUE THREAD

**Issue by nifengfei** [nilaoda/BBDown#16]
/Users/azrael/Downloads/bb/BBDown https://www.bilibili.com/bangumi/play/ep234489
BBDown version 1.2.2, Bilibili Downloader.
请注意：任何BUG请前往以下网址反馈：
https://github.com/nilaoda/BBDown/issues

[2020-08-25 18:37:40.014] - 获取aid...
[2020-08-25 18:37:40.685] - 获取aid结束: 27045209
[2020-08-25 18:37:40.825] - 获取视频信息...
[2020-08-25 18:37:40.825] - 视频标题: 【合集】玉子市场
[2020-08-25 18:37:40.826] - 发布时间: 2018/7/17 下午5:07:39
[2020-08-25 18:37:40.857] - 下载封面...
[2020-08-25 18:37:40.952] - P1: [46590021] [01] [24m01s]
[2020-08-25 18:37:40.953] - P2: [46590071] [02] [24m01s]
[2020-08-25 18:37:40.953] - P3: [46590115] [03] [24m01s]
[2020-08-25 18:37:40.953] - P4: [46590159] [04] [24m01s]
[2020-08-25 18:37:40.953] - P5: [46590201] [05] [24m01s]
[2020-08-25 18:37:40.953] - P...
[2020-08-25 18:37:40.953] - 分P太多, 已经省略部分...
[2020-08-25 18:37:40.953] - 共计 12 个分P, 已选择：ALL
[2020-08-25 18:37:40.953] - 开始解析P1...
[2020-08-25 18:37:41.132] - 共计8条视频流.
                            0. [高清 1080P] [1920x1080] [AVC] [16000/672] [1754 kbps] [~308.53 MB]
                            1. [高清 1080P] [1920x1080] [HEVC] [16000/672] [1404 kbps] [~246.97 MB]
                            2. [高清 720P] [1280x720] [AVC] [16000/672] [1316 kbps] [~231.49 MB]
                            3. [高清 720P] [1280x720] [HEVC] [16000/672] [1083 kbps] [~190.50 MB]
                            4. [清晰 480P] [852x480] [AVC] [16000/672] [790 kbps] [~138.96 MB]
                            5. [清晰 480P] [852x480] [HEVC] [16000/672] [627 kbps] [~110.29 MB]
                            6. [流畅 360P] [640x360] [AVC] [16000/672] [352 kbps] [~61.92 MB]
                            7. [流畅 360P] [640x360] [HEVC] [16000/672] [258 kbps] [~45.38 MB]
[2020-08-25 18:37:41.133] - 共计3条音频流.
                            0. [M4A] [193 kbps] [~33.95 MB]
                            1. [M4A] [132 kbps] [~23.22 MB]
                            2. [M4A] [67 kbps] [~11.79 MB]
[2020-08-25 18:37:41.134] - 已选择的流:
                            [视频] [高清 1080P] [1920x1080] [AVC] [16000/672] [1754 kbps] [~308.53 MB]
                            [音频] [M4A] [193 kbps] [~33.95 MB]
[2020-08-25 18:37:41.134] - 开始下载P1视频...
[2020-08-25 18:38:20.415] - 开始下载P1音频...                                
[2020-08-25 18:38:24.447] - 下载P1完毕                                       
[2020-08-25 18:38:24.447] - 开始合并音视频...
No such file or directory

**Comment by nifengfei** [comment]
这是说明问题

**Comment by nifengfei** [comment]
osx 版

**Comment by user1121114685** [comment]
> /Users/azrael/Downloads/bb/BBDown https://www.bilibili.com/bangumi/play/ep234489
> BBDown version 1.2.2, Bilibili Downloader.
> 请注意：任何BUG请前往以下网址反馈：
> https://github.com/nilaoda/BBDown/issues
> 
> [2020-08-25 18:37:40.014] - 获取aid...
> [2020-08-25 18:37:40.685] - 获取aid结束: 27045209
> [2020-08-25 18:37:40.825] - 获取视频信息...
> [2020-08-25 18:37:40.825] - 视频标题: 【合集】玉子市场
> [2020-08-25 18:37:40.826] - 发布时间: 2018/7/17 下午5:07:39
> [2020-08-25 18:37:40.857] - 下载封面...
> [2020-08-25 18:37:40.952] - P1: [46590021] [01] [24m01s]
> [2020-08-25 18:37:40.953] - P2: [46590071] [02] [24m01s]
> [2020-08-25 18:37:40.953] - P3: [46590115] [03] [24m01s]
> [2020-08-25 18:37:40.953] - P4: [46590159] [04] [24m01s]
> [2020-08-25 18:37:40.953] - P5: [46590201] [05] [24m01s]
> [2020-08-25 18:37:40.953] - P...
> [2020-08-25 18:37:40.953] - 分P太多, 已经省略部分...
> [2020-08-25 18:37:40.953] - 共计 12 个分P, 已选择：ALL
> [2020-08-25 18:37:40.953] - 开始解析P1...
> [2020-08-25 18:37:41.132] - 共计8条视频流.
> 0. [高清 1080P] [1920x1080] [AVC] [16000/672] [1754 kbps] [~308.53 MB]
> 1. [高清 1080P] [1920x1080] [HEVC] [16000/672] [1404 kbps] [~246.97 MB]
> 2. [高清 720P] [1280x720] [AVC] [16000/672] [1316 kbps] [~231.49 MB]
> 3. [高清 720P] [1280x720] [HEVC] [16000/672] [1083 kbps] [~190.50 MB]
> 4. [清晰 480P] [852x480] [AVC] [16000/672] [790 kbps] [~138.96 MB]
> 5. [清晰 480P] [852x480] [HEVC] [16000/672] [627 kbps] [~110.29 MB]
> 6. [流畅 360P] [640x360] [AVC] [16000/672] [352 kbps] [~61.92 MB]
> 7. [流畅 360P] [640x360] [HEVC] [16000/672] [258 kbps] [~45.38 MB]
> [2020-08-25 18:37:41.133] - 共计3条音频流.
> 0. [M4A] [193 kbps] [~33.95 MB]
> 1. [M4A] [132 kbps] [~23.22 MB]
> 2. [M4A] [67 kbps] [~11.79 MB]
> [2020-08-25 18:37:41.134] - 已选择的流:
> [视频] [高清 1080P] [1920x1080] [AVC] [16000/672] [1754 kbps] [~308.53 MB]
> [音频] [M4A] [193 kbps] [~33.95 MB]
> [2020-08-25 18:37:41.134] - 开始下载P1视频...
> [2020-08-25 18:38:20.415] - 开始下载P1音频...
> [2020-08-25 18:38:24.447] - 下载P1完毕
> [2020-08-25 18:38:24.447] - 开始合并音视频...
> No such file or directory

# 注意：Linux和Mac OS需要用户自行安装ffmpeg
