### ISSUE TITLE
建议增加更多的文件重命名选项，例如加入日期前缀等

### ISSUE THREAD

**Issue by ghost** [nilaoda/BBDown#180]
建议增加类似youtube-dl的文件重命名选项，例如`%(upload_date)`、`%(author)`或者`yyyy-MM-dd`之类的选项。

**Comment by ch3nBo** [comment]
需求，有些up主的多个视频命名重复的话app会自动跳过不会下载。

**Comment by nilaoda** [comment]
> 

这个下个版本优化一下

**Comment by ch3nBo** [comment]
> 需求，有些up主的多个视频命名重复的话app会自动跳过不会下载。

修改了下outPath，给每个视频加了av号，暂时解决了视频重名的问题，等作者下一个版本。
