### ISSUE TITLE
[咨询]

### ISSUE THREAD

**Issue by wqcblog** [nilaoda/BBDown#183]
请问哪位朋友能给出本地16800 aria2c端口(motrix设置的端口是16800)的调用示范，
我这样调用    BBDown -tv -token 匿 --aria2c-proxy 16800 -mt -p 1 "BV1nq4y157SS"
但是这样并没有显示aria2c的下载进度，向大家寻求帮助，谢谢！

**Comment by nilaoda** [comment]
示例代码
```
代理：
BBDown --use-aria2c --aria2c-proxy http://127.0.0.1:8080 BV1nq4y157SS
无代理：
BBDown --use-aria2c BV1nq4y157SS
```

需要`aria2c`可执行文件
