### ISSUE TITLE
[合并失败]

### ISSUE THREAD

**Issue by wqcblog** [nilaoda/BBDown#187]
我使用aria2去下载 发现最后一步显示合并失败，请问这是什么错误呢
![QQ截图20211020124528](https://user-images.githubusercontent.com/82157125/138029869-1434e6a4-cbfc-492b-8658-5775ea664057.png)
![QQ截图20211020124539](https://user-images.githubusercontent.com/82157125/138029881-c6bf95f8-3349-48b2-b059-1fec03490681.png)

**Comment by nilaoda** [comment]
这是一个BUG。在使用`--use-aria2c`时请不要使用`-mt`，两者存在冲突。下个版本优化一下。

**Comment by ayanamist** [comment]
`BBDown --debug -c "$(cat ~/.BBDown_SESSDATA)" -mt --skip-subtitle --skip-cover -hevc BV1tP4y1L7Qs` 

截图如下

![image](https://user-images.githubusercontent.com/406779/139517032-4e08ce1d-6845-4b27-8a49-73b333342f7e.png)

我本来感觉和这个description有换行有关系，因为我把ffmpeg命令弄出来，去掉description来执行，是好的；但是，我把`-mt`去掉后发现，居然也是好的，不懂了

**Comment by nilaoda** [comment]
> `BBDown --debug -c "$(cat ~/.BBDown_SESSDATA)" -mt --skip-subtitle --skip-cover -hevc BV1tP4y1L7Qs`
> 
> 截图如下
> 
> ![image](https://user-images.githubusercontent.com/406779/139517032-4e08ce1d-6845-4b27-8a49-73b333342f7e.png)
> 
> 我感觉和这个description有换行有关系，因为我把ffmpeg命令弄出来，去掉description来执行，是好的

在Windows下是可以正常合并的，尚未在Linux下测试，你的ffmpeg版本是？如果是最新版的话可能要针对Linux做点处理了

**Comment by ayanamist** [comment]
ffmpeg version 4.2.4-1ubuntu0.1
我觉得应该不是ffmpeg的问题。
能否在--debug的状态，ffmpeg不要loglevel为warn，让错误信息出来呀。
另外不知道是怎么执行命令，是否会经过shell，会的话，这个多行文本在linux的各个shell里可能会被当作多行命令被执行的。

**Comment by tonyhsie** [comment]
我也遇到一樣的問題，下載時根本沒有真的下載資料，最後自然合併失敗
v.1.4.5 跟 v.1.4.6 都有一樣的問題，而原本的 v1.4.0 並沒有這個問題

![圖片 2021-11-09 00-23-34](https://user-images.githubusercontent.com/52758827/140779616-46cb3e50-dca2-4503-8399-06231fce5ed1.png)


指令是 "BBDown.exe -mt -p 1 ss39539 --debug"
把 -mt 拿掉就能正常下載

請問在 v1.4.5 版之後，"-mt" 是發生了什麼事呢，謝謝
