### ISSUE TITLE
非自制视频无法下载

### ISSUE THREAD

**Issue by asuka-in-2020** [nilaoda/BBDown#190]
The given key was not present in the dictionary.

**Comment by asuka-in-2020** [comment]
> ![image](https://user-images.githubusercontent.com/20772925/138600514-4b9c3a53-9a33-4f3d-b370-2dbf75bb08e6.png)
> 
> ![image](https://user-images.githubusercontent.com/20772925/138600561-f0baec1f-35ea-480f-bc84-3c5d67582e5c.png)
> 
> 我这边 确实没问题

好吧，1.4.6版本解决了

**Comment by KeterCo** [comment]
我这同样原因，是因为视频被删除了，呜呜呜。
