### ISSUE TITLE
[建议]增加下载位置设置

### ISSUE THREAD

**Issue by lmx15002643515** [nilaoda/BBDown#193]
哔哩生成的命令没有指定路径，使用path环境变量，会下载到System32里，希望增加下载位置设置

**Comment by Orange-es** [comment]
大佬，使用--wokr-dir<地址>   一直拒绝访问 怎么调试呀？  win10

**Comment by nilaoda** [comment]
> 大佬，使用--wokr-dir<地址> 一直拒绝访问 怎么调试呀？ win10

看看截图

**Comment by Orange-es** [comment]
![1](https://user-images.githubusercontent.com/54025960/150720846-6f4e2211-8a61-4f7c-8676-5633c9f1c828.png)
这个样子的

**Comment by nilaoda** [comment]
@Orange-es  `--work-dir "D:\A"`

**Comment by Orange-es** [comment]
👍  好啦 大佬

**Comment by SoraAzusaga** [comment]
@nilaoda 大佬,默认路径下载路径在哪?

**Comment by nilaoda** [comment]
> @nilaoda 大佬,默认路径下载路径在哪?

默认在你启动软件的路径

**Comment by SoraAzusaga** [comment]
> 

昨天刚用，已经解决了，谢谢。
