### ISSUE TITLE
解析403

### ISSUE THREAD

**Issue by daofeng2015** [nilaoda/BBDown#2]
![image](https://user-images.githubusercontent.com/14891398/88507871-fadb8a00-d00f-11ea-9b6b-866e68e1a6b0.png)
确认是大会员,解析403,tv模式直接显示解析失败

**Comment by nilaoda** [comment]
目前TV模式并不支持下载番剧。

**Comment by nilaoda** [comment]
目前TV模式不支持番剧解析。
403问题晚上我看一下，请提供详细番剧链接。

**Comment by daofeng2015** [comment]
> 目前TV模式不支持番剧解析。
> 403问题晚上我看一下，请提供详细番剧链接。

番剧就是凡人修仙传.上面有链接的

**Comment by nilaoda** [comment]
![image](https://user-images.githubusercontent.com/20772925/88538601-38590b00-d042-11ea-8b7b-e6a5c1ec590e.png)

测试无问题啊
