### ISSUE TITLE
为什么要把视频下载？

### ISSUE THREAD

**Issue by abxm2** [nilaoda/BBDown#20]
诚心提问，为什么要把视频下载？谈谈下载的需求

**Comment by nilaoda** [comment]
有些优秀的视频值得收藏

**Comment by luisliao** [comment]
認同~ 很多經典視頻值得收藏
有些視頻並非永久上線
有時要再次觀賞時
很多早已下線或者根本就無法在網路上找到清晰版本
目前3C產品都已經是4K~8K
視頻若無數位修復優化
而是早期DVD的480P畫質
在4K或8K電視上播放觀賞是模糊不清的
