### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by wei711071** [nilaoda/BBDown#202]
輸入指令：

.\BBDown.exe BV1Cx411N7yx -P 3-24

之後就不停的出現The given key was not present in the dictionary.

BBDown version 1.4.5, Bilibili Downloader.
?迎到???交流：
https://github.com/nilaoda/BBDown/discussions

[2021-11-04 15:34:45.674] - 加?本地cookie...
[2021-11-04 15:34:45.678] - ?取aid...
The given key was not present in the dictionary.

**Comment by nilaoda** [comment]
是否试过最新版本？以及更新Cookie呢

**Comment by wei711071** [comment]
成功 謝謝
