### ISSUE TITLE
Error: 无法合并视频及音频

### ISSUE THREAD

**Issue by PiPiTcc** [nilaoda/BBDown#203]
Error: An error occurred trying to start process 'ffmpeg' with working directory 'C:\Users\ChinaTcc\Desktop\BBDown'. 系统找不到指定的文
![Snipaste_2021-11-05_11-37-34](https://user-images.githubusercontent.com/47528293/140454345-4ccb7125-c387-4ef4-b9ee-0099337f07d8.png)
件。

**Comment by nilaoda** [comment]
将[ffmpeg.exe](https://github.com/nilaoda/BBDown/raw/master/Binary/ffmpeg.exe)放到对应目录

**Comment by PiPiTcc** [comment]
> 将[ffmpeg.exe](https://github.com/nilaoda/BBDown/raw/master/Binary/ffmpeg.exe)放到对应目录
![Snipaste_2021-11-08_16-19-49](https://user-images.githubusercontent.com/47528293/140707362-0aaf83bc-2d3a-49df-9cd7-0316c64e70d5.png)
