### ISSUE TITLE
[建议]自动选定编码格式

### ISSUE THREAD

**Issue by none2003** [nilaoda/BBDown#204]
版本1.4.6

现状：
在命令行里使用--only-hevc开关的时候，会只下载hevc编码的视频。遇到合集视频，有时候其中一些P是用AVC编码的，这样会下载失败，需要在第一次启用--only-hevc开关下载之后，再关闭这个开关重新下载一遍，BBDOWN会自动跳过本地已经存在的文件，只下载缺失的文件。

需求：
希望能增加一个--hevc-first的开关，这样优先选择hevc编码的视频下载，如果没有，则自动选择AVC的视频下载。

**Comment by dogdie233** [comment]
我觉得可以close了
