### ISSUE TITLE
能提供linux安裝教程么？

### ISSUE THREAD

**Issue by skylimiter** [nilaoda/BBDown#205]
编程小白
![](https://cdn.u1.huluxia.com/g4/M03/F0/A0/rBAAdmGHsy2AAF6vAAAZj9ADL4k000.png)
将linux版解压后 下个动作就不会....

希望能抽空提供教程
万分感激

**Comment by hez2010** [comment]
`chmod +x BBDown` 基于运行权限之后即可直接调用 `./BBDown` 运行

**Comment by skylimiter** [comment]
![](https://cdn.u1.huluxia.com/g4/M03/F1/45/rBAAdmGIAxCAUukmAAASBDj9cUs531.png)
无任何反应 也给予运行权限了

**Comment by nilaoda** [comment]
```sh
$ wget --no-check-certificate https://github.com/nilaoda/BBDown/releases/download/1.4.6/BBDown_v1.4.6_20211015_linux-x64.zip

$ unzip BBDown_v1.4.6_20211015_linux-x64.zip

$ chmod +x ./BBDown

$ ./BBDown -h
```
