### ISSUE TITLE
可自定义设置ffmpeg的路径

### ISSUE THREAD

**Issue by logerlink** [nilaoda/BBDown#206]
建议可自定义设置ffmpeg的路径
![image](https://user-images.githubusercontent.com/39935072/140676555-a3c06bb5-941d-4c12-9a6a-e7c321a45875.png)

**Comment by jimstar06** [comment]
默认会从系统PATH变量寻找ffmpeg，修改环境变量即可。

**Comment by nilaoda** [comment]
已支持
