### ISSUE TITLE
下载报错Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by a9236** [nilaoda/BBDown#209]
Object reference not set to an instance of an object.
命令---https://www.bilibili.com/bangumi/play/ep332611 -ia --debug

**Comment by nilaoda** [comment]
哪个版本？我这里没遇到问题

**Comment by a9236** [comment]
BBDown_v1.4.0_20210710_win-x64_with_ffmpeg_aria2c

**Comment by a9236** [comment]
> 哪个版本？我这里没遇到问题

BBDown_v1.4.0_20210710_win-x64_with_ffmpeg_aria2c

**Comment by nilaoda** [comment]
> > 哪个版本？我这里没遇到问题
> 
> BBDown_v1.4.0_20210710_win-x64_with_ffmpeg_aria2c

最新版是1.4.6了

**Comment by a9236** [comment]
换新版问题已解决 感谢
