### ISSUE TITLE
mac不支持4k

### ISSUE THREAD

**Issue by PassionPenguin** [nilaoda/BBDown#219]
似乎mac上不支持4k……
同一网络环境下windows环境能够显示4k选项，mac最高是1080p

FYI: charles 捕获下来的返回数据

<img width="333" alt="Screenshot 2021-11-28 at 1 09 35 AM" src="https://user-images.githubusercontent.com/41184947/143690525-58b80237-6a70-4cce-8354-62298f720166.png">

FYI: 对应cli界面

<img width="557" alt="Screenshot 2021-11-28 at 1 10 27 AM" src="https://user-images.githubusercontent.com/41184947/143690543-1611a77f-eb28-4af4-9ca8-c7583495c7c6.png">

**Comment by nilaoda** [comment]
看样子是没有登录会员

**Comment by PassionPenguin** [comment]
> 看样子是没有登录会员

again my fault
