### ISSUE TITLE
可以支持下M1 不😁

### ISSUE THREAD

**Issue by ge2009** [nilaoda/BBDown#221]

**Comment by nilaoda** [comment]
可以试试这个运行各项功能是否正常：

需要手动添加可执行权限

[BBDown_osx-arm64.zip](https://github.com/nilaoda/BBDown/files/7615423/BBDown_osx-arm64.zip)

**Comment by dennisheliwei** [comment]
> 

无法登陆

**Comment by dennisheliwei** [comment]
> @ge2009 可以试试这个运行各项功能是否正常：
> 
> 需要手动添加可执行权限
> 
> [BBDown_osx-arm64.zip](https://github.com/nilaoda/BBDown/files/7615423/BBDown_osx-arm64.zip)

无法登陆哦，
```
$ ./BBDown login
[2021-12-07 18:09:13.867] - 获取登录地址...
[2021-12-07 18:09:14.391] - 生成二维码...
[2021-12-07 18:09:14.456] - The type initializer for 'Gdip' threw an exception.
```

**Comment by sxyqwang** [comment]
> @ge2009 可以试试这个运行各项功能是否正常：
> 
> 需要手动添加可执行权限
> 
> [BBDown_osx-arm64.zip](https://github.com/nilaoda/BBDown/files/7615423/BBDown_osx-arm64.zip)

请问可以更新下m1的版本吗？

**Comment by nilaoda** [comment]
> > @ge2009 可以试试这个运行各项功能是否正常：
> > 需要手动添加可执行权限
> > [BBDown_osx-arm64.zip](https://github.com/nilaoda/BBDown/files/7615423/BBDown_osx-arm64.zip)
> 
> 请问可以更新下m1的版本吗？

是正常使用的吗 没啥问题的话我加到自动构建里去

**Comment by sxyqwang** [comment]
> > > @ge2009 可以试试这个运行各项功能是否正常：
> > > 需要手动添加可执行权限
> > > [BBDown_osx-arm64.zip](https://github.com/nilaoda/BBDown/files/7615423/BBDown_osx-arm64.zip)
> > 
> > 
> > 请问可以更新下m1的版本吗？
> 
> 是正常使用的吗 没啥问题的话我加到自动构建里去

视频下载是没问题的，但是使用BBDown login 无法生成二维码，报错：
The type initializer for 'Gdip' threw an exception.

**Comment by nilaoda** [comment]
> > > > @ge2009 可以试试这个运行各项功能是否正常：
> > > > 需要手动添加可执行权限
> > > > [BBDown_osx-arm64.zip](https://github.com/nilaoda/BBDown/files/7615423/BBDown_osx-arm64.zip)
> > > 
> > > 
> > > 请问可以更新下m1的版本吗？
> > 
> > 
> > 是正常使用的吗 没啥问题的话我加到自动构建里去
> 
> 视频下载是没问题的，但是使用BBDown login 无法生成二维码，报错： The type initializer for 'Gdip' threw an exception.

这个问题见 #255 

另外希望测试一下app接口是否正常

**Comment by sxyqwang** [comment]
> > > > > @ge2009 可以试试这个运行各项功能是否正常：
> > > > > 需要手动添加可执行权限
> > > > > [BBDown_osx-arm64.zip](https://github.com/nilaoda/BBDown/files/7615423/BBDown_osx-arm64.zip)
> > > > 
> > > > 
> > > > 请问可以更新下m1的版本吗？
> > > 
> > > 
> > > 是正常使用的吗 没啥问题的话我加到自动构建里去
> > 
> > 
> > 视频下载是没问题的，但是使用BBDown login 无法生成二维码，报错： The type initializer for 'Gdip' threw an exception.
> 
> 这个问题见 #255
> 
> 另外希望测试一下app接口是否正常

不太会JAVA呀，请问如何达到在命令行中打印QRCode的效果呢？

**Comment by sxyqwang** [comment]
> > > > > > @ge2009 可以试试这个运行各项功能是否正常：
> > > > > > 需要手动添加可执行权限
> > > > > > [BBDown_osx-arm64.zip](https://github.com/nilaoda/BBDown/files/7615423/BBDown_osx-arm64.zip)
> > > > > 
> > > > > 
> > > > > 请问可以更新下m1的版本吗？
> > > > 
> > > > 
> > > > 是正常使用的吗 没啥问题的话我加到自动构建里去
> > > 
> > > 
> > > 视频下载是没问题的，但是使用BBDown login 无法生成二维码，报错： The type initializer for 'Gdip' threw an exception.
> > 
> > 
> > 这个问题见 #255
> > 另外希望测试一下app接口是否正常
> 
> 不太会JAVA呀，请问如何达到在命令行中打印QRCode的效果呢？

使用了cookie登陆，下载大会员视频接口无误，只是混流强制使用mp4box还未解决
