### ISSUE TITLE
macOS上使用TV登录功能会报错

### ISSUE THREAD

**Issue by Fru-Jia** [nilaoda/BBDown#23]
命令：`/Users/userfolder/Downloads/BBDown logintv`

报错：`The type initializer for 'Gdip' threw an exception. `

<img width="682" alt="截屏2020-09-18 13 00 34" src="https://user-images.githubusercontent.com/69293864/93558055-2bf08f00-f9af-11ea-9c29-71a6eb488b27.png">

**Comment by nilaoda** [comment]
#19
