### ISSUE TITLE
[ERROR] WinTLS: Failed to decrypt a message! Error: 无法解密指定的数据。

### ISSUE THREAD

**Issue by microka** [nilaoda/BBDown#237]
Windows 11 21H2 (22000.376) + BBDown v1.4.6，B站账户为大会员（非tv会员）。

`BBDown -tv -p 127 --use-aria2c "https://www.bilibili.com/bangumi/play/ep260416"`
下载视频过程中会出现如下错误：
`12/30 20:07:03 [ERROR] WinTLS: Failed to decrypt a message! Error: 无法解密指定的数据。
(80090330)`
但生成的文件可正常播放。

而下载 -p 126 则不会出现该错误提示。请问是什么原因呢？

**Comment by nilaoda** [comment]
https://github.com/aria2/aria2/issues/1098
