### ISSUE TITLE
An error occurred trying to start process 'ffmpeg' with working directory 'C:\Users\swkknk'. 系统找不到指定的文件。

### ISSUE THREAD

**Issue by junwenwang1677** [nilaoda/BBDown#245]
An error occurred trying to start process 'ffmpeg' with working directory 'C:\Users\swkknk'. 系统找不到指定的文件。

**Comment by Sod-Momas** [comment]
我遇到了同样的问题

```cmd

Microsoft Windows [版本 10.0.19043.1466]
(c) Microsoft Corporation。保留所有权利。

C:\Users\sod>cd /

C:\>dotnet tool install --global BBDown
可使用以下命令调用工具: BBDown
已成功安装工具“bbdown”(版本“1.4.6”)。

C:\>BBDown https://www.bilibili.com/video/BV1Sz4y1k7tP
BBDown version 1.4.6, Bilibili Downloader.
欢迎到讨论区交流：
https://github.com/nilaoda/BBDown/discussions

[2022-01-16 00:37:43.673] - 获取aid...
[2022-01-16 00:37:43.954] - 获取aid结束: 585526737
[2022-01-16 00:37:43.954] - 获取视频信息...
[2022-01-16 00:37:44.033] - 视频标题: 〖B站首发〗曹雅雯Olivia feat. ?te 坏特《若是明仔载》官方高画质 Official HD MV 闽南语
[2022-01-16 00:37:44.034] - 发布时间: 2020/12/4 20:32:28
[2022-01-16 00:37:44.034] - P1: [262830937] [曹雅雯Olivia feat. te 壞特《若是明仔載》官方高畫質 Official HD MV] [03m47s]
[2022-01-16 00:37:44.034] - 共计 1 个分P, 已选择：ALL
[2022-01-16 00:37:44.034] - 开始解析P1...
[2022-01-16 00:37:44.037] - 下载封面...
[2022-01-16 00:37:44.398] - 共计8条视频流.
                            0. [1080P 高清] [1920x1080] [AVC] [24.390] [2507 kbps] [~69.47 MB]
                            1. [1080P 高清] [1920x1080] [HEVC] [24.390] [1508 kbps] [~41.79 MB]
                            2. [720P 高清] [1280x720] [AVC] [24.390] [1749 kbps] [~48.46 MB]
                            3. [720P 高清] [1280x720] [HEVC] [24.390] [1054 kbps] [~29.21 MB]
                            4. [480P 清晰] [852x480] [AVC] [24.390] [789 kbps] [~21.86 MB]
                            5. [480P 清晰] [852x480] [HEVC] [24.390] [479 kbps] [~13.27 MB]
                            6. [360P 流畅] [640x360] [AVC] [24.390] [353 kbps] [~9.78 MB]
                            7. [360P 流畅] [640x360] [HEVC] [24.390] [217 kbps] [~6.01 MB]
[2022-01-16 00:37:44.400] - 共计3条音频流.
                            0. [M4A] [127 kbps] [~3.52 MB]
                            1. [M4A] [127 kbps] [~3.52 MB]
                            2. [M4A] [67 kbps] [~1.86 MB]
[2022-01-16 00:37:44.402] - 已选择的流:
                            [视频] [1080P 高清] [1920x1080] [AVC] [24.390] [2507 kbps] [~68.86 MB]
                            [音频] [M4A] [127 kbps] [~3.49 MB]
[2022-01-16 00:37:44.403] - 开始下载P1视频...
[2022-01-16 00:37:52.592] - 开始下载P1音频...
[2022-01-16 00:37:53.208] - 下载P1完毕
[2022-01-16 00:37:53.208] - 开始合并音视频...
An error occurred trying to start process 'ffmpeg' with working directory 'C:\'. 系统找不到指定的文件。

C:\>
```

**Comment by Sod-Momas** [comment]
我拉取了代码，然后重新生成了一下，还是有这个问题，我把 Binary 里的 ffmpeg.exe 放到 .\BBDown\BBDown\bin\Debug\net6.0\ 目录下 (与 BBDown.exe 同级) 后就可以正常使用了

**Comment by nilaoda** [comment]
程序会在exe旁边或环境变量里寻找ffmpeg路径

**Comment by ducknessman** [comment]
> 我遇到了同样的问题
> 
> ```batchfile
> Microsoft Windows [版本 10.0.19043.1466]
> (c) 微软公司。保留所有权利。
> 
> C:\用户\sod > cd /
> 
> C:\ > dotnet tool install --global BBDown
> 可以使用以下命令调用工具：BBDown
> 已成功安装工具“bbdown”(版本“1.4.6”)。
> 
> C:\ > BBDown https://www.bilibili.com/video/BV1Sz4y1k7tP
> BBDown 1.4.6 版本，哔​​哩哔哩下载器。
> 到欢迎讨论区交流：
> https://github.com/nilaoda/BBDown/discussions
> 
> [2022-01-16 00:37:43.673] - 获取援助...
> [2022-01-16 00:37:43.954] - 获取援助结束: 585526737
> [2022-01-16 00:37:43.954] - 获取视频信息...
> [2022-01-16 00:37:44.033] - 视频标题：〖B站首发〗曹雅雯Olivia feat. ?te 坏特《你明仔载》官方高画质官方高清MV 闽南语
> [2022-01-16 00:37:44.034] - 发布时间: 2020/12/4 20:32:28
> [2022-01-16 00:37:44.034] - P1: [262830937] [曹雅雯 Olivia feat. te坏特《你质明仔载》官方高清官方高清MV [03m47s]
> [00-01-16 37:44.034] - 00:选择 201 个选择2个分P，已：ALL
> [2022-01-16 00:37:44.034] - 开始解析P1...
> [2022-01-16 00:37:44.037] - 下载封面...
> [2-01-16 37:44.398] - 02: 28 条视频 2 流。
>                             0. [1080P 画面] [1920x1080] [AVC] [24.390] [2507 kbps] [~69.47 MB​​]
>                             1. [1080P 分辨率] [1920x1080] [HEVC] [24.390] [1508 kbps] [~41.79 MB]
>                             2. [720P] [1280x720] [AVC] [24.390] [1749 kbps] [~48.46 MB]
>                             3. [720P] [1280x720] [HEVC] [24.390] [1054 kbps] [~29.21 MB]
>                             4. [480P 清晰度] [852x480] [AVC [24.390] [78kbps] [~21.6 MB]
>                             5. [480P 清晰度] [852x480] [HEVC [24.390] [47 kbps] [~13.7 MB]
>                             6. [360P 像素] [640x360] [AV8C] [24.39] [353 kbps] [~9.9 MB]
>                             7. [360P 像素] [640x360] [HEVC] [24.39] [21kbps] [~6.0 MB]
> [37:44.400] 00: 20: 20: 23-16-01-16 00: 过滤条
>                             0. [M4A] [127 kbps] [~3.52 MB]
>                             1. [M4A] [127 kbps] [~3.52 MB]
>                             2. [M4A] [67 kbps] [~1.86 MB]
> [2022-01-16 00:37:44.402] - 已选择的流：
>                             [视频] [1080P] [1920x1080] [AVC] [24.390] [2507 kbps] [~68.86 MB]
>                             [音频] [M4A] [127 kbps] [~3.49 MB]
> [2022-01-16 00:37:44.403] - 开始下载P1视频...
> [2022-01-16 00:37:52.592] - 开始下载P1音频...
> [2022-01-16 00:37:53.208] - 下载P1完
> [2022-01-16 00:37:53.208] - 开始视频...
> 尝试使用工作目录“C:\”启动进程“ffmpeg”时发生错误。系统找不到指定的文件。
> 
> C:\ >
> ```

如果再windows上
只需要将整个工程拷贝下来，解压到你安装BBDown的文件夹的位置。将Binary里面的另外3个exe文件，与BBDown.exe放在同一路径下，就可以解决这个问题

**Comment by nilaoda** [comment]
新版已解决ffmpeg寻找问题
