### ISSUE TITLE
建议添加自定义 UserAgent 可下载 有8K资源的视频

### ISSUE THREAD

**Issue by wchips** [nilaoda/BBDown#248]
#UserAgent          建议添加自定义UserAgent
#一行一条记录     
#模拟MacOS Safari 最新版浏览器 UserAgent 可下载 有8K资源的视频
#Mozilla/5.0 (Macintosh; Intel Mac OS X 11_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15

**Comment by nilaoda** [comment]
早已支持8K https://github.com/nilaoda/BBDown/actions

不过尚未发布Release

**Comment by wchips** [comment]
> 早已支持8K https://github.com/nilaoda/BBDown/actions
> 
> 不过尚未发布Release

感谢！已经starred了。贪婪下，文件名支持添加BV-[id] AV-[id]会更好！再次感谢！！！
