### ISSUE TITLE
The remote server returned an error: (412) Precondition Failed.

### ISSUE THREAD

**Issue by fvlw** [nilaoda/BBDown#25]
error: (412)  被Bilibili拒绝请求了吗
测试链接 https://www.bilibili.com/video/BV1fK4y1t7hj
希望作者添加一个 -o 参数 可以指定文件输出路径 和 添加抓取xml弹幕功能

![Snipaste_2020-09-20_10-52-07](https://user-images.githubusercontent.com/71577616/93693492-11dfb980-fb33-11ea-9841-135573002a62.png)

**Comment by nilaoda** [comment]
`-c`后面是字符串形式的cookie，不是cookie.txt。
你可以直接使用`BBDown login`来登录

**Comment by fvlw** [comment]
> 
> 
> `-c`后面是字符串形式的cookie，不是cookie.txt。
> 你可以直接使用`BBDown login`来登录



一样的 我省方便加了个txt 其实b站只需要 一个SESSDATA参数就可以了
那个412错误我等了半小时 重新 -info 就可以正常获取视频 应该是我太频繁抓取 被拉黑一段时间

希望作者 添加一个 -o -C 指定输出文件路径 抓取弹幕文件xml 的功能参数   
这工具挺香的 感谢作者的幸苦开发

**Comment by EveElseIf** [comment]
412家常便饭了，我的话就是直接换ip就行了

**Comment by nilaoda** [comment]
#83
