### ISSUE TITLE
非问题  只是询问

### ISSUE THREAD

**Issue by BingChunMoLi** [nilaoda/BBDown#252]
希望知道视频标题过滤后存储文件的规则，B站接口解析出的视频标题含有windows禁止的符号，和 一些 /\ 特殊符号，现在使用BBDown下载后 希望知道文件名，进行上传百度或onedrive使用，因为是sh 批量下载 所以需要知道文件地址 逐个上传

**Comment by hez2010** [comment]
https://github.com/nilaoda/BBDown/blob/9ee389c0fc1aa86119db3b5085a47cf2c502cee9/BBDown/BBDownUtil.cs#L565

**Comment by BingChunMoLi** [comment]
抱歉，非C#开发者，搜索引擎得到结果并不知道是否正确,是把这些字符转换为“.”了吗? 不太理解加号1到31是什么意思
 最佳答案：

无效字符列表为：
<（小于）
>（大于）
：（冒号）
“（双引号）
/（正斜杠）
\（反斜杠）
|（立杆或立管）
？（问号）
*（星号）
加号1到31

**Comment by BingChunMoLi** [comment]
https://www.bilibili.com/video/BV1Vf4y1T7bw 发现似乎没有过滤 \ 生成文件携带\

**Comment by hez2010** [comment]
`Path​.​GetInvalidFileNameChars​()` 是平台相关的，在 Windows 下返回的结果包含 \，而在 Linux 下返回结果不包含 \

**Comment by hez2010** [comment]
Windows 下: `0x22, 0x3c, 0x3e, 0x7c, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x3a, 0x2a, 0x3f, 0x5c, 0x2f`

Linux 下：`0x00, 0x2f`

**Comment by BingChunMoLi** [comment]
感谢，解决了，主要是C#不够熟悉，我是在java端进行业务处理的
