### ISSUE TITLE
请问这两种链接怎么下载？

### ISSUE THREAD

**Issue by lipinghao1986** [nilaoda/BBDown#27]
https://www.bilibili.com/cheese/play/ep68
这套课程我已付费购买，但BBDown貌似不支持下载！

https://www.bilibili.com/video/BV1mZ4y1P7WF
这个页面有4个互动视频，地址都一样，靠点选视频上按钮来观看哪个场景。但地址解析只支持第一个场景的视频！有没有办法让BBDown一次性下载4个场景的视频(总视频长度41.16分钟)，如果是分段最好合拼输出~

**Comment by nilaoda** [comment]
课程已经支持。

互动视频暂时不加。

**Comment by Bubbu0129** [comment]
现在有计划添加“互动视频”的下载功能吗？
