### ISSUE TITLE
尝试使用最新版本的构建出现问题

### ISSUE THREAD

**Issue by dongffan** [nilaoda/BBDown#274]
如题 我使用来自Actions里面的构建，主要是我想体验一些新功能，但是使用最新版本的构建出现解析问题
![屏幕截图 2022-02-26 114132](https://user-images.githubusercontent.com/86098324/155827694-ebf663c6-8e86-49d6-af75-5644f291143c.png)

**Comment by nilaoda** [comment]
在切换到最新dotnet后Native AOT出现一些问题，正在处理
