### ISSUE TITLE
下载时同时登陆，不会执行下载，只执行登录

### ISSUE THREAD

**Issue by Pombeler** [nilaoda/BBDown#29]
`BBDown.exe -ia -mt BV1pp4y1a7A9 login`
下载同时登录，只会登录，并不会执行下载

**Comment by Pombeler** [comment]
> `BBDown.exe -ia -mt BV1pp4y1a7A9 login`
> 下载同时登录，只会登录，并不会执行下载

**Comment by nilaoda** [comment]
就是这样设计的
