### ISSUE TITLE
找不到ffmpeg

### ISSUE THREAD

**Issue by ProgrammerMao** [nilaoda/BBDown#292]
我的粉丝用的时候出了一个问题，提示找不到ffmpeg
![d29cb6e383425dd90c5bcec3f4d54ae96e47a053](https://user-images.githubusercontent.com/72609054/158016867-eb79be17-9694-4888-92b8-6ee570ece584.jpg)
我确认过他的ffmpeg，cmd是能找到的
![4fa59ff0d782085eae6262c81592ab140577fce6](https://user-images.githubusercontent.com/72609054/158016852-e2c72e6e-0e05-4efc-8774-cf327b52b9e5.png)
但是就是在合并的时候提示错误

**Comment by nilaoda** [comment]
1.4.9中将会优化这部分内容，可以尝试使用此版本看问题是否解决

https://github.com/nilaoda/BBDown/actions/runs/2216260479
