### ISSUE TITLE
要是能直接输出metadata JSON，那多事一件美事儿

### ISSUE THREAD

**Issue by mo-han** [nilaoda/BBDown#298]
如今的我沉沦在debug模式下的stdout解析中……

**Comment by xhlove** [comment]
只解析出下载链接的功能？

**Comment by mo-han** [comment]
> 只解析出下载链接的功能？

链接事小
主要是title、desc、owner、staff这类元数据，debug里有现成的JSON串，就是一条条解析还是有点苦手

**Comment by dogdie233** [comment]
那为什么不自己搓一个API的轮子呢😂

**Comment by mo-han** [comment]
> 那为什么不自己搓一个API的轮子呢😂

放着筷子不用，再削两根树枝是吧

**Comment by nilaoda** [comment]
等忙完手头的事我搞一下

**Comment by dogdie233** [comment]
> > 那为什么不自己搓一个API的轮子呢😂
> 
> 放着筷子不用，再削两根树枝是吧

已经有各种语言的sdk了吧，有点难理解为什么要用一个面向用户的程序做解析

**Comment by mo-han** [comment]
@nilaoda 
不用弄这个啦，我自己写的python wrapper已经完成了，所有解析数据都能从debug打印文本中提取出来，没必要费精力搞这个了
