### ISSUE TITLE
MacOSX(BigSur)无法正常运行

### ISSUE THREAD

**Issue by NobodyHere-rrr** [nilaoda/BBDown#30]
如题，big sur无法正常运行，无论iterm还是终端，运行结果如图，提示：
Required argument missing for command: BBDown

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]
<img width="657" alt="截屏2020-09-29 下午9 13 16" src="https://user-images.githubusercontent.com/62543054/94563240-ff831f80-0298-11eb-9893-8914b8c224a9.png">

**Comment by nilaoda** [comment]
BBDown 后面有加视频URL吗？我手头没有Big Sur设备，无法测试。

**Comment by tuzi3040** [comment]
很明显没加
