### ISSUE TITLE
*****************.mcdn.bilivideo.cn:4483

### ISSUE THREAD

**Issue by Tiggggger-0** [nilaoda/BBDown#307]
在登陆后下载视频时，显示“不知道这样的主机。 (*****************.mcdn.bilivideo.cn:4483)”

**刚刚那个Issue被我手贱关了

**Comment by nilaoda** [comment]
pcdn……这玩意很烦

**Comment by Tiggggger-0** [comment]
什么意思qwq

**Comment by dogdie233** [comment]
> 什么意思qwq

鼠鼠为了省钱弄的，要深入了解的话百度搜一下pcdn就知道了

**Comment by nilaoda** [comment]
已强制替换
