### ISSUE TITLE
显示错误

### ISSUE THREAD

**Issue by YUNDAN21** [nilaoda/BBDown#308]
The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
为啥会有这个错误出现啊？要怎么解决

**Comment by dogdie233** [comment]
版本、使用参数

**Comment by rayblade** [comment]
> The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0. 为啥会有这个错误出现啊？要怎么解决

apt-get -y install libcurl4-openssl-dev zlib1g-dev libkrb5-dev

**Comment by ihcbbs** [comment]
> > The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0. 为啥会有这个错误出现啊？要怎么解决
> 
> apt-get -y install libcurl4-openssl-dev zlib1g-dev libkrb5-dev

windows版本下面出现……

**Comment by nilaoda** [comment]
提供一下导致报错的命令行参数。

**Comment by YUNDAN21** [comment]
重启一下电脑就好了，感谢
