### ISSUE TITLE
请求支持B站“HDR真彩”规格和APP独享视频

### ISSUE THREAD

**Issue by nilaoda** [nilaoda/BBDown#31]
HDR：https://www.bilibili.com/video/BV1rp4y1e745
APP独享：https://www.bilibili.com/bangumi/play/ep341977

**Comment by diannaojiang** [comment]
HDR的id是125 但目前用playurl不知为何获取不到  找了半天也没找到一台mac os的safri来测试

**Comment by nilaoda** [comment]
> HDR的id是125 但目前用playurl不知为何获取不到 找了半天也没找到一台mac os的safri来测试

`fnval=80`即可
