### ISSUE TITLE
多p视频下载，弹幕(ass)下载出现问题

### ISSUE THREAD

**Issue by AsuZSH** [nilaoda/BBDown#315]
## 出现很多很多与当前分集无关的弹幕（下载后，接近1500行弹幕，原先大约50行）

xml弹幕应该没有问题

如果单集下载则不会出现此问题
# （经过对比，会把之前视频的弹幕叠加进来，即第60集的ass文件包含了 1-60 集所有的弹幕）

**Comment by bbaa-bbaa** [comment]
release的版本有这个问题 #267 请前往github Action下载最新构建版本


------------------ 原始邮件 ------------------
发件人: Asuka ***@***.***&gt;
发送时间: 2022年4月6日 14:07
收件人: nilaoda/BBDown ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [nilaoda/BBDown] 多p视频下载，弹幕(ass)下载出现问题 (Issue #315)





 
测试视频：BV1GB4y1P79U
 
测试分集：60
 
出现很多很多与当前分集无关的弹幕（下载后，接近1500行弹幕，原先大约50行）
 
xml弹幕应该没有问题
 
如果单集下载则不会出现此问题
 
（经过对比，会把之前视频的弹幕叠加进来，即第60集的ass文件包含了 1-60 集所有的弹幕）
 
感谢大佬！！！
