### ISSUE TITLE
希望加入 相同清晰度 优先 HEVC 的功能

### ISSUE THREAD

**Issue by AsuZSH** [nilaoda/BBDown#316]
### 因为HEVC格式体积较小，所以我会优先下载HEVC格式，但是有些视频 4K 分辨率没有 HEVC 视频，而720p则有HEVC，就导致我下载的不是最高清晰度，每次手动调还挺麻烦的

**Comment by dogdie233** [comment]
新的构建已经有这个功能了

**Comment by shhzhang** [comment]
感谢，已解决！
