### ISSUE TITLE
某些番劇只會下載前 1/4 (6分鐘；全長約24分)

### ISSUE THREAD

**Issue by tonyhsie** [nilaoda/BBDown#320]
我使用 BBDown 一年多了，一直都能正常下載，給我很大幫助，感謝作者

最近連續遇到三個新番劇下載有問題
(都是這兩天新上架、限港澳台區、會員限定的番劇；我在台灣、也有大會員)

有問題的番劇號碼：ep475884 (ss41458 的第2集)、ep475899 (ss41459 的第2集)、ep476331 (ss41486 的第2集)

它們的第1集都能正常下載，但第2集就只會下載前6分鐘的內容
打開下載後的 mp4，雖然看起來片長有 24 分鐘，實際上播放到 06:00 之後就會自動結束

以 ep476331 為例 (下載後播放到 06:00 就會不正常結束，90 MB)
![圖片 2022-04-09 02-56-22](https://user-images.githubusercontent.com/52758827/162505344-b1bc4bb2-3abb-4c75-badd-b17af778db64.png)

同一番劇的第一集 (下載後播放正常，220 MB)
![圖片 2022-04-09 02-52-24](https://user-images.githubusercontent.com/52758827/162505419-0e18fe4d-c6d4-4584-98d3-37dda7598c36.png)

雖然是同一個番劇，但這兩個影片的視頻/音頻流差很多，不曉得是什麼原因
另外，雖然有問題的番劇，上面的 log 只有視頻流，但實際上下載的影片也是有音頻的

**Comment by dogdie233** [comment]
在网页端看理科生P2正常吗(分辨率能调吗)

**Comment by dogdie233** [comment]
有可能是登录掉了(使用bbdown login重新登录)
或者是大会员过期了

**Comment by dogdie233** [comment]
建议加一个登录状态检测

**Comment by tonyhsie** [comment]
> 有可能是登录掉了(使用bbdown login重新登录) 或者是大会员过期了

感謝，重新登錄後，一切都正常了

> 建议加一个登录状态检测

請問要怎麼檢測登錄狀態，有特殊的指令嗎 (我在 -h 裡好像沒看到)

**Comment by dogdie233** [comment]
> > 有可能是登录掉了(使用bbdown login重新登录) 或者是大会员过期了
> 
> 感謝，重新登錄後，一切都正常了
> 
> > 建议加一个登录状态检测
> 
> 請問要怎麼檢測登錄狀態，有特殊的指令嗎 (我在 -h 裡好像沒看到)

暂时没有这个功能，以后写吧w

**Comment by tonyhsie** [comment]
> > > 有可能是登录掉了(使用bbdown login重新登录) 或者是大会员过期了
> > 
> > 
> > 感謝，重新登錄後，一切都正常了
> > > 建议加一个登录状态检测
> > 
> > 
> > 請問要怎麼檢測登錄狀態，有特殊的指令嗎 (我在 -h 裡好像沒看到)
> 
> 暂时没有这个功能，以后写吧w

了解 非常感謝!
