### ISSUE TITLE
哔哩哔哩有一个无法下载

### ISSUE THREAD

**Issue by freework2000** [nilaoda/BBDown#324]
https://www.bilibili.com/video/BV1PZ4y1N7zg?p=4

p4下载提示这个。lux可以正常下载。
The SSL connection could not be established, see inner exception

**Comment by nilaoda** [comment]
下个版本会解决这个问题，现在可以先下载最新的自动构建版本并开启`--force-http`

https://github.com/nilaoda/BBDown/actions/runs/2152529634

**Comment by freework2000** [comment]
好的。下载试试。
要问的是，自动构建版怎么下载，不会。有步骤或者截图没有。百度了一下也没有具体答案。

**Comment by xhlove** [comment]
![image](https://user-images.githubusercontent.com/48152166/163674959-afc7fc59-b154-4753-b504-851a632aa0bb.png)

**Comment by freework2000** [comment]
好的多谢！
测试新版本可以正常下载那个视频了
