### ISSUE TITLE
弹幕链接浏览器访问正常, 但程序下载弹幕出现错误

### ISSUE THREAD

**Issue by lanyuanxiaoyao** [nilaoda/BBDown#325]
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/15119304/163700965-a9c75bda-7423-4508-8390-89a4f9f84885.png">

这是弹幕下载链接, 在不同的系统和网络下都尝试过, 报错相同
http://comment.bilibili.com/91559895.xml

这是视频链接
https://www.bilibili.com/bangumi/play/ss1173

**补充一下, 问题发生在 Actions 版本里面, Release 版本没问题, 但是我需要 force-http**

**Comment by nilaoda** [comment]
试下新的Actions

**Comment by lanyuanxiaoyao** [comment]
ok, 解决问题了
