### ISSUE TITLE
下载 1080P 高码率 存在一个小bug

### ISSUE THREAD

**Issue by AsuZSH** [nilaoda/BBDown#330]
### 感谢大佬！！

**Comment by nilaoda** [comment]
下次调整一下 清晰度优先级大于编码优先级

**Comment by AsuZSH** [comment]
好嘞感谢！

**Comment by dogdie233** [comment]
因为想着是优先保证能播放嘛，清晰度相比编码(决定能不能播放)还是靠边站

**Comment by AsuZSH** [comment]
真有道理哎，也可以加个优先级参数嘛😁

**Comment by dogdie233** [comment]
默认编码优先，然后加个`--dfn-firstly`控制程序清晰度优先(?

**Comment by nilaoda** [comment]
在最新构建中，
* 输入`--encoding-priority "hevc, avc" --dfn-priority "1080P 高帧率, 1080P 高清"`则优先按照编码排序
* 输入`--dfn-priority "1080P 高帧率, 1080P 高清" --encoding-priority "hevc, avc"`则优先按照清晰度排序。

**Comment by AsuZSH** [comment]
好耶！
