### ISSUE TITLE
这是什么情况

### ISSUE THREAD

**Issue by tyzh279** [nilaoda/BBDown#334]
![XZ($}A_PY0UPSJ 23PF YS4](https://user-images.githubusercontent.com/52770990/166142906-9b9a6a4b-b731-4133-ac28-637e2a35c255.png)
用tv接口就会出现这样，不用tv接口就没事

**Comment by nilaoda** [comment]
https://github.com/nilaoda/BBDown/actions

**Comment by tyzh279** [comment]
> https://github.com/nilaoda/BBDown/actions

这个怎么用，有教程吗

**Comment by nilaoda** [comment]
https://github.com/nilaoda/BBDown/suites/6324650755/artifacts/227307276
