### ISSUE TITLE
Required argument missing for command: BBDown

### ISSUE THREAD

**Issue by Jianningyuan** [nilaoda/BBDown#335]
每次设置目录或其他的时候总是Required argument missing for command: BBDown
已经在bbdown目录运行了

**Comment by nilaoda** [comment]
你用的完整命令是什么？

**Comment by Jianningyuan** [comment]
BBDown -mt -BV

**Comment by Jianningyuan** [comment]
BBDown --work_dir <>
和其余的命令

**Comment by Jianningyuan** [comment]
除了直接下载其余用不了

**Comment by fcwys** [comment]
我的也是，没法用

**Comment by fcwys** [comment]
找到原因了。。。，当使用命令“BBDown“是大写时正常，使用全小写时就报错，希望作者修复下大小写敏感问题，谢谢！

小写时：
![image](https://user-images.githubusercontent.com/28641034/167359205-75943348-ca32-41da-aac4-7416e3fedb8d.png)

大写时：
![image](https://user-images.githubusercontent.com/28641034/167359322-35597112-495f-4ec2-9fdd-6a38ec84a120.png)

**Comment by Jianningyuan** [comment]
damshi

**Comment by Jianningyuan** [comment]
我依旧不行啊

**Comment by Jianningyuan** [comment]
BBDown.exe --aria2c-path ""这串指令依旧不行

**Comment by nilaoda** [comment]
> BBDown.exe --aria2c-path ""这串指令依旧不行

请展示你的完整命令

**Comment by Jianningyuan** [comment]
不好意思，前几天考试
完整命令为
BBDown.exe --work-dir "D:\BilibiliDownloadFile"

**Comment by Jianningyuan** [comment]
报错依旧位上面的

**Comment by nilaoda** [comment]
> 报错依旧位上面的

你没有输入要下载的网址吗

**Comment by Jianningyuan** [comment]
输了依旧报错

**Comment by Jianningyuan** [comment]
现在又不报错了

**Comment by Jianningyuan** [comment]
梦幻的很

**Comment by Jianningyuan** [comment]
顺便问个问题，可以一劳永逸的设置各种目录而不用每次都打路径吗，没有的话就算了

**Comment by nilaoda** [comment]
> 顺便问个问题，可以一劳永逸的设置各种目录而不用每次都打路径吗，没有的话就算了

参考readme中 配置文件的部分

**Comment by jacksong01** [comment]
我打开闪退，用cmd打开，提示Required argument missing for command: BBDown，大佬怎么解决。 以前没用过，刚下载第一次用。

**Comment by nilaoda** [comment]
> 我打开闪退，用cmd打开，提示Required argument missing for command: BBDown，大佬怎么解决。 以前没用过，刚下载第一次用。

请阅读readme中的示例部分
