### ISSUE TITLE
希望标题自定义能加入作者名称

### ISSUE THREAD

**Issue by vvyoko** [nilaoda/BBDown#340]
标题和BV AV号辨识不够
没有作者名称根本不知道是谁发的.
比方说就现在的热门
就是这样的

女仆妹妹的笑容可爱吗 (〃'▽'〃)
僵尸娘 但是真人版！
....

**Comment by vvyoko** [comment]
我看最新的测试版支持这些选项
非常感谢 yukinotech 大佬的贡献


在此报一个小BUG
F 参数部分不能以`@`开头,中间包含`@`没事
比方说这样
`BBDown -F "@<ownerName> <videoTitle> av<aid>"`

我测试了旧版也会出错,比方说这样
`BBDown -F "@<videoTitle> av<aid>"`
应该不是新版出现的问题

**Comment by nilaoda** [comment]
@vvyoko 

我扒了一下源码，在`command-line-api`中，默认开启了`TokenReplacement`机制，所有以`@`开头的参数会被解析为`Response File`，当解析到`@<ownerName> <videoTitle> av<aid>`时，会去寻找`<ownerName> <videoTitle> av<aid>`文件并读取该文件中的内容作为参数解析，而这个文件实际并不存在，这个参数就被忽略了…… 

测试了一下，建立一个文件`file_format.txt`，内容如下
```
<ownerName> <videoTitle> av<aid>
```

然后执行`BBDown -F "@file_format.txt" "http://xxx"`可以正常识别并读取参数

但是如果文件内容为
```
@<ownerName> <videoTitle> av<aid>
```

就开始套娃了，还是无法解析……

一个折中的办法就是使用`-F "\@file_format.txt"`让它不被解析为`Response File`，但是这样的话程序需要手动去处理多余的`\`

看下是否真的需要使用`@`作为文件命名的起始字符……改这个感觉挺奇怪的😂

---

不过这个`Response File`的解析挺有意思，实测可以代替上个版本新搞的配置文件功能……
```
#本文件是BBDown程序的配置文件
#以#开头的都会被程序忽略
#然后剩余非空白内容程序逐行读取，对于一个选项，其参数应当在下一行出现

#例如下面将设置输出文件名格式
--file-pattern
<videoTitle>[<dfn>]

--multi-file-pattern
<videoTitle>/[P<pageNumberWithZero>]<pageTitle>[<dfn>]

#下面设置下载多个分P时，每个分P的下载间隔为2秒
--delay-per-page
2

#开启弹幕下载功能
--download-danmaku
```

保存为`b.config`然后使用`BBDown @b.config`即可正常调用

要是早知道可以这样读取本地配置，我更新了个寂寞属于是……

---

该命令行解析库的相同反馈：https://github.com/dotnet/command-line-api/issues/816

**Comment by yukinotech** [comment]
@nilaoda 
个人觉着还是自己解析好：
1、自己解析的话自定义程度高，比如可以自己支持一行的参数
2、命令行里多加一个@，解析为Response File的行为，不知道跨平台有没有坑
3、最后就是一个优雅的问题吧。当然，这个纯粹是个人觉得有点丑......

**Comment by vvyoko** [comment]
@nilaoda 太过复杂就不用管啦
避免这个的方法很多
```
    下载后重命名
    参数加入路径
        BBDown -F "bilibili\@<ownerName> <videoTitle> av<aid>"
```

比我以前的处理方法已经好太多了....
以前没 `F` 参数前我都是用脚本处理的...
脚本内容都超过100行...
```
    首先解析API获取 作者名, 标题, p号, p标题, av号....(差不多是自己实现了一遍)
    然后等待 BBDown 下载完成
    再然获取 BBDown 下载完成的文件名 
        单P<videoTitle> 
        多P <videoTitle>/[P<pageNumberWithZero>]<pageTitle>
    因为我是windows,还要检查文件名是否包含 /\:*?<>| 并替换...
    最后才把 BBDown 下载的文件重命名成现在的 @<ownerName> <videoTitle> av<aid>
```

由于 `F` 最近才新增 `ownerName` 参数,我一直是这样处理的.
现在方便太多了.


@yukinotech 
加`@`主要是为了标识这是作者名
就像这一样
```
    用 p1 p2 标识 p号
    用 av<aid> 标识 av号
```


最后感谢两位大佬的工作
祝生活愉快

**Comment by vvyoko** [comment]
经过测试,大概完美了,关闭此issues
感谢

**Comment by wangfeng35** [comment]
原来命名要用双引号“” 怪不得总是报错

**Comment by nilaoda** [comment]
关于响应文件的官方描述：

https://docs.microsoft.com/zh-cn/dotnet/standard/commandline/syntax#response-files
