### ISSUE TITLE
1.5.0 Release无法登录

### ISSUE THREAD

**Issue by Goojoe** [nilaoda/BBDown#345]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
1.5.0 Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows 11 Pro 22000.652
Windows terminal 1.12.10983.0

#### 3. 你使用的完整命令是什么？
```
BBDown login
```
#### 4. 遇到了什么问题？
1.5.0 Release无法登录,1.4.9 Release正常
报错:`Required argument missing for command: BBDown`

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://user-images.githubusercontent.com/78355492/167288952-9f031f4d-b8a6-46ef-8668-1da58ba490be.png)

**Comment by nilaoda** [comment]
1.5.1已修复
