### ISSUE TITLE
[题外话]关于哔哩哔哩Web端地区限制问题

### ISSUE THREAD

**Issue by Goojoe** [nilaoda/BBDown#348]
# 哔哩哔哩Web端地区限制问题
正常在哔哩哔哩Web端观看,使用国内IP普通视频可以正常观看,但是一旦我加上国外代理,就不能看普通视频了

![image](https://user-images.githubusercontent.com/78355492/167894484-c55a5402-cd26-4d21-98fc-112110597714.png)

按这个限制,理论上我在外国服务器下载,也会被限制,但是下载没有任何问题
所以请问是用什么破除限制的?或者原理是什么?

**Comment by nilaoda** [comment]
软件本身只是正常请求web api而已，没有做任何特殊处理
