### ISSUE TITLE
建议 自訂檔案名，檔案格式，存放路徑

### ISSUE THREAD

**Issue by RyanL-29** [nilaoda/BBDown#35]
可自訂檔案名前後綴

檔案名第一集改為 01 而非 1

檔案格式 e.g. mkv

存放路徑，不限只放於根目錄，可放其他地方

**Comment by nilaoda** [comment]
本软件的推荐使用方式：
将本软件所在路径加入你的环境变量`PATH`中，随后在目标文件夹中执行命令即可下载&合并到此目录。

关于你提到的文件格式，目前提供了`--skip-mux`跳过混流步骤，你可以自行使用mkvmerge进行封装。

最后文件名前缀，目前感觉没有什么实际用处，如果有其他人也需要这个功能，我再加吧。

**Comment by mo-han** [comment]
@nilaoda 
附议，我也需要自定义文件名，最好按照某种格式自定义，就类似`youtube-dl`那样。
这背后需要的工作量说大不大说小不小，单就堪堪能用的程度不需要多少行代码，但若要做到大而全把所有常用关键字变量全支持那肯定是大费周章的，不过这真没必要（我觉得……
我是只会python，不然就直接开PR了，现在我在寻思着用python给BBDown做个基于子进程调用的封装，在这个封装里通过管道捕获打印信息，把关键信息找出来，再自行爬取所需信息，然后对已下载文件、文件夹作重命名。我是真的黔驴技穷了，想不出更好的办法。

我个人喜欢的下载文件名格式是这样的：`标题 [bilibili BV号 av号][上传用户名] 分P - 分P子标题.mp4`，已经用这套格式下载了数不清的视频，用的工具是自己魔改（代码乱七八糟 ← 魔）的`you-get`。you-get大小问题还挺多的，有些我是真的改不了或者嫌烦不想动它了，比如有些老旧视频的1080p60、1080p+的视频流，you-get解析不出来（加了fnval参数就只有dash流了，那些个旧视频的大会员高清流偏偏没有dash流），我是决定放弃了。众里寻他千百度，找到这个项目，用了一下挺好，可惜不能自定义文件名格式。

**Comment by nilaoda** [comment]
> @nilaoda
> 附议，我也需要自定义文件名，最好按照某种格式自定义，就类似`youtube-dl`那样。
> 这背后需要的工作量说大不大说小不小，单就堪堪能用的程度不需要多少行代码，但若要做到大而全把所有常用关键字变量全支持那肯定是大费周章的，不过这真没必要（我觉得……
> 我是只会python，不然就直接开PR了，现在我在寻思着用python给BBDown做个基于子进程调用的封装，在这个封装里通过管道捕获打印信息，把关键信息找出来，再自行爬取所需信息，然后对已下载文件、文件夹作重命名。我是真的黔驴技穷了，想不出更好的办法。
> 
> 我个人喜欢的下载文件名格式是这样的：`标题 [bilibili BV号 av号][上传用户名] 分P - 分P子标题.mp4`，已经用这套格式下载了数不清的视频，用的工具是自己魔改（代码乱七八糟 ← 魔）的`you-get`。you-get大小问题还挺多的，有些我是真的改不了或者嫌烦不想动它了，比如有些老旧视频的1080p60、1080p+的视频流，you-get解析不出来（加了fnval参数就只有dash流了，那些个旧视频的大会员高清流偏偏没有dash流），我是决定放弃了。众里寻他千百度，找到这个项目，用了一下挺好，可惜不能自定义文件名格式。

和这个讨论类似 https://github.com/nilaoda/BBDown/discussions/100 

之后应该会增加一个配置文件来实现自定义

**Comment by tonyhsie** [comment]
> @nilaoda
> 附议，我也需要自定义文件名，最好按照某种格式自定义，就类似`youtube-dl`那样。
> 这背后需要的工作量说大不大说小不小，单就堪堪能用的程度不需要多少行代码，但若要做到大而全把所有常用关键字变量全支持那肯定是大费周章的，不过这真没必要（我觉得……
> 我是只会python，不然就直接开PR了，现在我在寻思着用python给BBDown做个基于子进程调用的封装，在这个封装里通过管道捕获打印信息，把关键信息找出来，再自行爬取所需信息，然后对已下载文件、文件夹作重命名。我是真的黔驴技穷了，想不出更好的办法。
> 
> 我个人喜欢的下载文件名格式是这样的：`标题 [bilibili BV号 av号][上传用户名] 分P - 分P子标题.mp4`，已经用这套格式下载了数不清的视频，用的工具是自己魔改（代码乱七八糟 ← 魔）的`you-get`。you-get大小问题还挺多的，有些我是真的改不了或者嫌烦不想动它了，比如有些老旧视频的1080p60、1080p+的视频流，you-get解析不出来（加了fnval参数就只有dash流了，那些个旧视频的大会员高清流偏偏没有dash流），我是决定放弃了。众里寻他千百度，找到这个项目，用了一下挺好，可惜不能自定义文件名格式。

我用 C# 就寫了一個「给BBDown做个基于子进程调用的封装，在这个封装里通过管道捕获打印信息，把关键信息找出来，再自行爬取所需信息，然后对已下载文件、文件夹作重命名。」這樣的程式

主要是因為抓番劇時每次要下指令指定 ss編號、集數 太過麻煩，另外能自動重命名下載的文件/文件夾也是一個點

這個程式透過讀取一個文字檔
![圖片 2021-07-17 18-35-28](https://user-images.githubusercontent.com/52758827/126034451-3b621ec6-f11b-44a6-b330-beebef392611.png)

在每次執行時，能自動檢查目前是否有新的一集，有的話，就自動開始下載、重命名，並記錄進度
平時只要維護這個文字檔，就能新增/移除要下載的目標番劇

我覺得自己做個殼來調用 BBDown 是很容易且方便的
如果要把這些功能整合進 BBDown 裡，可能會太過複雜而難以使用

所以我也建議，如果 @mo-han 你有一些特定需求，又有程設能力的話，自己打造一個殼來調用 BBDown 會是最能符合自己需求的解決方案

**Comment by RyanL-29** [comment]
> > @nilaoda
> > 附议，我也需要自定义文件名，最好按照某种格式自定义，就类似`youtube-dl`那样。
> > 这背后需要的工作量说大不大说小不小，单就堪堪能用的程度不需要多少行代码，但若要做到大而全把所有常用关键字变量全支持那肯定是大费周章的，不过这真没必要（我觉得……
> > 我是只会python，不然就直接开PR了，现在我在寻思着用python给BBDown做个基于子进程调用的封装，在这个封装里通过管道捕获打印信息，把关键信息找出来，再自行爬取所需信息，然后对已下载文件、文件夹作重命名。我是真的黔驴技穷了，想不出更好的办法。
> > 我个人喜欢的下载文件名格式是这样的：`标题 [bilibili BV号 av号][上传用户名] 分P - 分P子标题.mp4`，已经用这套格式下载了数不清的视频，用的工具是自己魔改（代码乱七八糟 ← 魔）的`you-get`。you-get大小问题还挺多的，有些我是真的改不了或者嫌烦不想动它了，比如有些老旧视频的1080p60、1080p+的视频流，you-get解析不出来（加了fnval参数就只有dash流了，那些个旧视频的大会员高清流偏偏没有dash流），我是决定放弃了。众里寻他千百度，找到这个项目，用了一下挺好，可惜不能自定义文件名格式。
> 
> 我用 C# 就寫了一個「给BBDown做个基于子进程调用的封装，在这个封装里通过管道捕获打印信息，把关键信息找出来，再自行爬取所需信息，然后对已下载文件、文件夹作重命名。」這樣的程式
> 
> 主要是因為抓番劇時每次要下指令指定 ss編號、集數 太過麻煩，另外能自動重命名下載的文件/文件夾也是一個點
> 
> 這個程式透過讀取一個文字檔
> ![圖片 2021-07-17 18-35-28](https://user-images.githubusercontent.com/52758827/126034451-3b621ec6-f11b-44a6-b330-beebef392611.png)
> 
> 在每次執行時，能自動檢查目前是否有新的一集，有的話，就自動開始下載、重命名，並記錄進度
> 平時只要維護這個文字檔，就能新增/移除要下載的目標番劇
> 
> 我覺得自己做個殼來調用 BBDown 是很容易且方便的
> 如果要把這些功能整合進 BBDown 裡，可能會太過複雜而難以使用
> 
> 所以我也建議，如果 @mo-han 你有一些特定需求，又有程設能力的話，自己打造一個殼來調用 BBDown 會是最能符合自己需求的解決方案

我這個Extension不知可不可以幫到你 [BBDownAutoExtension](https://github.com/RyanL-29/BBDownAutoExtension/tree/master), 不過這個要用我編譯的 [BBDown](https://github.com/RyanL-29/BBDown/tree/master) 使用, 修改了cookie 獨立了出來成為cookie.txt, 然後config檔可以設定影片儲存路徑.

**Comment by tonyhsie** [comment]
> > > @nilaoda
> > > 附议，我也需要自定义文件名，最好按照某种格式自定义，就类似`youtube-dl`那样。
> > > 这背后需要的工作量说大不大说小不小，单就堪堪能用的程度不需要多少行代码，但若要做到大而全把所有常用关键字变量全支持那肯定是大费周章的，不过这真没必要（我觉得……
> > > 我是只会python，不然就直接开PR了，现在我在寻思着用python给BBDown做个基于子进程调用的封装，在这个封装里通过管道捕获打印信息，把关键信息找出来，再自行爬取所需信息，然后对已下载文件、文件夹作重命名。我是真的黔驴技穷了，想不出更好的办法。
> > > 我个人喜欢的下载文件名格式是这样的：`标题 [bilibili BV号 av号][上传用户名] 分P - 分P子标题.mp4`，已经用这套格式下载了数不清的视频，用的工具是自己魔改（代码乱七八糟 ← 魔）的`you-get`。you-get大小问题还挺多的，有些我是真的改不了或者嫌烦不想动它了，比如有些老旧视频的1080p60、1080p+的视频流，you-get解析不出来（加了fnval参数就只有dash流了，那些个旧视频的大会员高清流偏偏没有dash流），我是决定放弃了。众里寻他千百度，找到这个项目，用了一下挺好，可惜不能自定义文件名格式。
> > 
> > 
> > 我用 C# 就寫了一個「给BBDown做个基于子进程调用的封装，在这个封装里通过管道捕获打印信息，把关键信息找出来，再自行爬取所需信息，然后对已下载文件、文件夹作重命名。」這樣的程式
> > 主要是因為抓番劇時每次要下指令指定 ss編號、集數 太過麻煩，另外能自動重命名下載的文件/文件夾也是一個點
> > 這個程式透過讀取一個文字檔
> > ![圖片 2021-07-17 18-35-28](https://user-images.githubusercontent.com/52758827/126034451-3b621ec6-f11b-44a6-b330-beebef392611.png)
> > 在每次執行時，能自動檢查目前是否有新的一集，有的話，就自動開始下載、重命名，並記錄進度
> > 平時只要維護這個文字檔，就能新增/移除要下載的目標番劇
> > 我覺得自己做個殼來調用 BBDown 是很容易且方便的
> > 如果要把這些功能整合進 BBDown 裡，可能會太過複雜而難以使用
> > 所以我也建議，如果 @mo-han 你有一些特定需求，又有程設能力的話，自己打造一個殼來調用 BBDown 會是最能符合自己需求的解決方案
> 
> 我這個Extension不知可不可以幫到你 [BBDownAutoExtension](https://github.com/RyanL-29/BBDownAutoExtension/tree/master), 不過這個要用我編譯的 [BBDown](https://github.com/RyanL-29/BBDown/tree/master) 使用, 修改了cookie 獨立了出來成為cookie.txt, 然後config檔可以設定影片儲存路徑.

非常感謝

不過我自己寫的程式也發展半年了，目前該有的功能都很齊全
可以自動判斷集數、遇到特定錯誤自動修正參數再次重抓....等等

有什麼需求也可以自己完成，比較方便


不過你要不要考慮一下，讓你的程式跟 BBDown 主程式盡量脫勾
在不需要另外編譯 BBDown 的情況下，也能使用你的程式

不然每次 BBDown 改版，你那邊也要跟著改，比較麻煩

**Comment by mo-han** [comment]
我自己用python写的wrapper库完成了，元数据提取、画质自动挑选、文件重命名这几个痛点都满足了。
https://github.com/mo-han/mo-han-toolbox/blob/master/ezpykitext/puppeteer/BBDown.py
仅供参考，看似两三百行，但是依赖了大量自己设计、魔改的基础库，所以并不能单文件直接使用。
重命名的实现原理偷了个巧，直接在临时文件夹里下载，然后把需要的文件移出来。
P.S. 尽量用aria2c，尽量别用-mt
