### ISSUE TITLE
最近下载的up素材水印都去不掉，是出现啥问题了么？还是怎么回事

### ISSUE THREAD

**Issue by tonpay3** [nilaoda/BBDown#351]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
xxx

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by hez2010** [comment]
水印是直接编码在视频上的，和下载渠道无关
