### ISSUE TITLE
Required argument missing for command

### ISSUE THREAD

**Issue by SA-Root** [nilaoda/BBDown#352]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release-1.5.3

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows 11 Build 22616 x64

#### 3. 你使用的完整命令是什么？
```
BBDown -app -token [保密] -hevc -ia --debug "BV1KS4y197BN"
```
#### 4. 遇到了什么问题？
提示缺少参数

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://user-images.githubusercontent.com/73736681/168469353-f76ce65d-70a5-44c9-80ac-936b37f8ad05.png)

**Comment by nilaoda** [comment]
需要将`x64_BBDown`重命名为`BBDown`以正常工作。

这个后面有机会再优化一下……
