### ISSUE TITLE
可否修改下国际版码率跟文件大小排序问题

### ISSUE THREAD

**Issue by JIKEXIU** [nilaoda/BBDown#354]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release版本v1.5.3 

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win10

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
破站国际版解析出来的链接HEVC在最上面，且自动下载也是默认HEVC。能否改成跟国内版一样，默认排序码率跟文件大小靠前，下载也是高码率AVC优先，谢谢！

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![QQ截图20220516235307](https://user-images.githubusercontent.com/53504145/168634988-94b64778-46b1-4c04-8a94-fa67efbf2fcb.png)
![88888888888888888888](https://user-images.githubusercontent.com/53504145/168635822-6174670a-7012-4c1c-8751-2f9f3075ae56.png)

**Comment by nilaoda** [comment]
你的完整命令行是什么？我测了一下排序是正常的

![image](https://user-images.githubusercontent.com/20772925/168644836-4753e916-28e7-422d-addf-91a69e887930.png)

**Comment by JIKEXIU** [comment]
> 你的完整命令行是什么？我测了一下排序是正常的
> 
> ![image](https://user-images.githubusercontent.com/20772925/168644836-4753e916-28e7-422d-addf-91a69e887930.png)
> 

排序不正常是使用了某个大佬的BBDown gui造成的，后来用命令行一切正常。
