### ISSUE TITLE
macOS 下无法执行 login 命令

### ISSUE THREAD

**Issue by foisonocean** [nilaoda/BBDown#37]
OS Version: macOS 10.15.7

直接下载视频没问题，执行 login 命令出现 “The type initializer for 'Gdip' threw an exception” 的错误：`The type initializer for 'Gdip' threw an exception`

<img width="912" alt="CleanShot 2020-10-07 at 20 54 28@2x" src="https://user-images.githubusercontent.com/15059605/95333521-7777c800-08df-11eb-80aa-7e29e74ca486.png">

**Comment by foisonocean** [comment]
不好意思，和 #19 和 #34 重复了。
不过我建议最好能在 README 里面说明这个步骤，不然不翻 issue 根本不知道怎么处理。
或者能更进一步，直接在 target Linux/macOS 的时候静态链接 gdiplus，省去了用户自行下载依赖库的烦恼。

**Comment by nilaoda** [comment]
嗯

**Comment by bamboo512** [comment]
对于 macOS，使用 Homebrew 安装 `mono-libgdiplus` 即可解决报错。
```Shell
brew install mono-libgdiplus
```

**Comment by ZiLoong-L** [comment]
最新版MacOS会提示Warning: You are using macOS 12.

**Comment by Freemanysz** [comment]
运行 brew install mono-libgdiplus 之后，即使重启terminal 还是继续报这个错误啊

**Comment by 4yingxiang** [comment]
> 运行 brew install mono-libgdiplus 之后，即使重启terminal 还是继续报这个错误啊 更新： 应该是M1芯片的mac 通过homebrew 安装之后的问题，因为homebrew 在intel mac 上是安装到/usr/local， 但是M1的是安装到/opt/homebrew。 在网上搜了一下，配置一下：export DYLD_FALLBACK_LIBRARY_PATH="/opt/homebrew/lib/" 就可以了，参考：https://supportcenter.devexpress.com/ticket/details/t1047142/the-libgdiplus-library-cannot-be-loaded-on-an-apple-m1-arm-based-machine-with-mac-os

哥，新手小白，和你遇到了同样的问题，也是m1版本登陆报错，想问一下如何配置：export DYLD_FALLBACK_LIBRARY_PATH="/opt/homebrew/lib/"  求教方法

**Comment by Freemanysz** [comment]
> > 运行 brew install mono-libgdiplus 之后，即使重启terminal 还是继续报这个错误啊 更新： 应该是M1芯片的mac 通过homebrew 安装之后的问题，因为homebrew 在intel mac 上是安装到/usr/local， 但是M1的是安装到/opt/homebrew。 在网上搜了一下，配置一下：export DYLD_FALLBACK_LIBRARY_PATH="/opt/homebrew/lib/" 就可以了，参考：https://supportcenter.devexpress.com/ticket/details/t1047142/the-libgdiplus-library-cannot-be-loaded-on-an-apple-m1-arm-based-machine-with-mac-os
> 
> 哥，新手小白，和你遇到了同样的问题，也是m1版本登陆报错，想问一下如何配置：export DYLD_FALLBACK_LIBRARY_PATH="/opt/homebrew/lib/" 求教方法

直接在 终端 (terminal) 复制粘贴 回车，运行这个命令即可
