### ISSUE TITLE
下载视频较多时容易触发api限制，希望可以参数控制间隔时间

### ISSUE THREAD

**Issue by xvzhenduo** [nilaoda/BBDown#383]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release v1.5.3

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
BBDown -tv -token {这里是我的token} -mt -p 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,122,23,24 "ss26579"
```
#### 4. 遇到了什么问题？
下载到20p的时候貌似就触发api限制了(下载进度卡在那里，重新下载也一样，我在使用第三方客户端时，就什么也加载不出来)
![image](https://user-images.githubusercontent.com/74353173/178974581-92c71e62-b110-4c63-91dd-b43ce3ed78cb.png)

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
忘记截了，目前已经好了

希望可以加一个参数，在下载完一个视频后间隔指定时间再下载下一个视频

**Comment by nilaoda** [comment]
```
  --delay-per-page <delay-per-page>              设置下载合集分P之间的下载间隔时间(单位: 秒, 默认无间隔)
```

**Comment by codingToPerfection** [comment]
# 我下载一个200p的 BVXXXXX. --delay-per-page 10 是否够用

我注意到：`--delay-per-page 3`会导致大约p=20的时候，进度条停止发展。

我下载一个200p的 BVXXXXX. --delay-per-page 10 是否够用？
