### ISSUE TITLE
Win版 --work-dir 参数是否不支持带环境变量的路径

### ISSUE THREAD

**Issue by DCxDESIGN** [nilaoda/BBDown#390]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
220714 Actions

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
`bbdown BV1fB4y1h76Z --work-dir %HOMEDRIVE%%HOMEPATH%\desktop`
或者
`bbdown BV1fB4y1h76Z --work-dir "%HOMEDRIVE%%HOMEPATH%\desktop"`

#### 4. 遇到了什么问题？
我一般在 PowerShell 下运行 BBDown，并且工作路径默认是在桌面，在我运行上述命令，或者不带参数改为在 BBDown.config 里配置成
```
--work-dir
%HOMEDRIVE%%HOMEPATH%\desktop
```
或者
```
--work-dir
"%HOMEDRIVE%%HOMEPATH%\desktop"
```
的时候，它并不会按照预期直接在桌面放置下载文件，而是在我的默认工作路径下再新建名为 %HOMEDRIVE%%HOMEPATH% 的文件夹，里面再新建 desktop 文件夹，再放置下载文件，如下图所示：
![SShot-20220717-003015-explorer](https://user-images.githubusercontent.com/48208459/179364065-ab2d4ac2-403e-4fdb-88b9-7b89abc61469.png)

想了解一下 BBDown 目前参数是不是不支持 Win 下 %% 这样的环境变量作为路径，如果确实不支持的话，以后有支持的可能吗？

非常感谢

**Comment by nilaoda** [comment]
暂不支持
