### ISSUE TITLE
添加了--video-only参数但仍然显示下载了音频(单纯的显示BUG)

### ISSUE THREAD

**Issue by Miuzarte** [nilaoda/BBDown#391]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release 1.5.3

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win10 19044.1826

#### 3. 你使用的完整命令是什么？
```
bbdown -app -ia --video-only av679989972
```
#### 4. 遇到了什么问题？
~~添加了--video-only参数但似乎仍然下载了音频？~~
只是显示bug，实际下载的文件没有音频
但是下载开始前还是会访问aclip文件  不知道为什么，因为本来一开始只想要音频  途中突然又想要视频了，开始下的时候(`--video-only`)会提示无法访问aclip文件的错误然后程序终止
```
[2022-07-17 07:34:18.782] - 开始合并音视频...
```

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://user-images.githubusercontent.com/66856838/179375161-f8cde90e-eec3-4806-8741-6a3e41ddb38c.png)

**Comment by nilaoda** [comment]
这不是BUG，而是接口没有提供纯视频文件，所以只能下载整个FLV，然后只保留视频。
