### ISSUE TITLE
visual studio analyzer dependences 报错

### ISSUE THREAD

**Issue by ttys000** [nilaoda/BBDown#392]
已安装 .Net 7.0 SDK preview6，使用 dotnet 命令 build 一切正常。
使用 visual studio 2022 打开 sln 文件，build solution 失败。
项目依赖的 Analyzer 中有很多报错，如：
<img width="283" alt="image" src="https://user-images.githubusercontent.com/12792995/179402505-59e36e73-fa18-496a-b7de-67bd7b8d12ad.png">
导致源文件中也会有一些错误告警，对 visual studio 不太熟悉，请问该如何正确设置 analyzer？

**Comment by hez2010** [comment]
这些不是报错，这些只是用来给你展示Analyzers里有哪些规则。

**Comment by ttys000** [comment]
> 

<img width="600" alt="image" src="https://user-images.githubusercontent.com/12792995/179438385-0d2c9359-4a5e-4fdb-8ae8-a81b04cbe90a.png">

**Comment by ttys000** [comment]
> 这些不是报错，这些只是用来给你展示Analyzers里有哪些规则。 能否截一张错误窗口中的提示？

<img width="600" alt="image" src="https://user-images.githubusercontent.com/12792995/179438415-a23e72ec-d772-4464-8481-d7c1ffe0c1b1.png">

**Comment by ttys000** [comment]
从错误列表上看，就像是语法分析器的问题。

**Comment by hez2010** [comment]
你可能没有在vs的设置中开启“使用 .NET 预览版 SDK”

**Comment by ttys000** [comment]
> 你可能没有在vs的设置中开启“使用 .NET 预览版 SDK”

是这个么？我已经勾选了，没找到其他的配置。

<img width="584" alt="image" src="https://user-images.githubusercontent.com/12792995/179449120-a8e75057-a665-44c0-85dd-c90f024ea32b.png">
