### ISSUE TITLE
Value cannot be null. Parameter name: path1

### ISSUE THREAD

**Issue by aliofwind** [nilaoda/BBDown#4]
D:\BBDown>.\BBDown av884123171 -mt
BBDown version 20200731.1[Beta], Bilibili Downloader.
请注意：这是一个测试版本，任何BUG请前往以下网址反馈：
https://github.com/nilaoda/BBDown/issues

Value cannot be null. Parameter name: path1

**Comment by nilaoda** [comment]
已经修复

**Comment by ViggoC** [comment]
遇到了同样的问题。
Linux 和 windows 均复现：`BBDown --audio-only BV1pL411N7j1`，去掉 `--audio-only` 可正常运行，version 1.4.8
