### ISSUE TITLE
能否添加指定本地代理连接

### ISSUE THREAD

**Issue by zgbjwzh** [nilaoda/BBDown#40]
比如说本地http代理，socks代理地址选择

**Comment by nilaoda** [comment]
目前程序自动使用系统的http代理，暂时不支持socks5等协议

**Comment by zgbjwzh** [comment]
可是实际上并未使用系统的http代理，我需要使用sstap开到走虚拟网卡才可以

**Comment by nilaoda** [comment]
![image](https://user-images.githubusercontent.com/20772925/95658583-16a1f700-0b4e-11eb-89ca-aba2caff2b36.png)

没有问题的

**Comment by zgbjwzh** [comment]
我是用的是Windows server2012R2并非W10，代理服务器设置仅在IE浏览器里面设置了

**Comment by zgbjwzh** [comment]
后期是否可以添加单独选择的参数，万分感谢
