### ISSUE TITLE
合并视频失败

### ISSUE THREAD

**Issue by holll** [nilaoda/BBDown#403]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
BBDown v1.5.3

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
BBDown BV1G34y1E7eZ
```
#### 4. 遇到了什么问题？
合并视频失败

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://user-images.githubusercontent.com/36074987/180628759-ce893b39-8a69-4b2b-90ec-307eb8ad9aa9.png)

**Comment by nilaoda** [comment]
临时解决方案：

```
BBDown -M "横屏+竖屏/[P<pageNumberWithZero>]<pageTitle>" BV1G34y1E7eZ
```
