### ISSUE TITLE
收藏夹列表解析报错

### ISSUE THREAD

**Issue by shelken** [nilaoda/BBDown#411]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）

Actions版本: Merge pull request from hez2010/master Build Latest 96

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。
m1 Mac Mini

#### 3. 你使用的完整命令是什么？
```
./BBDown https://space.bilibili.com/30868158/favlist\?fid\=86964258 --debug -app -dd -info --work-dir . --ffmpeg-path /opt/homebrew/bin/ffmpeg > debug.log
```
#### 4. 遇到了什么问题？

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/33972006/183297408-f8e737de-4265-4668-ae6a-da779b5a8ccc.png">

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。
[debug.log](https://github.com/nilaoda/BBDown/files/9277004/debug.log)

**Comment by shelken** [comment]
![image](https://user-images.githubusercontent.com/33972006/184343489-ca7f349d-2f6d-460f-841d-724fdfb8af03.png)
找到问题了，有的视频没有ugc这个字段

**Comment by shelken** [comment]
知道原因了：收藏里有些是audio。
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/33972006/184387041-1ac11bc7-8f22-40c3-90de-366a0253c5b2.png">

**Comment by nilaoda** [comment]
嗯 后续我修一下
