### ISSUE TITLE
macos上怎样安装

### ISSUE THREAD

**Issue by MostlyHarmlessxyz** [nilaoda/BBDown#421]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Action 
 6ff0554

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
macOS13.0
#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
无法安装
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by xhlove** [comment]
> 一款**命令行**式哔哩哔哩下载器. Bilibili Downloader.

**Comment by nilaoda** [comment]
https://github.com/nilaoda/BBDown/discussions/149
