### ISSUE TITLE
-intl 无法下载 

### ISSUE THREAD

**Issue by ltsj** [nilaoda/BBDown#422]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。BBDown version 1.5.3, Bilibili Downloader. Release版本

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。Win/Linux 都有试过

#### 3. 你使用的完整命令是什么？
```
BBDown -intl https://www.bilibili.tv/en/play/1048837 --debug
```
#### 4. 遇到了什么问题？
xxx 无法下载 不确定流程是否有问题 仅看到-intl的命令 未看到其他关于 国际版的说明 我是直接下载的 网络环境正常

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。
![image](https://user-images.githubusercontent.com/30733960/185954139-09e67ab6-5afd-41d5-996a-7b735d7e907c.png)
![image](https://user-images.githubusercontent.com/30733960/185953830-65a90cf5-3a8c-4b2d-88bf-2f757cc74b42.png)
中间太长截图放不下 只截图了开头和结尾

**Comment by nilaoda** [comment]
属已知BUG，等有空修复

**Comment by nilaoda** [comment]
已修正
