### ISSUE TITLE
字幕问题

### ISSUE THREAD

**Issue by MyGoodbye** [nilaoda/BBDown#426]
你好，请问对于外挂字幕视频我下载字幕的时候它默认是下载英文字幕，我如何选择下载其它语种的字幕呢？

**Comment by nilaoda** [comment]
理论上字幕是全部下载的，你说的默认下载英文字幕是哪个视频？

**Comment by nilaoda** [comment]
我可能知道了 是subonly存在一些问题，目前已经修复。可以下载最新版本：
https://nightly.link/nilaoda/BBDown/workflows/build_latest/master
