### ISSUE TITLE
mp4box找不到bin文件

### ISSUE THREAD

**Issue by FanruiC** [nilaoda/BBDown#435]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
1.5.3 Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Linux ubuntu 22.04

#### 3. 你使用的完整命令是什么？
```
BBDown --use-mp4box <url>
```
#### 4. 遇到了什么问题？
问题：找不到mp4box的bin文件。遇到bug过程：有些视频默认使用ffmpeg合并音视频卡住不动，所以改用--use-mp4box。提示找不到bin文件，查看/usr/bin发现安装最新版的mp4box后，其bin文件名为MP4Box。将MP4Box改为mp4box后，bbdown即可正常运行。

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by PaTTeeL** [comment]
今天用了一下，优化mp4box寻找机制貌似依然有点小问题？
BBDown version 1.5.8, Bilibili Downloader.
运行环境：Ubuntu 22.04.1 LTS @ WSL2
Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

运行
`./BBDown -tv --use-mp4box -token mytoken --encoding-priority av1 -mt -dd --work-dir /mnt/d/DOWNLOAD/ -ia -p 1 "BVnumber"` 报错`ErrorStartingProcess, mp4box, /mnt/d/DOWNLOAD, No such file or directory`

测试了一下mp4box
```
ubuntu:~$ which MP4Box
/usr/bin/MP4Box
```
改为运行
`./BBDown -tv --use-mp4box -token mytoken --encoding-priority av1 -mt -dd --work-dir /mnt/d/DOWNLOAD/ -ia -p 1 "BVnumber" --mp4box-path $(which MP4Box)`
成功！
