### ISSUE TITLE
使用 scoop 安装

### ISSUE THREAD

**Issue by canvascat** [nilaoda/BBDown#438]
感觉 Windows 下 [scoop](https://github.com/ScoopInstaller/Scoop) 安装 app 太丝滑了。
比如安装 ffmpeg, `scoop install ffmpeg`，支持自定义 Bucket，来安装 BBDown。
这是我刚做的一个尝试：https://github.com/canvascat/scoop-bucket

**Comment by Goojoe** [comment]
不错不错,支持一下

**Comment by LinHier** [comment]
不知道scoop官方的extra bucket的准入门槛是什么，能加到这个里面就更方便了，省得还得维护自定bucket

**Comment by bryarrow** [comment]
刚刚自己做了一个scoop bucket就看到这个issue🤣这个issue还有人理吗，我也希望能用scoop安装
（自己的bucket：https://github.com/bryarrow/scoopBBdown）

**Comment by liuxsdev** [comment]
已提交至 Scoop Main Bucket:  https://github.com/ScoopInstaller/Main/pull/4924
现在可以使用`scoop install bbdown` 安装了 😁

**Comment by nilaoda** [comment]
> 已提交至 Scoop Main Bucket: [ScoopInstaller/Main#4924](https://github.com/ScoopInstaller/Main/pull/4924) 现在可以使用`scoop install bbdown` 安装了 😁

非常感谢你的贡献。现在你可以编辑 Readme，将 Scoop 安装/升级命令附上后提交 PR。

**Comment by liuxsdev** [comment]
> > 已提交至 Scoop Main Bucket: [ScoopInstaller/Main#4924](https://github.com/ScoopInstaller/Main/pull/4924) 现在可以使用`scoop install bbdown` 安装了 😁
> 
> 兄弟， Scoop Main Bucket 里面的BBDown总是小一个版本号更新不及时，这要怎么解决？

Main 里面是最新的1.6.1 啊  https://github.com/ScoopInstaller/Main/blob/master/bucket/bbdown.json

**Comment by liuxsdev** [comment]
@pein0saga 

另一个仓库里有同名的软件，你得指定一下仓库的名字
`scoop install main/bbdown` 或者 `scoop update main/bbdown`
