### ISSUE TITLE
多P下载问题

### ISSUE THREAD

**Issue by stoplove** [nilaoda/BBDown#44]
![图片](https://user-images.githubusercontent.com/47299503/96396686-53c75280-11fa-11eb-8d74-aa4c646d78bf.png)

**Comment by stoplove** [comment]
> 
> 
> ![图片](https://user-images.githubusercontent.com/47299503/96396686-53c75280-11fa-11eb-8d74-aa4c646d78bf.png)

无法继续下载

**Comment by nilaoda** [comment]
你直接用-p选择分p范围试试呢。分p太多可能被B站限制了
