### ISSUE TITLE
linux中 发出的ffmpeg和mp4box命令在特殊title下存在转义问题

### ISSUE THREAD

**Issue by nlfiasel** [nilaoda/BBDown#445]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
1.5.3和Actions版本都试过

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Linux

#### 3. 你使用的完整命令是什么？
```
BBDown --debug BV164411E7Bi
```
#### 4. 遇到了什么问题？
在最后音视频合并步骤

` [2022-10-10 14:16:59.449] - ffmpeg命令：-loglevel warning -y  -i "52428970/52428970.P1.91756752.mp4"  -i "52428970/52428970.P1.91756752.m4a"  -i "52428970/52428970.jpg"  -map 0  -map 1  -map 2  -disposition:v:1 attached_pic  -metadata title="萌龙循环\(//∇//)\" -metadata description="麻吉哑巴库内|ω・）" -metadata artist="賢者佐倉めぐみ" -c copy  -c:s mov_text -movflags faststart -strict unofficial -strict -2 -f mp4 "萌龙循环.(..∇..).mp4"`

其中 `metadata title="萌龙循环\(//∇//)\"` 中最后的 `\` 会将 `"` 转义 导致命令出错
所以发出的命令中，正确的应该是 `metadata title="萌龙循环\(//∇//)\\"`
（ `"` 前的 `\` 应该提前被修改为 `\\` ）

这个问题在mp4box上经过测试是一样存在的(最新的Action版本。。。因为1.5.3使用--use-mp4box无法找到程序)

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by nilaoda** [comment]
最新Action版本应该已解决
