### ISSUE TITLE
能否支持 '解除b站区域限制' 的代理服务器

### ISSUE THREAD

**Issue by My-Responsitories** [nilaoda/BBDown#446]
能否支持 [解除b站区域限制](https://greasyfork.org/zh-CN/scripts/25718) 的代理服务器?

**Comment by nilaoda** [comment]
目前没计划，需要的话可以fork本项目，然后手动修改这里提交后，即可以在Actions中自动构建新版本
https://github.com/nilaoda/BBDown/blob/a77623995082488f1e16745b8c0e46cd9f75b372/BBDown.Core/Parser.cs#L26-L27

**Comment by dogdie233** [comment]
readme不是说不会支持吗（）
