### ISSUE TITLE
部分视频无法重命名 Some videos cannot be renamed

### ISSUE THREAD

**Issue by LittleArray** [nilaoda/BBDown#447]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
BBDown version 1.5.3 Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win10 21H2

#### 3. 你使用的完整命令是什么？
```
BBdown -app -dd -p 1 -F "Paris In The Rain1 (BV1gT4y1Y7bQ)" --work-dir "D:\download" BV1gT4y1Y7bQ
```
#### 4. 遇到了什么问题？
无法为文件重命名，仅保存在工作目录下以视频标题存在的文件夹中

#### 5. 运行截图（最好开启`-debug`；注意自行将Cookie/Token等敏感信息隐藏）
![Snipaste_2022-10-13_16-03-40](https://user-images.githubusercontent.com/88972417/195538228-adbea13a-97fe-488d-bf9e-3afa59a6893f.png)

**Comment by nilaoda** [comment]
多P请使用`-M` 不是`-F`

**Comment by LittleArray** [comment]
谢谢hxd
