### ISSUE TITLE
建议增加个人空间频道的视频下载

### ISSUE THREAD

**Issue by bestlake** [nilaoda/BBDown#45]
https://space.bilibili.com/326749661/channel/detail?cid=61588

**Comment by bestlake** [comment]
大佬，这个需求推进一下呗

**Comment by nilaoda** [comment]
> 大佬，这个需求推进一下呗

会的

**Comment by JDZW2018** [comment]
大佬，这个推进的怎么样了

**Comment by nilaoda** [comment]
> 大佬，这个推进的怎么样了

不是已经有了么
