### ISSUE TITLE
.NET兼容问题

### ISSUE THREAD

**Issue by DreamFerry** [nilaoda/BBDown#452]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
1.5.4 Release版本

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows11 22H2

#### 3. 你使用的完整命令是什么？
dotnet tool install --global BBDown

#### 4. 遇到了什么问题？
无法使用dotnet tool安装BBDown

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
<img width="842" alt="Snipaste_2022-10-20_16-11-47" src="https://user-images.githubusercontent.com/41297263/196893625-580efc31-1a64-4218-a470-2e8afa1f8626.png">

安装.NET 7以后才能成功安装，但.NET 7还处在RC阶段，使用率还很少，希望解决在低版本.NET下的兼容问题

**Comment by nilaoda** [comment]
可以使用 [Release](https://github.com/nilaoda/BBDown/releases) 版本。目前没有精力维护多个不同的运行时。
