### ISSUE TITLE
"code":10003003,"message":"该地区无法访问","ttl":1

### ISSUE THREAD

**Issue by 321yida** [nilaoda/BBDown#467]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
BBDown_1.5.4_20221019_win-x64(Release版本)
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win11 21H2
#### 3. 你使用的完整命令是什么？
BBDown.exe -intl "https://www.bilibili.com/video/BV1EG4y187sW/"
#### 4. 遇到了什么问题？
解析此分P失败(使用--debug查看详细信息)
![image](https://user-images.githubusercontent.com/67246596/200332861-a5058055-5011-4fed-8e2f-1e558b672c8a.png)
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
报错如下
![image](https://user-images.githubusercontent.com/67246596/200333096-d23ce197-fd22-4cc9-b95a-2905aa68b93d.png)

**Comment by duzhaokun123** [comment]
挂代理了吗 哪国的

**Comment by 321yida** [comment]
> 

没有挂代理，其他接口都能下载，只有国际版接口不行

**Comment by duzhaokun123** [comment]
那不很合理
