### ISSUE TITLE
下载完之后封面图片不见了

### ISSUE THREAD

**Issue by 315xiaoyao** [nilaoda/BBDown#469]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
BBDown_1.5.4_20221019_win-x64 Release版本

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
BBDown.exe https://www.bilibili.com/video/BV12W4y1x7JN/?spm_id_from=333.1007.tianma.9-1-37.click&vd_source=294f5980ea75870efddcb2c3889a539a
```
```
我在本地使用了配置文件如下：BBDown.config
#本文件是BBDown程序的配置文件
#以#开头的都会被程序忽略
#然后剩余非空白内容程序逐行读取，对于一个选项，其参数应当在下一行出现

#例如下面将设置输出文件名格式
--file-pattern
<videoTitle>[<dfn>]-<ownerName>

#下面设置下载多个分P时，每个分P的下载间隔为2秒
--delay-per-page
2
--ffmpeg-path
C:\Users\ricky\Desktop\视频素材\tool\ffmpeg-master-latest-win64-gpl\bin\ffmpeg.exe

--dfn-priority 
"8K 超高清, 超清 4K, 1080P 高码率, 高清 720P, HDR 真彩, 杜比视界"

# 下载模式，使用TV去掉水印
-tv
#配置下载视频保存的目录
#--work-dir
#"C:\Users\ricky\Desktop\"
```

#### 4. 遇到了什么问题？
下载完整个视频之后封面图片和文字不见了，主要是封面图片不见了。（在没有下载完成之前它是有下载的，后面好像是合并完成就删除掉了）

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://user-images.githubusercontent.com/33082140/200625635-e584e3f5-503d-4a16-a8b7-6cc28cb139e7.png)

![image](https://user-images.githubusercontent.com/33082140/200625519-d98ad089-6c56-4cac-9f52-0923723eb6ca.png)

**Comment by nilaoda** [comment]
软件就是这样设计的 合并后会将临时文件删除

**Comment by nilaoda** [comment]
暂时没有只获取封面封面的功能。要么没合并之前就把封面存下来，要么自行从mp4中提取封面。

**Comment by 315xiaoyao** [comment]
> 暂时没有只获取封面封面的功能。要么没合并之前就把封面存下来，要么自行从mp4中提取封面。

好的谢谢！希望后期把这个功能也加上。

**Comment by retsyo** [comment]
正想问这个问题呢。反正最初都下载了，能否增加选项，按视频文件命名方式，保留下载的封面图？
