### ISSUE TITLE
去除不了水印啊

### ISSUE THREAD

**Issue by zongbao98** [nilaoda/BBDown#473]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
BBDown -tv https://www.bilibili.com/video/BV1XP411j7Lr/?spm_id_from=333.999.0.0

#### 4. 遇到了什么问题？
下载了 水印还是在 其他视频也是一样

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）

这是截图
![image](https://user-images.githubusercontent.com/83392495/202088867-edb73e5d-6271-437a-b136-962340f63dfd.png)

这是文件
![image](https://user-images.githubusercontent.com/83392495/202088905-5df0b390-55d1-4a69-b69e-37882d16f25a.png)

**Comment by duzhaokun123** [comment]
有人说一定能去水印吗

**Comment by fredfcxxx** [comment]
试试用tv的api

**Comment by Jun-Y1** [comment]
我之前在5月份用1.5.3版本的时候还能去除水印，今天新旧版本都尝试发现去除不了了，即使下载之前去除水印成功过的视频现在也有水印了，由此可以推测b站更新水印的覆盖方式了。
