### ISSUE TITLE
设置工作目录无效

### ISSUE THREAD

**Issue by Neihan2020** [nilaoda/BBDown#476]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
v1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows 11 

#### 3. 你使用的完整命令是什么？
```
BBDown --work-dir <--work-dir>
```
#### 4. 遇到了什么问题？
设置工作目录无效

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://user-images.githubusercontent.com/84032101/202851218-46ac1980-cf29-4380-b5b6-bb51a9b8b2be.png)

![image](https://user-images.githubusercontent.com/84032101/202851234-e4ac458f-b0b7-4e7e-bf69-361a24775f14.png)

**Comment by Neihan2020** [comment]
请问是只能在拉去视频的时候后面跟--work-dir么

**Comment by nilaoda** [comment]
URL是必输项

**Comment by Neihan2020** [comment]
> 网址是必输项

好吧,我以为是那种开头设置一下,后续全部都会往那个路径存储的

**Comment by Neihan2020** [comment]
> 网址是必输项

不过还是谢谢,程序很棒

**Comment by nilaoda** [comment]
可以在exe目录下新建`BBDown.config`文件，里面写你的参数，例如：
```
--work-dir
E:\BBDown
```

**Comment by BenjaminYHQ** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/17381446/218771784-e63149db-7517-4234-9579-0ec22c78d631.png">
<img width="198" alt="image" src="https://user-images.githubusercontent.com/17381446/218771878-e7caad86-0361-4cbf-b573-85860890e0bf.png">
命令行可以指定下载地址。config文件无效，是哪里设置错误了吗？
