### ISSUE TITLE
推荐发布渠道加上 dotnet tool 方式

### ISSUE THREAD

**Issue by lindexi** [nilaoda/BBDown#48]
感谢大佬的这个工具，非常好用！

我推荐额外添加 dotnet tool 的方式发布

看起来可以使用 dotnet tool 方式进行发布，对我来说可以方便集成到我的工具库里面

本质上的 dotnet tool 是通过 NuGet 进行管理的，在版本管理上非常清真

更改使用 dotnet tool 的方法也十分简单，请看 [教程：创建 .NET Core 工具 - .NET Core CLI | Microsoft Docs](https://docs.microsoft.com/zh-cn/dotnet/core/tools/global-tools-how-to-create )

**Comment by nilaoda** [comment]
感谢大佬支持！我有空试试看~

**Comment by nilaoda** [comment]
大佬，我的发布似乎不太正确。。Dependencies为什么什么都没有呢
https://www.nuget.org/packages/BBDown/

**Comment by lindexi** [comment]
@nilaoda 因为打出来就是 Tool 了，里面自动包含了所有引用了，因此就不需要声明依赖项

我开始使用了，好评。多谢大佬

![图片](https://user-images.githubusercontent.com/16054566/99609579-295ff380-2a4b-11eb-81ff-b0d04f714da4.png)

**Comment by nilaoda** [comment]
原来如此
