### ISSUE TITLE
怎么在执行合并的时候 执行ffmpeg额外转换参数

### ISSUE THREAD

**Issue by gdf159159** [nilaoda/BBDown#481]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。Release1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。Win10

#### 3. 你使用的完整命令是什么？
```
BBDown ... BV1jv4y1D7iG -tv  --encoding-priority "hevc,av1,avc" -p 1
```
#### 4. 遇到了什么问题？
xxx  b站下载的hevc默认编码打包方式是hev1是  ios不能播放 需要转一下变成hvc1

ffmpeg -i a.mp4 -c:v copy -tag:v hvc1 -c:a copy "b.mp4"
怎么在执行合并的时候 自动执行以上转换呢?

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by nilaoda** [comment]
目前不支持，后续版本可能会增加相关选项。

related: https://github.com/nilaoda/BBDown/discussions/425

**Comment by gaoshilei** [comment]
下载好之后用ffmpeg手动转一下吧，或者写个脚本自动转
