### ISSUE TITLE
下载付费课程（已付费）时部分可下载，但后边的视频出现The response ended prematurely, with at least 11366389 additional bytes expected.

### ISSUE THREAD

**Issue by mumuxi-git** [nilaoda/BBDown#484]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
BBDown version 1.4.8 Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
bbdown "https://www.bilibili.com/cheese/play/ep19905?csource=common_hp_history_null&t=3&spm_id_from=333.1007.top_right_bar_window_history.content.click"
```
#### 4. 遇到了什么问题？
下载付费课程（已付费并扫描二维码登录）时部分可下载，但后边的视频出现The response ended prematurely, with at least 11366389 additional bytes expected.

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://user-images.githubusercontent.com/92151426/205444100-0a3c2415-3e34-4ad9-999a-6e7f188c4b1b.png)

**Comment by mumuxi-git** [comment]
然后试了下别的下载器，使用DownKyi_1.3.8下载成功，不知道这个问题出现在哪里。主要是很喜欢bbdown这款命令行下载器，很简洁实用，还请大佬看看问题在哪里。

**Comment by nilaoda** [comment]
目前尚无法定位此位置，可以尝试切换到aria2下载试试 准备[aria2c.exe](https://github.com/nilaoda/BBDown/tree/master/Binary)并开启`--use-aria2c`。

**Comment by mumuxi-git** [comment]
> 目前尚无法定位此位置，可以尝试切换到aria2下载试试 准备[aria2c.exe](https://github.com/nilaoda/BBDown/tree/master/Binary)并开启`--use-aria2c`。

更新至最新版，再次尝试下载，问题解决，谢谢。
