### ISSUE TITLE
ni大佬，请教下最后合并的具体命令是啥呀

### ISSUE THREAD

**Issue by wub1n** [nilaoda/BBDown#485]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
windows 10 x64

#### 3. 你使用的完整命令是什么？
```
BBDown -tv --skip-ai "https://www.bilibili.com/video/BV1te4y1p7Gv/"
```
#### 4. 遇到了什么问题？
大佬，想请教下最后合并的具体命令是啥，我下载油管的4K，想用ffmpeg命令一次性封装音视频、字幕、章节、封面，此前用了众多下载器，只有bbdown可以做到封装这么多的条目，可是苦于不知道具体命令，网上找的都需要好几个步骤，所以特来请教，希望大佬能解惑。

**Comment by wub1n** [comment]
主要还想封装成mp4格式，如果MKV的话那就简单了。

**Comment by nilaoda** [comment]
启用`--debug`时，会打印出来程序使用的命令。

**Comment by wub1n** [comment]
> 启用`--debug`时，会打印出来程序使用的命令。

是我小白了 谢谢大佬 真心感谢！！！
