### ISSUE TITLE
如何在 cmd命令行中使用 --multi-file-pattern 选项？

### ISSUE THREAD

**Issue by adangran** [nilaoda/BBDown#487]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release 1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win 10

#### 3. 你使用的完整命令是什么？
```
BBDown.exe -tv   -dd --skip-subtitle --multi-file-pattern "<ownerName>：<videoTitle>/[P <pageNumberWithZero>]<pageTitle>[<dfn>]" --work-dir C:\Downloads --ffmpeg-path C:\Users\L\AppData\Local\ffmpeg\bin\ffmpeg.exe --delay-per-page 30 --debug https://b23.tv/VkVvrFv
```
#### 4. 遇到了什么问题？
我尝试在cmd命令行中使用 --multi-file-pattern <ownerName>：<videoTitle>/[P<pageNumberWithZero>]<pageTitle>[<dfn>] 自定义下载文件的文件名，但并不起作用，下载后的文件依然是默认的文件名。
--debug 看了下，应该是小于号、大于号被转义成 \u003C \u003E 了。
是我的转义写错了吗？正确的命令应该怎么写？

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://user-images.githubusercontent.com/39615236/206723751-04c79d33-5219-4799-acad-54225e73d82a.png)

**Comment by duzhaokun123** [comment]
因为 https://b23.tv/VkVvrFv 不是多p视频

**Comment by adangran** [comment]
@duzhaokun123 不是多p不多p的问题，你看下debug， 小于号、大于号被转义了。我试了下，如果写到配置文件就可以成功，但我想在命令行使用。

**Comment by adangran** [comment]
@duzhaokun123 跪~，确实是我错了。。。谢谢指正
