### ISSUE TITLE
作者有计划更新批量下载吗，现在虽然会生成一个txt，但属实不知道怎么写一个bat来调用

### ISSUE THREAD

**Issue by yibingchaoyue** [nilaoda/BBDown#494]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
xxx

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by nilaoda** [comment]
```bat
@echo off
for /f "delims=" %%i in (test.txt) do (
    BBDown "%%i"
)
```

**Comment by hibiki222** [comment]
> ```batchfile
> @echo off
> for /f "delims=" %%i in (test.txt) do (
>     BBDown "%%i"
> )
> ```

3个月了才看到回复  我已经创建了这个bat  可如何使用呢
BVxxxx
BVyyyy
比如下两个视频 该如何操作
