### ISSUE TITLE
下载弹幕的问题

### ISSUE THREAD

**Issue by qingchunnh** [nilaoda/BBDown#498]
版本1.5.4
操作系统win10
完整命令 用的是GUI生成的
ep234488  --ffmpeg-path "G:\BBDown\ffmpeg.exe"  -dd  --force-http  --work-dir "G:\BBDown\Download"
下载的弹幕不完整，我下好的弹幕文件发现少了特别多弹幕，ass的文件大小是316kb，我拿浏览器插件下载的弹幕文件大小是5.64mb
浏览器插件下载的弹幕没有缺任何一条弹幕，但是用BBDown下载的弹幕就缺了特别多，这是怎么回事呢

**Comment by duzhaokun123** [comment]
因为 bbdown 直接用的解析结果里标的那个弹幕 应该是`http://comment.bilibili.com/{cid}.xml`

而没有用正经的弹幕接口

**Comment by qingchunnh** [comment]
> 因为 bbdown 直接用的~解析结果里标的那个弹幕~(web 接口应该没有这个字段) 应该是`http://comment.bilibili.com/{cid}.xml`
> 
> 而没有用正经的弹幕接口
> 
> 下载完整弹幕要翻历史弹幕的 完全没有做

感谢解答
