### ISSUE TITLE
tv接口失效了？

### ISSUE THREAD

**Issue by aliofwind** [nilaoda/BBDown#5]
多个视频都是返回：
`Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index`

**Comment by nilaoda** [comment]
TV接口现在要会员了 而且成了FLV

**Comment by lipinghao1986** [comment]
> TV接口现在要会员了 而且成了FLV

鸟大，如果开通了TV会员，添加网页端的Cookies是否可以解析无水印？还是得添加TV端的cookies？

**Comment by nilaoda** [comment]
> > TV接口现在要会员了 而且成了FLV
> 
> 鸟大，如果开通了TV会员，添加网页端的Cookies是否可以解析无水印？还是得添加TV端的cookies？

必须TV的会员。使用`BBDown logintv`来登录
