### ISSUE TITLE
无法去除水印

### ISSUE THREAD

**Issue by knaxLFea** [nilaoda/BBDown#501]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。
win
#### 3. 你使用的完整命令是什么？
```
BBDown ...
```.\BBDOWN https://www.bilibili.com/video/BV1D14y1E7nR -TV
#### 4. 遇到了什么问题？
xxx
最近下载的所有视频都无法去水印，而之前可以
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by nilaoda** [comment]
1. `-tv`
2. https://github.com/nilaoda/BBDown/issues/473
