### ISSUE TITLE
如何在--file-pattern中添加 bv号

### ISSUE THREAD

**Issue by suckerSlayer** [nilaoda/BBDown#506]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
 BBDown_1.5.4_20221019_win-x64 Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win
#### 3. 你使用的完整命令是什么？
```
BBDown -mt -F "<videoTitle>[<ownerName>][<dfn>][<bid>][<aid>]"
```
#### 4. 遇到了什么问题？
如何在--file-pattern中添加 bv号

**Comment by nilaoda** [comment]
目前不支持

**Comment by La-Hire** [comment]
> 目前不支持

直接从url里截取呢
