### ISSUE TITLE
最近B站的SESSDATA每天不重样，离谱啊

### ISSUE THREAD

**Issue by antatura** [nilaoda/BBDown#507]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows 11 21H2

#### 3. 你使用的完整命令是什么？
```
BBDown.exe -c "SESSDATA=???????????????" -ia BV......
```
#### 4. 遇到了什么问题？
B站的SESSDATA老是会变动，每次都要重新复制。

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by HashLiver** [comment]
因为B站网页版每天会刷新cookies，你从浏览器复制下SESSDATA后，立即清除浏览器cookies。

这样你复制下来的SESSDATA半年内不会过期。

**Comment by antatura** [comment]
> 

好！感谢！

**Comment by antatura** [comment]
> 

好！感谢！

**Comment by mo-han** [comment]
> 

请问一下，B站这个特性是一直这样的吗？我印象里以前没这现象，我是最近才遇到。
