### ISSUE TITLE
如何下载1080P以上画质？即使我登陆了

### ISSUE THREAD

**Issue by Guaishou233** [nilaoda/BBDown#509]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。BBDown 1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。Win

#### 3. 你使用的完整命令是什么？
```
BBDown ...-tv https://www.bilibili.com/video/BV1fK411Q7fK?p=1
```
#### 4. 遇到了什么问题？
我无法下载4k画质及时我登陆了，如何像演示中那样搜寻到4k画质呢？

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

![R`WSW{~G7}WK5AIX5092(GE](https://user-images.githubusercontent.com/94284422/210983434-5d0a3ffd-e798-4e4d-a94c-49f749998791.png)

![}}FCBAS%RO37GIH78C4S`FX](https://user-images.githubusercontent.com/94284422/210983469-17b013b6-7602-4ff9-8319-bcef8e0b748d.png)

**Comment by Guaishou233** [comment]
![ecd6e3c538b327b5f3ec5aab214e619](https://user-images.githubusercontent.com/94284422/211140858-75c4d186-8f77-4c5d-a670-dfb2ee99339e.png)
![9d2c56f20cf32c70031bfafb1943ba5](https://user-images.githubusercontent.com/94284422/211140870-1d38cb93-62c9-4cd2-bfa3-0405b227c04b.png)
我试过但是还是没有办法下载到4k

**Comment by nilaoda** [comment]
你需要TV小电视会员

![image](https://user-images.githubusercontent.com/20772925/211142050-b5f08e6c-4742-4cc5-a032-98aef6d82905.png)
