### ISSUE TITLE
下载进度会卡住

### ISSUE THREAD

**Issue by zhaotianff** [nilaoda/BBDown#51]
需要按回车才能恢复下载进度显示
![下载进度卡住](https://user-images.githubusercontent.com/22126367/99940084-7541ce00-2da6-11eb-9d58-dd7d664a159a.png)
如图中显示进度为1%，我再按下回车，已经下载到11%了

**Comment by zhaotianff** [comment]
只要点击 了其它空白区域就会这样。

**Comment by nilaoda** [comment]
所有cmd程序都会因选中字符而阻塞输出

**Comment by zhaotianff** [comment]
嗯，是的
