### ISSUE TITLE
小白求问如何批量下载？

### ISSUE THREAD

**Issue by MaxieJr** [nilaoda/BBDown#513]
是要自己将视频地址写进urls.txt吗？提示获取到了的全部投稿视频地址可以在哪导出呢

**Comment by ColdFox-H** [comment]
目前好像没有批量下载的功能，我找到了导出B站收藏夹的方法，然后根据这个写了导出订阅番剧的方法
`function get_list ()
{
    var result = "";
    $(".fav-video-list > li >a.title").each(function(){
        result += $(this).text() + '<br><a href="' + $(this).attr("href") + '" target=_blank >https:'+$(this).attr("href")+'</a><br>';
    });
    return result;
}
var html = "";
function main (){
    html += get_list();
    if($(".be-pager-next:visible").length == 0)
    {   
        document.write(html);
        return ;
    }else{
        $(".be-pager-next").click();
        setTimeout("main()",5000);
    }
}
main();`
来源于：https://www.cnblogs.com/toumingbai/p/11399238.html
自己写的：
`function get_list ()
{
    var result = "";
    $(".pgc-follow-list > li >a>h4.pgc-item-title").each(function(){
        result += '<a href="' + $(this).parent().attr("href") + '" target=_blank >https:'+$(this).parent().attr("href")+'</a><br>';
    });
    return result;
}
var html = "";
function main (){
    html += get_list();
    if($(".next-page:visible").length == 0)
    {   
        document.write(html);
        return ;
    }else{
        $(".next-page")[0].click();
        setTimeout("main()",5000);
    }
}
main();`
然后你可以通过python调用命令行命令来批量下载
`import os
os.popen(command)`
但是这种做法会导致同时开启非常多的线程，也就是每个链接都启动一个bbdown来下载。我目前没有找到比较好的方法来处理这个。比较理想的方法是一次最多开5个线程来下载，下载完一个再下接下来的。但是没找到实现方法。

**Comment by ChokWah** [comment]
@ColdFox-H 可以下载某个 up 主的所有视频吗？

**Comment by specked2527** [comment]
@ChokWah @ColdFox-H @MaxieJr  以下载某个 up 主的所有视频

`BBDown` `你要下载的UP个人空间的投稿视频地址`
提示获取到了的全部投稿视频地址在软件目录的 XXX.txt 把他改成 urls.txt
新建文本.txt 填写代码保存 改成 xxx.bat 运行

```powershell
@echo Off
For /F %%a in (urls.txt) Do (BBDown.exe "%%a")
pause
```

**Comment by specked2527** [comment]
@ChokWah @ColdFox-H @MaxieJr  以下载某个 up 主的所有视频

`BBDown` `你要下载的UP个人空间的投稿视频地址`
提示获取到了的全部投稿视频地址在软件目录的 XXX.txt 把他改成 urls.txt
新建文本.txt 填写代码保存 改成 xxx.bat 运行

```powershell
@echo Off
For /F %%a in (urls.txt) Do (BBDown.exe "%%a")
pause
```

**Comment by specked2527** [comment]
@ChokWah @ColdFox-H @MaxieJr  以下载某个 up 主的所有视频

`BBDown` `你要下载的UP个人空间的投稿视频地址`
提示获取到了的全部投稿视频地址在软件目录的 XXX.txt 把他改成 urls.txt
新建文本.txt 填写代码保存 改成 xxx.bat 运行

```powershell
@echo Off
For /F %%a in (urls.txt) Do (BBDown.exe "%%a")
pause
```
