### ISSUE TITLE
mac m1max用不了BBDown，显示zsh: command not found: bbdown

### ISSUE THREAD

**Issue by tammy323** [nilaoda/BBDown#515]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
dotnet tool install --global BBDown 下载的，不知道什么版本

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
mac

#### 3. 你使用的完整命令是什么？
```
BBDown https://www.bilibili.com/video/BV15z4y1Z734/?spm_id_from=333.337.search-card.all.click&vd_source=f3164ea8896e552ec4e245e6724f6eb8
```
#### 4. 遇到了什么问题？
zsh: command not found: bbdown
出现这个，不知道该怎么办，it小白。另一个帖子看到有个回复，但不知道怎么使用，谢谢。
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by tammy323** [comment]
刚刚再次运行BBDown https://www.bilibili.com/video/BV15z4y1Z734/?spm_id_from=333.337.search-card.all.click&vd_source=f3164ea8896e552ec4e245e6724f6eb8出现：[1] 90419
zsh: no matches found: https://www.bilibili.com/video/BV15z4y1Z734/?spm_id_from=333.337.search-card.all.click
kwokhin@guoxiandebijibendiannao ~ % 
[1]  + exit 1     bbdown 
kwokhin@guoxiandebijibendiannao ~ % bbdown https://www.bilibili.com/video/BV15z4y1Z734/?spm_id_from=333.337.search-card.all.click&vd_source=f3164ea8896e552ec4e245e6724f6eb8
[1] 90422
zsh: no matches found: https://www.bilibili.com/video/BV15z4y1Z734/?spm_id_from=333.337.search-card.all.click
[1]  + exit 1     bbdown 
kwokhin@guoxiandebijibendiannao ~ % bbdown https://www.bilibili.com/video/BV15z4y1Z734/?spm_id_from=333.337.search-card.all.click&vd_source=f3164ea8896e552ec4e245e6724f6eb8 
[1] 90432
zsh: no matches found: https://www.bilibili.com/video/BV15z4y1Z734/?spm_id_from=333.337.search-card.all.click
kwokhin@guoxiandebijibendiannao ~ % 
[1]  + exit 1     bbdown 
kwokhin@guoxiandebijibendiannao ~ %

**Comment by nilaoda** [comment]
到Release页面，下载二进制版本吧。需要`chmod +x ./BBDown`手动赋权限

**Comment by tammy323** [comment]
您是说下载[BBDown_1.5.4_20221019_osx-arm64.zip]，解压后怎么使用呢？添麻烦了，不好意思，谢谢。

**Comment by nilaoda** [comment]
> 您是说下载[BBDown_1.5.4_20221019_osx-arm64.zip]，解压后怎么使用呢？添麻烦了，不好意思，谢谢。

https://github.com/nilaoda/BBDown/discussions/149

**Comment by tammy323** [comment]
"解压后在 Finder 中右键打开一次，选择允许。卡在这个了

**Comment by tammy323** [comment]
“解压后在 Finder 中右键打开一次，选择允许。”卡在这一开始了，没有“允许”可以选择

**Comment by Xav1erwong** [comment]
> > 您是说下载[BBDown_1.5.4_20221019_osx-arm64.zip]，解压后怎么使用呢？添麻烦了，不好意思，谢谢。
> 
> #149
<img width="615" alt="截屏2023-01-28 下午7 09 13" src="https://user-images.githubusercontent.com/115802621/215263354-9055e3fb-0b06-465f-9c02-2a9c0163f7f9.png">

大佬怎么手动赋予权限是在终端输入吗 结果是
