### ISSUE TITLE
bbdown 可以设置默认下载目录吗？

### ISSUE THREAD

**Issue by billowssun** [nilaoda/BBDown#518]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。windows

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
bbdown 可以设置默认下载目录吗？每次都在用户文件夹里面，很难找到。

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。
![image](https://user-images.githubusercontent.com/55521033/213185824-684a9636-9b6f-43f5-95a6-c8e5582eec2b.png)

**Comment by nilaoda** [comment]
`--work-dir <work-dir>                          设置程序的工作目录`
