### ISSUE TITLE
文件名包含大于号小于号会被替换成英文点号，但是MacOS是允许文件名包含大于号小于号的，而且包含这会使文件变成隐藏文件。

### ISSUE THREAD

**Issue by dfvips** [nilaoda/BBDown#520]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
v1.5.4 Actions

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
MacOS 13

#### 3. 你使用的完整命令是什么？
BBDown --skip-cover --work-dir /Users/dreamfly/Downloads "https://www.bilibili.com/video/BV1as411i7GW?spm_id_from=333.880.my_history.page.click"
#### 4. 遇到了什么问题？
如 <烟袋斜街10号网络剧>正式版预告片花，文件名包含大于号小于号，会被替换成 . 号，而这样会导致在mac上面找不到文件，因为文件变成了隐藏文件。

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![4f135690f1d691fde740b03a5dd364eb](https://user-images.githubusercontent.com/21048630/213734827-4221cd4c-ea25-4c51-87f8-a1c57259ce21.png)
![307b15df1c47428fb3b54714bb56d7b2](https://user-images.githubusercontent.com/21048630/213734854-86ade973-a82f-42d6-8b16-c79e5c4080c6.png)
![40b65af02f4330427bd6801e1de3aecd](https://user-images.githubusercontent.com/21048630/213734887-32c60899-12a1-4fcf-a7b3-1cee3efa3060.png)
![b6f446a64eb966b6d5ac9899295a7882](https://user-images.githubusercontent.com/21048630/213734925-bef09d39-6bc7-4272-a754-5a823b8a5985.png)

**Comment by hez2010** [comment]
@nilaoda Consider replacing unsupported characters to `_` instead of `.`.
