### ISSUE TITLE
求问，如何自定义下载不同分辨率的视频文件？

### ISSUE THREAD

**Issue by jikongwudi** [nilaoda/BBDown#529]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
xxx

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by nilaoda** [comment]
有两种方式

* `--interactive` 手动选择
* `--dfn-priority` 设置画质优先级，如更偏爱1080P高码率， `--dfn-priority "1080P 高码率"`

**Comment by jikongwudi** [comment]
懂啦，谢谢解答
