### ISSUE TITLE
bbdown如何设置视频下载路径？跪谢各位大佬

### ISSUE THREAD

**Issue by laoziliyunlongshikaiyidalipaode** [nilaoda/BBDown#537]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
xxx

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by nilaoda** [comment]
设置工作目录

**Comment by XMB-7** [comment]
比如--work-dir D:\MyVideos
直接写进配置文件就好, 不用每次都手动键入.
