### ISSUE TITLE
在直接复制的链接中，添加的选项无法使用。

### ISSUE THREAD

**Issue by LaoShiSaMa** [nilaoda/BBDown#538]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release 1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows 11 x64

#### 3. 你使用的完整命令是什么？
bbdown https://www.bilibili.com/video/BV1GT411D72s/?spm_id_from=333.1007.tianma.2-1-3.click&vd_source=cdd5266bd7830ac0c78c70b0bac357c0 --skip-ai --work-dir download --ffmpeg-path tools/ffmpeg.exe --config-file tools/bbdown.config 

#### 4. 遇到了什么问题？
在直接复制的链接（例如:https://www.bilibili.com/video/BV1GT411D72s/?spm_id_from=333.1007.tianma.2-1-3.click&vd_source=cdd5266bd7830ac0c78c70b0bac357c0）中，添加的选项无法使用。
但简化版链接和直接输入BV可用
（懒.jpg）

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）：
**图片中只可知跳过AI选项失败，但实际下载目录也是错的**
**而且--debug也没用捏 :(**
![1](https://user-images.githubusercontent.com/118602053/221360946-ca95e601-0fdf-4de9-be2b-088cd1d16337.png)
![2](https://user-images.githubusercontent.com/118602053/221360950-f50f152d-0b7f-4d50-8c6e-0cc268de7142.png)
![3](https://user-images.githubusercontent.com/118602053/221360953-ea6dde8f-0753-48e8-ba73-8b9932785ed2.png)
![4](https://user-images.githubusercontent.com/118602053/221360955-0868c5e1-3c05-45ae-a978-24ec0f068bb6.png)

**Comment by nilaoda** [comment]
请使用英文引号`"`包裹你的 URL
