### ISSUE TITLE
下载完成后合并音视频和字幕时失败

### ISSUE THREAD

**Issue by claudeWest** [nilaoda/BBDown#539]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release 1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win

#### 3. 你使用的完整命令是什么？
```
BBDown -p 1 "https://www.bilibili.com/video/BV1Ev411W7Rn"
```
#### 4. 遇到了什么问题？
执行合并音视频和字幕时找不到指定的文件

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）

![Snipaste_2023-02-26_00-06-38](https://user-images.githubusercontent.com/119830043/221367219-17098da9-cf07-4dd3-ae87-b6947e4a7b01.png)

**Comment by nilaoda** [comment]
下载 [ffmpeg](http://ffmpeg.org/download.html#build-windows) 并将`ffmpeg.exe`放到程序目录下

**Comment by XMB-7** [comment]
> 下载 [ffmpeg](http://ffmpeg.org/download.html#build-windows) 并将ffmpeg.exe放到程序目录下

指定ffmpeg路径时, 像添加环境变量那样只指定目录F:\MyApps\FFmpeg\bin是识别不了的, 必须指定F:\MyApps\FFmpeg\bin\ffmpeg.exe才行. 或许可以优化一下,
