### ISSUE TITLE
突然报错了……

### ISSUE THREAD

**Issue by draftman9** [nilaoda/BBDown#546]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
release 1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win10

#### 3. 你使用的完整命令是什么？
```
BBDown.exe https://www.bilibili.com/video/BV1Wa411H7CR/
```
#### 4. 遇到了什么问题？

不能下载并报错。

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://user-images.githubusercontent.com/99490289/222961063-17aa6738-6fa6-4be2-b199-6b33b2f9805f.png)

**Comment by nilaoda** [comment]
昨天B站崩了
