### ISSUE TITLE
标题开头是‘-’的视频会合并失败

### ISSUE THREAD

**Issue by Lebensborn** [nilaoda/BBDown#548]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
1.5.4 Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows

#### 3. 你使用的完整命令是什么？
```
.\BBDown.exe av762058039 --debug
```
#### 4. 遇到了什么问题？
合并失败，只有2个视频如此，共同点为标题开头是‘-’，猜测将-识别为了参数的一部分

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://user-images.githubusercontent.com/44167242/223131893-4ba41211-82fa-4033-a9cf-19b5c8d07890.png)

**Comment by JoyLin0617** [comment]
啊，原來是這樣！！
我下載的也會合併失敗
我這下載的名稱是：-弟子入リ-DESHIIRI (全)
難怪呀
