### ISSUE TITLE
如何卸载

### ISSUE THREAD

**Issue by nihaohani** [nilaoda/BBDown#549]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
xxx

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by nilaoda** [comment]
如果你不是使用.NET Tool安装的，直接删除所有相关文件即可

如果是，请运行`dotnet tool uninstall --global BBDown`

**Comment by nihaohani** [comment]
> 如果你不是使用.NET工具安装的，直接删除所有相关文件即可
> 
> 如果是，请运行`dotnet tool uninstall --global BBDown`

成功了，非常感谢！
