### ISSUE TITLE
小白问下关于批量下载 这个bat如何使用呢

### ISSUE THREAD

**Issue by hibiki222** [nilaoda/BBDown#553]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。win

#### 3. 你使用的完整命令是什么？
```。。
BBDown ...
```
#### 4. 遇到了什么问题？
xxx。。

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。.。。

**Comment by hibiki222** [comment]
#494 这个bat创建好了 但看不懂 是要创建一个test.txt的文件吗

**Comment by nilaoda** [comment]
创建test.txt文件，里面每行都是一个链接

**Comment by hibiki222** [comment]
> 创建test.txt文件，里面每行都是一个链接
再请问一句
链接是单纯的bv号
还是      BBDown "https://www.bilibili.com/video/BV号"     这种命令的格式

**Comment by nilaoda** [comment]
@hibiki222 理论上都可以
