### ISSUE TITLE
是怎么获取到本地cookie的？

### ISSUE THREAD

**Issue by Tsumikia** [nilaoda/BBDown#558]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
xxx

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by nilaoda** [comment]
BBDown 并不具备直接获取用户存储在 Chrome 等浏览器中的 Cookie 的能力，你可以使用以下命令扫描二维码以登录你的账号：
```
BBDown login
```
登录成功后，再次执行你的下载命令即可。
