### ISSUE TITLE
[Suggestion] Consider adding new option "-web"

### ISSUE THREAD

**Issue by MasterInQuestion** [nilaoda/BBDown#571]
Simply for overriding back to the default web resolving interface.
    (to avoid awkward notations like &#x60;-tv false&#x60;)

**Comment by nilaoda** [comment]
Web is **default**. Unless you use `-tv` or `-app`.

**Comment by MasterInQuestion** [comment]
Yes, perfectly aware.
    Primarily intended for easier override.
