### ISSUE TITLE
如何只下载弹幕，不下载视频？

### ISSUE THREAD

**Issue by zhaige95** [nilaoda/BBDown#572]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
 release BBDown_1.5.4_20221019_win-x64

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
 win10

#### 3. 你使用的完整命令是什么？
 BBDown.exe https://www.bilibili.com/bangumi/play/ep744327?theme=movie&spm_id_from=333.337.0.0 -dd

**Comment by draftman9** [comment]
我这有一个非正规方法：你开`-dd`时，会先下弹幕，再下视频和音频。因此在下载视频时，`Ctrl-C`了它。就会只留下.xml文件了。
