### ISSUE TITLE
tv视频流地址获取方式是什么样的

### ISSUE THREAD

**Issue by ali13378510bu** [nilaoda/BBDown#573]
我想请问一下，tv视频流地址获取方式是什么样的，我找了该项目鸣谢的b站接口项目，但是没能找到tv端视频流的获取方式，只找到了web端的，能不能指点一下，或者提供下tv端的视频流地址获取方式

**Comment by ali13378510bu** [comment]
我想请问一下，tv视频流地址获取方式是什么样的，我找了该项目鸣谢的b站接口项目，但是没能找到tv端视频流的获取方式，只找到了web端的，能不能指点一下，或者提供下tv端的视频流地址获取方式

**Comment by nilaoda** [comment]
看这里：https://github.com/nilaoda/BBDown/blob/master/BBDown.Core/Parser.cs
