### ISSUE TITLE
视频流大小显示错误

### ISSUE THREAD

**Issue by Unbiseptium** [nilaoda/BBDown#575]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）

Actions

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）

Win

#### 3. 你使用的完整命令是什么？

 BBDown BV1A54y1F7v6 -ia --skip-mux --debug

#### 4. 遇到了什么问题？

视频流大小显示错误，选择流时显示30.49 GB，实际为7.68GB

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://user-images.githubusercontent.com/61733874/233310584-f346d170-9d1e-4ff3-982f-4895a42f82cc.png)

**Comment by nilaoda** [comment]
目前文件大小显示是从接口里取bandwidth*时长计算得到的 应该改成优先取用size字段，size没有再自行计算。
