### ISSUE TITLE
ErrorStartingProcess, ffmpeg, F:\BBDown1.5.4, 系统找不到指定的文件。

### ISSUE THREAD

**Issue by oooomoooo** [nilaoda/BBDown#577]
![1682350989379](https://user-images.githubusercontent.com/92239221/234047740-3b33bede-19b5-4dc2-96ab-433af558a8da.png)
ErrorStartingProcess, ffmpeg, F:\BBDown1.5.4, 系统找不到指定的文件。请给我说下怎么弄啊

**Comment by oooomoooo** [comment]
已经解决，需要可以找我解决这个问题了

**Comment by sdkaert** [comment]
> 已经解决，需要可以找我解决这个问题了

如何解决的？

**Comment by YuHan-He** [comment]
> 已经解决，需要可以找我解决这个问题了

同问，如何解决？

**Comment by nilaoda** [comment]
@YuHan-He 下载ffmpeg
