### ISSUE TITLE
无法个人空间解析

### ISSUE THREAD

**Issue by denjhang** [nilaoda/BBDown#579]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
BBDown v1.5.4 Release版本
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win10

#### 3. 你使用的完整命令是什么？
bbdown https://space.bilibili.com/623253809/video
#### 4. 遇到了什么问题？
无法个人空间解析
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）

![截图未命名0501202239](https://user-images.githubusercontent.com/61811583/235451247-9962f470-23b0-4df5-a9fe-b4bd180c6c8d.jpeg)

**Comment by jikongwudi** [comment]
解决了吗，我也是这种错误

**Comment by realaz23** [comment]
同样的问题

**Comment by nilaoda** [comment]
#588
