### ISSUE TITLE
跳过混流将导致封面音频视频无法按照指定的配置进行命名

### ISSUE THREAD

**Issue by XMB-7** [nilaoda/BBDown#586]
假如预设的命名为xxx, 目前是没用--skip-mux时, 下载的视频会被正确命名为xxx, 但如果用了--skip-mux, 封面音频视频就都不会被正确命名为xxx.
(另外是不是笔误了, 是mix非mux吧)

![image](https://user-images.githubusercontent.com/65625632/236524374-c1705ba4-e12f-41d2-9252-a5f1d0b4a816.png)

重命名配置如下
```
--file-pattern
<ownerName>/<pageNumberWithZero>_<videoTitle>
--multi-file-pattern
<ownerName>/<videoTitle>/<pageNumberWithZero>_<pageTitle>
```

**Comment by nilaoda** [comment]
这两个选项就是给混流后输出的文件使用的，如果跳过混流这两个选项不具备现实意义。

**Comment by XMB-7** [comment]
> 这两个选项就是给混流后输出的文件使用的，如果跳过混流这两个选项不具备现实意义。

我这边有一个应用场景: 我需要把b站视频音视频分离下载=, 然后只把音频上传到飞书妙记服务器(直接上传视频, 空间不够用), 所以需要音视频乃至封面弹幕字幕都能按照预设进行重命名.
