### ISSUE TITLE
想批量下载，导出txt文件时报错，烦请帮忙看下

### ISSUE THREAD

**Issue by songzichao** [nilaoda/BBDown#588]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
1.5.4
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
linux

#### 3. 你使用的完整命令是什么？
```
./BBDown -p ALL "https://b23.tv/1sHcavH"
```
#### 4. 遇到了什么问题？
ExpectedEndAfterSingleJson, { LineNumber: 0 | BytePositionInLine: 70.

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
 
![QQ截图20230506172117](https://user-images.githubusercontent.com/31985874/236615761-973033a4-8462-4842-9069-2a9530b0bb78.jpg)

![QQ截图20230506172900](https://user-images.githubusercontent.com/31985874/236615856-59006215-e738-4eda-86f2-e9555e2807f8.jpg)

**Comment by Lebensborn** [comment]
同经常遇到

**Comment by listra1** [comment]
最近似乎都是这样的，不知道哪里出问题了

**Comment by linchuanXu** [comment]
同样的问题，希望修复

**Comment by Linux2010** [comment]
下载个人空间，好像又不好用了，v1.6.1
