### ISSUE TITLE
BBDown.config配置无效

### ISSUE THREAD

**Issue by waya99** [nilaoda/BBDown#592]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。win10

#### 3. 你使用的完整命令是什么？
```
--work-dir
```
#### 4. 遇到了什么问题？
BBDown.config文件配置的地址无效，还是自动下载到根C盘用户目录下

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![1684256098390(1)](https://github.com/nilaoda/BBDown/assets/130042845/ade4b398-e5e3-4742-8710-145f73daf0a0)
![1684256228130](https://github.com/nilaoda/BBDown/assets/130042845/982c3a26-11a8-4f6c-85b2-2ae969f60015)
![1684256143162](https://github.com/nilaoda/BBDown/assets/130042845/03153a0e-3f31-4af0-9165-073aa339a5ad)
![1684256207207](https://github.com/nilaoda/BBDown/assets/130042845/65b4b991-499f-4b1e-89a5-40d4b9ab3a7e)

**Comment by aquawius** [comment]
试试加上引号好不好用
![image](https://github.com/nilaoda/BBDown/assets/70997816/53c76497-29d3-43d0-9a82-f4c0b84c4358)
我的是好用的
