### ISSUE TITLE
TV端源无法解析下载最高码率

### ISSUE THREAD

**Issue by AnitaCanthus** [nilaoda/BBDown#602]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
发布v1.5.5

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win10

#### 3. 你使用的完整命令是什么？
```
BBDown -tv https://www.bilibili.com/bangumi/play/ep743766?spm_id_from=333.1007.0.0
```
#### 4. 遇到了什么问题？
tv端与网页端视频码率不一样，tv端视频源码率没有网页高
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by Kanou911** [comment]
TV端码率一直比网页的低。不是软件问题，有些源还没高码率源
