### ISSUE TITLE
咨询一下，如何导出urls.txt即主页的所有连接

### ISSUE THREAD

**Issue by chenkongming** [nilaoda/BBDown#614]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
xxx

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by nilaoda** [comment]
你可以使用以下命令导出用户的全部视频链接
```
bbdown "https://space.bilibili.com/3766866"
```

**Comment by chenkongming** [comment]
> bbdown "https://space.bilibili.com/3766866"

https://github.com/nilaoda/BBDown/issues/614#issuecomment-1582303649这接口返回{"code":-799,"message":"请求过于频繁，请稍后再试","ttl":1}

**Comment by chenkongming** [comment]
> > bbdown "https://space.bilibili.com/3766866"
> 
> [https://github.com/nilaoda/BBDown/issues/614#issuecomment-1582303649这接口返回{"code":-799,"message":"请求过于频繁，请稍后再试","ttl":1}](https://github.com/nilaoda/BBDown/issues/614#issuecomment-1582303649%E8%BF%99%E6%8E%A5%E5%8F%A3%E8%BF%94%E5%9B%9E%7B%22code%22:-799,%22message%22:%22%E8%AF%B7%E6%B1%82%E8%BF%87%E4%BA%8E%E9%A2%91%E7%B9%81%EF%BC%8C%E8%AF%B7%E7%A8%8D%E5%90%8E%E5%86%8D%E8%AF%95%22,%22ttl%22:1%7D)

 我先抓取网页元素连接吧，这边应该是我频繁调接口被ban了？
