### ISSUE TITLE
几个小问题（建议）

### ISSUE THREAD

**Issue by MC-dusk** [nilaoda/BBDown#62]
win10 1909
v1.3.7

1. 使用软件下载视频后会在“C:\Users\XXX\Videos\”路径下生成BiliBiliDownload文件夹，不知道是作缓存文件夹用还是意外bug。如果是缓存文件夹能否生成在exe所在路径下。（强迫症每次都要手动删除这个文件夹有点难受）
2. 下载视频过程中会下载封面，下载混流结束封面就被删除了，希望能保留封面（或使用参数控制是否下载、是否保存封面）。（封面应该不是混流进了mp4视频里吧）。

以上不是紧要的bug，不影响正常使用。

**Comment by nilaoda** [comment]
第一点 代码中没有相关逻辑……我试了一下好像也没有生成相关文件夹
第二点 程序确实把封面封装到了mp4中 你可以在Windows资源管理器中看到效果

![image](https://user-images.githubusercontent.com/20772925/102230665-206a2100-3f28-11eb-94db-ea5ddd4468cf.png)

![image](https://user-images.githubusercontent.com/20772925/102230745-35df4b00-3f28-11eb-994b-a63c66627dbb.png)

**Comment by MC-dusk** [comment]
谢谢回复，刚刚再次实验，确实一切如您所说

> 在“C:\Users\XXX\Videos\”路径下生成BiliBiliDownload文件夹

没有复现这个情况，我再继续观察

> 希望能保留封面

只要使用-ia并打断下载流程即可保存封面（和字幕）

封面确实封装进mp4文件中，如您上图所示，用potplayer可以看到。

**Comment by MC-dusk** [comment]
> 使用软件下载视频后会在“C:\Users\XXX\Videos\”路径下生成BiliBiliDownload文件夹

找到罪魁祸首了，我同时在使用`哔哩哔哩UWP`http://www.microsoftuwp.com/mobile/apps/7008.html ，是这个软件产生的。
当时测试的时候没往这方面想😅
