### ISSUE TITLE
MAC m1 System.Text.RegularExpressions.Generated.<RegexGenerator_g>F74B1AE921BCEFE4BA601AA541C7A23B1CA9711EA81E8FE504B5B6446748E035A__QueryRegex_13' threw an exception.

### ISSUE THREAD

**Issue by EastDong314** [nilaoda/BBDown#622]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
dotnet global tool 安装

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
mac

#### 3. 你使用的完整命令是什么？
```
BBDown login
```
#### 4. 遇到了什么问题？
The type initializer for 'System.Text.RegularExpressions.Generated.<RegexGenerator_g>F74B1AE921BCEFE4BA601AA541C7A23B1CA9711EA81E8FE504B5B6446748E035A__QueryRegex_13' threw an exception.

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![Screenshot 2023-06-16 at 00 16 01](https://github.com/nilaoda/BBDown/assets/76643642/a3de94a4-8de2-45f1-adf7-a11abebf252c)

**Comment by nilaoda** [comment]
试试直接使用 Release 版本呢。。

**Comment by dogdie233** [comment]
@hez2010 这是.net runtime的问题吗（？）

**Comment by hez2010** [comment]
能否开启 --debug 看一下具体的异常信息。
