### ISSUE TITLE
如何下载大会员60帧的视频？

### ISSUE THREAD

**Issue by XCXDSHS** [nilaoda/BBDown#626]
Release版本1.5.9 win-x64
另外那个设置ffmepg我不懂咋用
假设我命令行下载视频是C:\BBDown.exe bv12345 -tv
我的ffmepg在E:\test\2
我应该在命令行输入什么才能读取在E:\test\2的ffmepg？

**Comment by nilaoda** [comment]
下载大会员60帧的视频 需要你是大会员，然后使用`BBDown login`进行登录

路径：`BBDown --ffmpeg-path E:\test\2\ffmpeg.exe`
