### ISSUE TITLE
怎么退出登录

### ISSUE THREAD

**Issue by Backonemore** [nilaoda/BBDown#63]
在ubuntu上，请问想退出登录应该用什么命令，感谢

**Comment by JasonKhew96** [comment]
删掉 `BBDown.data` 文件就行了

**Comment by Backonemore** [comment]
> 删掉 `BBDown.data` 文件就行了
> EDIT: 还有一个 `BBDownTV.data`

谢谢，已解决

**Comment by Backonemore** [comment]
不知道使用过-c选项后，cookie会不会保存起来，之后每次下载的时候都调用？
如果是的话，请问有清除的方法吗

**Comment by JasonKhew96** [comment]
> 不知道使用过-c选项后，cookie会不会保存起来，之后每次下载的时候都调用？
> 如果是的话，请问有清除的方法吗

`-c` 不会保存

**Comment by Backonemore** [comment]
> > 不知道使用过-c选项后，cookie会不会保存起来，之后每次下载的时候都调用？
> > 如果是的话，请问有清除的方法吗
> 
> `-c` 不会保存

好的，感谢
