### ISSUE TITLE
提示找不到spm_id_from和vd_source

### ISSUE THREAD

**Issue by aantior** [nilaoda/BBDown#635]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
BBDown version 1.5.9, Bilibili Downloader.

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
windows

#### 3. 你使用的完整命令是什么？
```
BBDown --cookie "SESSDATA=XXXX" --video-ascending --audio-ascending --encoding-priority "AV1,hevc,1920x1080" --dfn-priority "1080P 高清, 720P 高清" --file-pattern "AV<aid>_<videoTitle>_<pageNumberWithZero>_<pageTitle>_<dfn>_<res>_<apiType>" --work-dir "./Video"
```
#### 4. 遇到了什么问题？
'spm_id_from' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'vd_source' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/131586786/d4673797-a4b6-4c9e-bb85-7a4ef6497b1a)

**Comment by nilaoda** [comment]
url左右加上英文的引号 `"`
