### ISSUE TITLE
 解析此分P失败(使用--debug查看详细信息)

### ISSUE THREAD

**Issue by linabellbiu** [nilaoda/BBDown#639]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
.\BBDown.exe BV1bj411Z7sv --show-all --debug
```
#### 4. 遇到了什么问题？

 解析此分P失败(使用--debug查看详细信息)

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![1689171113175](https://github.com/nilaoda/BBDown/assets/20228139/b9fae82f-3aaa-4896-814a-4bab0037b500)

**Comment by linabellbiu** [comment]
我已经登录了

**Comment by nilaoda** [comment]
相关：https://github.com/nilaoda/BBDown/discussions/638

**Comment by Aurora-20** [comment]
相同问题+1

**Comment by Aurora-20** [comment]
> 复现失败😨

估计可能昨天晚上有段时间暂时不太行，我现在也好了。

**Comment by enihsyou** [comment]
在这里换个 User-Agent 就好了， https://github.com/nilaoda/BBDown/blob/f331640859c92520ab72b403321bb2c9013f2499/BBDown.Core/Util/HTTPUtil.cs#L22 
实测只要随便改个字母，比如最后的 `Safari/605.1.15` 版本号变一下。

**Comment by nilaoda** [comment]
无法复现
