### ISSUE TITLE
Error: unable to open display

### ISSUE THREAD

**Issue by Backonemore** [nilaoda/BBDown#64]
在vps上使用的时候出现该提示，如下图
![Snipaste_2020-12-22_00-49-31](https://user-images.githubusercontent.com/64834906/102800990-9ae6e500-43ef-11eb-8b3b-b6142d37e219.png)

**Comment by nilaoda** [comment]
尝试安装libgdiplus

**Comment by Backonemore** [comment]
> 尝试安装libgdiplus

已安装，但仍会出现该错误

![Screenshot_20201222_110013](https://user-images.githubusercontent.com/64834906/102847112-b03e2c80-444c-11eb-90c4-d28809032373.jpg)

**Comment by JasonKhew96** [comment]
看样子，ffmpeg mux 那边出问题了，不知道哪一个文件损坏了

**Comment by nilaoda** [comment]
更新ffmpeg试试？到4.0以上

**Comment by Backonemore** [comment]
就是ffmpeg的原因。我用snap装的ffmpeg，是4.3.1版本的。会报错。
我把snap卸载了，去https://johnvansickle.com/ffmpeg/重新装了个ffmpeg，现在不会报错了。
感谢

**Comment by Backonemore** [comment]
用github没多久，才发现好像close issue之后就没法评论了。想问下大佬，一般问题解决之后是直接close吗

**Comment by nilaoda** [comment]
> 用github没多久，才发现好像close issue之后就没法评论了。想问下大佬，一般问题解决之后是直接close吗

close就好

**Comment by Backonemore** [comment]
好的
