### ISSUE TITLE
解析仅限港澳台的番就报“net_http_client_invalid_requesturi”这个错误

### ISSUE THREAD

**Issue by DDRT1999** [nilaoda/BBDown#640]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
bbdown https://www.bilibili.com/bangumi/play/ep567696 -p 13 --debug
```
#### 4. 遇到了什么问题？
解析仅限港澳台的番就报`net_http_client_invalid_requesturi`这个错误

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![屏幕截图 2023-07-14 011903](https://github.com/nilaoda/BBDown/assets/76974253/857c0ee2-848c-440f-92f1-22742953ddb4)
![屏幕截图 2023-07-14 012820](https://github.com/nilaoda/BBDown/assets/76974253/d975f01f-bde4-4922-8ac8-27f966f51df4)

**Comment by Zhumeng14** [comment]
一样的问题，字幕接口估计挂掉了，-skip-subtitle，跳过字幕能正常下载视频。

**Comment by DDRT1999** [comment]
> 一样的问题，字幕接口估计挂掉了，-skip-subtitle，跳过字幕能正常下载视频。

干，原来是阿b的问题，能正常下载了，谢谢老哥😂

**Comment by nilaoda** [comment]
已修复
