### ISSUE TITLE
net_http_message_not_success_statuscode_reason, 412, Precondition Failed

### ISSUE THREAD

**Issue by denjhang** [nilaoda/BBDown#643]
1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release 1.5.9

2. 你在什么系统使用本软件？（Win/Linux/Mac）
win10

3. 你使用的完整命令是什么？
@echo off
set "list-name=lists-200k"
echo %list-name%

for /f "tokens=1 delims=." %%a in ('dir %list-name%*.txt /b') do (
if "%%a.txt"=="lists.txt" (
echo 跳过运行lists.txt列表文件
) else (call:Func %%a )
@Rem 批量扫描指定文件夹下的txt播放列表
)

pause

:Func
echo 目前up主名称：%1
echo 该up主播放列表的文件名为 %list-name%%1.txt
@Rem 先获取文件名

echo --------------------------------------
@Rem 输出一行分隔

echo 新建一个文件夹：%list-name%%1，用于存放该up主视频
md %list-name%%1
@Rem 新建以播放列表文件夹名的文件夹

echo --------------------------------------
@Rem 输出一行分隔

echo 现在调用BBDown下载该up的所有视频，并下载弹幕
echo --------------------------------------

For /F %%a in (%list-name%%1.txt) Do (
BBDown.exe "%%a" --show-all -dd --skip-ai False --work-dir %list-name%%1\
@Rem 下载播放列表文本文件中列出的视频，带参数下载弹幕等

echo --------------------------------------
echo 现在下载完视频了
echo --------------------------------------
@Rem 输出一行分隔
)

goto:eof

4. 遇到了什么问题？
报错，无法下载

5. 运行截图（最好开启--debug；注意自行将Cookie/Token等敏感信息隐藏）
![sshot-20230715-011124](https://github.com/nilaoda/BBDown/assets/61811583/8af19737-702a-4df5-88a4-12c41689bfee)

**Comment by nilaoda** [comment]
下载太频繁了 等等就好
