### ISSUE TITLE
手机大会员不能下载1080P 60FPS 的视频吗？

### ISSUE THREAD

**Issue by XCXDSHS** [nilaoda/BBDown#647]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release1.5.9

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win10

#### 3. 你使用的完整命令是什么？
C:\BBDown_1.5.9_20230622_win-x64\BBDown.exe -app -token "******" "https://www.bilibili.com/video/BV1MW411D7Q2" -info

#### 4. 遇到了什么问题？
手机大会员可以下载大会员1080P 60FPS的视频吗？还是只有TV小电视大会员才能下载1080P 30FPS以上的画质？

**Comment by nilaoda** [comment]
建议使用 WEB api，app接口很久没维护了

**Comment by XCXDSHS** [comment]
那应该怎么使用命令，我尝试了以下两个但都失败 (以使用login成功登录)
1：提示"你尚未登录B站账号, 解析可能受到限制"
C:\BBDown_1.5.9_20230622_win-x64\BBDown.exe -c "SESSDATA=******" "https://www.bilibili.com/video/BV1MW411D7Q2"
2：提示 Unrecognized command or argument 'SESSDATA=******'.
C:\BBDown_1.5.9_20230622_win-x64\BBDown.exe -web "SESSDATA=******" "https://www.bilibili.com/video/BV1MW411D7Q2"

**Comment by nilaoda** [comment]
已使用login成功登录无需进行额外操作 直接下载就行了

**Comment by lightfindyou** [comment]
我已经通过BBDown会员登陆，但是只能下载前6分钟的视频，我用的debian系统，版本是 BBDown version 1.6.0，命令是 BBDown -tv -p All "https://www.bilibili.com/bangumi/play/ep327362?from_spmid=666.25.episode.0"

**Comment by XCXDSHS** [comment]
我和楼上的一样使用login成功登录，然后直接用-tv下载，和没有手机大会员的选项一模一样，我看了其它人的问题，应该是因为-tv必须要小电视大会员才行，手机大会员似乎没什么用，以后再试试

**Comment by XCXDSHS** [comment]
似乎可以不加-tv直接使用普通接口下载说不定支持手机大会员，下次试试
