### ISSUE TITLE
无法登录&无法下载视频

### ISSUE THREAD

**Issue by Goojoe** [nilaoda/BBDown#651]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
1.6.0 Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win
#### 3. 你使用的完整命令是什么？
```
BBDown login
```
#### 4. 遇到了什么问题？
无法登录,极低概率可以弹出二维码,登录后也无法下载视频,卡在加载cookie

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
```
PS C:\Users\Administrator\Desktop> BBDown.exe login --debug
BBDown version 1.6.0, Bilibili Downloader.
欢迎到讨论区交流：
https://github.com/nilaoda/BBDown/discussions

[2023-07-21 18:43:58.537] - Unrecognized command or argument '--debug'.
```

```
PS C:\Users\Administrator\Desktop> BBDown.exe login
BBDown version 1.6.0, Bilibili Downloader.
欢迎到讨论区交流：
https://github.com/nilaoda/BBDown/discussions

[2023-07-21 18:44:00.952] - 获取登录地址...
```

**Comment by ZGMF-X56S** [comment]
我也是相同的问题，login报错

> The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.

估计是B站改了api的地址

**Comment by nilaoda** [comment]
无法复现

**Comment by Goojoe** [comment]
--debug选项没有用，你可以加入更多的捕捉错误的方式吗？

**Comment by dogdie233** [comment]
因为登录命令没有`--debug`参数(

**Comment by Goojoe** [comment]
找到原因了Clash TUN 模式导致的问题,关闭就好了
