### ISSUE TITLE
下载视频时无法下载字幕

### ISSUE THREAD

**Issue by Pythame** [nilaoda/BBDown#652]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release 1.6.0

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win x64

#### 4. 遇到了什么问题？
当命令为
```
D:\BBDown\BBDown.exe "https://www.bilibili.com/video/BV1Eb411u7Fw/"  --ffmpeg-path "D:\BBDOwn\ffmpeg.exe"  --sub-only   --debug  --skip-ai false  -mt  --force-http  --work-dir "C:\Users\Administrator\Downloads"
```
时，可正常下载AI字幕。

但当命令没有--sub-only，即命令为
```
D:\BBDown\BBDown.exe "https://www.bilibili.com/video/BV1Eb411u7Fw/"  --ffmpeg-path "D:\BBDOwn\ffmpeg.exe"  --debug  --skip-ai false  -mt  --force-http  --work-dir "C:\Users\Administrator\Downloads"
```
时，debug中有字幕下载，并且在临时文件夹中有正确的srt文件，但字幕并没有被移动到目标下载文件夹。
注：只测试了AI字幕的下载，未测试普通字幕

#### 猜想
可能是清除临时文件夹前未复制srt文件

**Comment by nilaoda** [comment]
经测试没有出现问题

![image](https://github.com/nilaoda/BBDown/assets/20772925/f66771ba-cc3b-4bf6-b2aa-1c541691c257)

**Comment by nilaoda** [comment]
@Pythame 建议开一个新的issue描述你的需求
