### ISSUE TITLE
水印问题

### ISSUE THREAD

**Issue by Rhodri-hc** [nilaoda/BBDown#654]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。1.6.0 Release 

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。win

#### 3. 你使用的完整命令是什么？
```
BBDown ...  .\BBDown.exe -tv BV1XXXXXXXXXX
```
#### 4. 遇到了什么问题？
xxx 现在都没发去除水印，该怎么处理好呢

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by specked2527** [comment]
@Rhodri-hc 别用

**Comment by nilaoda** [comment]
工具本身没有去除水印的能力 取决于服务器返回的媒体文件是否包含水印。
