### ISSUE TITLE
💫为什么😅 命令缺少必需的参数：“BBDown”

### ISSUE THREAD

**Issue by specked2527** [nilaoda/BBDown#656]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
BBDown version 1.6.0,Release版本

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```

 BBDown --mp4box-path <C:\Program Files\GPAC\mp4box.exe>
BBDown --debug
BBDown  --mp4box-path <mp4box-path>

```
#### 4. 遇到了什么问题？
cmd : Required argument missing for command: 'BBDown'.

powershell:
所在位置 行:1 字符: 22
+ BBDown --mp4box-path <C:\Program Files\GPAC\mp4box.exe>
+                      
“<”运算符是为将来使用而保留的。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/124735279/6949dbf0-3278-4bbb-b4b2-10b2866accf6)

**Comment by xhlove** [comment]
因为这是下载视频的工具，你至少得跟个url在后面

**Comment by dogdie233** [comment]
🤣👉
