### ISSUE TITLE
建议在下载时加一个进度条，或者是滚动的省略号之类的，不然以为卡住了，没有在下载中。

### ISSUE THREAD

**Issue by lengdong863** [nilaoda/BBDown#663]
![image](https://github.com/nilaoda/BBDown/assets/46510506/64c30ee7-ba45-4907-be73-8fe30c91ca2e)

**Comment by nilaoda** [comment]
正常情况下应该有进度条显示的

**Comment by lengdong863** [comment]
那就是在“尝试将音/视频流强制替换为XXXXXX”时，没有进度条显示？
还是说我的配置出现问题？
