### ISSUE TITLE
小白

### ISSUE THREAD

**Issue by monwow** [nilaoda/BBDown#664]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
[BBDown v1.6.0] , Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
--video-only

#### 4. 遇到了什么问题？
为什么我成功下载后 UP的水印依旧还在

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by specked2527** [comment]
@monwow  谁告诉你可以去水印的
