### ISSUE TITLE
下载出现错误

### ISSUE THREAD

**Issue by SkyDream01** [nilaoda/BBDown#666]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
Release1.6.0

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win

#### 3. 你使用的完整命令是什么？
```
BBDown --audio-only --debug BV1vP411r7dM
```
#### 4. 遇到了什么问题？
下载出现错误

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
<img width="850" alt="屏幕截图 2023-08-04 132950" src="https://github.com/nilaoda/BBDown/assets/86307796/3523f9b0-efb8-42d6-835c-b98106468742">

**Comment by dogdie233** [comment]
换最新的ci build试试
