### ISSUE TITLE
在番剧批量下载的命名规则

### ISSUE THREAD

**Issue by tang-bai** [nilaoda/BBDown#667]
现在番剧批量下载的格式为 [P01]1 xxx.mp4 
之后是否可以考虑更改成S01E01 xxx.mp4   前面为季度后面为集数
这样子可以直接把番剧导入到emby或者jellyfin进行识别

**Comment by dogdie233** [comment]
但是怎么识别是第几季呢

**Comment by specked2527** [comment]
@tang-bai  不可以 无法识别季度

**Comment by dogdie233** [comment]
可以用自定义文件名，自己补上季度就好了，比如`-F "S01E<pageNumberWithZero> <pageTitle>"`

**Comment by tang-bai** [comment]
> @tang-bai 不可以 无法识别季度

那好吧

**Comment by dogdie233** [comment]
> > 可以用自定义文件名，自己补上季度就好了，比如`-F "S01E<pageNumberWithZero> <pageTitle>"`
> 
> BBDown -p ALL -F "S01E " https://www.bilibili.com/bangumi/play/ss34402 我在使用这个命令之后发现不能成功命名是我命令错了吗

是的，应该用`BBDown -p ALL -F "S01E<pageNumberWithZero> <pageTitle>" https://www.bilibili.com/bangumi/play/ss34402`

**Comment by tang-bai** [comment]
> > > 可以用自定义文件名，自己补上季度就好了，比如`-F "S01E<pageNumberWithZero> <pageTitle>"`
> > 
> > 
> > BBDown -p ALL -F "S01E " https://www.bilibili.com/bangumi/play/ss34402 我在使用这个命令之后发现不能成功命名是我命令错了吗
> 
> 是的，应该用`BBDown -p ALL -F "S01E<pageNumberWithZero> <pageTitle>" https://www.bilibili.com/bangumi/play/ss34402`

我在使用1.6.0版本使用你给出的命令无法重命名
![image](https://github.com/nilaoda/BBDown/assets/71223830/9dc3c1dc-9c9a-48df-ba3c-22ec83d9d2f0)
![image](https://github.com/nilaoda/BBDown/assets/71223830/3c47d4b3-c7d3-4bea-9534-87a6a7537a1c)

**Comment by dogdie233** [comment]
噢如果是多p的话需要用`-M`参数而不是`-F`
另外我刚刚试了一下，这个视频标题貌似本身就带个集数
如果用 `-M "S01E<pageNumberWithZero> <pageTitle>"` 就会变成 `S01E01 1 降临之日.mp4`
如果是 `-M "S01E<pageTitle>"` 就会变成 `S01E1 降临之日.mp4`
最好是把这个参数的用法搞懂
