### ISSUE TITLE
无法单独下载合集的封面，文件名带\导致无法创建对应目录

### ISSUE THREAD

**Issue by mengtaixiao** [nilaoda/BBDown#671]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。Release版本 v1.6.0

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。Win 和 Linux 均可复现

#### 3. 你使用的完整命令是什么？
```
BBDown --cover-only https://www.bilibili.com/video/BV1YA411Q783?p=3
```
#### 4. 遇到了什么问题？
无法单独下载合集的封面，报错红字提示：

 **IO_PathNotFound_Path, D:\temp\【阿梓】感染力满分！苦情歌翻唱精选合集（1）\\[P003]阿楚姑娘.jpg**

推测是文件名包含符号\，导致无法创建文件

经过测试，下载完整视频或先下载音频，是可以正常创建出对应目录，
有对应的目录了，然后就可以单独下载封面了。     看来问题不大
如下（正常）：
```
BBDown --audio-only https://www.bilibili.com/video/BV1YA411Q783?p=3
BBDown --cover-only https://www.bilibili.com/video/BV1YA411Q783?p=3
```

如下（异常）：
```
BBDown --cover-only https://www.bilibili.com/video/BV1YA411Q783?p=3
```

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/43106255/98e1fb66-da20-491f-a3e9-404776fa31a6)

。。。

**Comment by nilaoda** [comment]
已修复，到 [Actions](https://github.com/nilaoda/BBDown/actions) 中下载最新自动构建进行测试。
