### ISSUE TITLE
BV1r94y1q7Kq下载第0条视频播放异常

### ISSUE THREAD

**Issue by ciring** [nilaoda/BBDown#672]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
1.6.0

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win

#### 3. 你使用的完整命令是什么？
```
BBDown.exe https://www.bilibili.com/video/BV1r94y1q7Kq/ 
```
#### 4. 遇到了什么问题？
默认第0个视频格式为av1，视频文件播放有问题，hotplayer无法播放，vlc播放只有一张图片不动。
手动指定下载第1个视频，hevc，无问题
不知道是原视频问题还是下载器问题

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by dogdie233** [comment]
复现不出来，用视频流`[1080P 高清] [1920x1080] [AV1]` 在potplayer可以正常播放
