### ISSUE TITLE
net_http_message_not_success_statuscode_reason, 429, Too Many Requests

### ISSUE THREAD

**Issue by AlwaysControl** [nilaoda/BBDown#682]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
![image](https://github.com/nilaoda/BBDown/assets/142526752/7058bc8f-05ff-48a4-851c-f05dd9d8268f)

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win10-x64

#### 3. 你使用的完整命令是什么？
```
bbdown BV15p4y1J7Ei
config:
--skip-subtitle;
--skip-ai;
-F 【<ownerName><ownerMid>】<pageTitle><videoCodecs>_<res>_<fps>_<videoBandwidth>_<audioCodecs>_<audioBandwidth>;
--work-dir O:\bilibili


```
#### 4. 遇到了什么问题？
无论何种视频均无法下载，提示net_http_message_not_success_statuscode_reason, 429, Too Many Requests

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/142526752/65c80e5b-5e63-4171-92bc-05155a4b50f8)

**Comment by nilaoda** [comment]
1.6.1已解决
