### ISSUE TITLE
错误提示： net_http_message_not_success_statuscode, 429, Too Many Requests

### ISSUE THREAD

**Issue by thewq123** [nilaoda/BBDown#685]
#### 1. 你使用的BBDown版本是什么？（指明是Release版本还是Actions版本）
。。。1.5.4

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。deepin

#### 3. 你使用的完整命令是什么？
```
./BBDown  -tv --audio-only

```
#### 4. 遇到了什么问题？
下载不了视频

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by nilaoda** [comment]
遇到问题麻烦升级到最新版 如果不能再来反馈
