### ISSUE TITLE
1.6.1“你尚未登录b站账号，解析可能受限制。”下载后水印依然存在。

### ISSUE THREAD

**Issue by Bchemilogy** [nilaoda/BBDown#687]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
。。。

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
xxx

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by specked2527** [comment]
@Bchemilogy 谁告诉你可以去水印的

**Comment by 520Fairy** [comment]
BBDown version 1.6.3, Bilibili Downloader.
遇到问题请首先到以下地址查阅有无相关信息：
[2025-01-11 18:43:18.843] - 检测账号登录...
[2025-01-11 18:43:18.844] - 加载本地cookie...
[2025-01-11 18:43:21.055] - 你尚未登录B站账号, 解析可能受到限制
[2025-01-11 18:43:21.055] - 获取aid...
输入有误
请尝试升级到最新版本后重试!

**Comment by 520Fairy** [comment]
> BBDown 1.6.3 版本，Bilibili 下载器。 遇到问题请首先到以下地址查阅有无相关信息： [2025-01-11 18：43：18.843] - 检测账号登录... [2025-01-11 18：43：18.844] - 加载本地cookie... [2025-01-11 18：43：21.055] - 你尚未登录B站账号， 解析可能受到限制 [2025-01-11 18：43：21.055] - 获取援助... 输入有误 请尝试升级到最新版本后重试！

一直不能获取登录的二维码
