### ISSUE TITLE
The remote server returned an error: (412) Precondition Failed.

### ISSUE THREAD

**Issue by jccforever** [nilaoda/BBDown#69]
D:\Downloads\Compressed\BBDown_v1.3.7_20201213>BBDown "https://www.bilibili.com/video/BV1wb411p7jW"
BBDown version 1.3.7, Bilibili Downloader.
欢迎到讨论区交流：
https://github.com/nilaoda/BBDown/discussions

[2020-12-27 10:48:42.449] - 加载本地cookie...
[2020-12-27 10:48:42.453] - 获取aid...
The remote server returned an error: (412) Precondition Failed.

**Comment by nilaoda** [comment]
更换cookie

**Comment by qingyi11** [comment]
> 
> 
> 更换cookie

怎么换

**Comment by nilaoda** [comment]
#83
