### ISSUE TITLE
最新版本使用了.NET 8 Preview，使用不方便，建议打包为支持多运行时的包。

### ISSUE THREAD

**Issue by zmjack** [nilaoda/BBDown#696]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.1

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```

#### 4. 遇到了什么问题？
使用不方便，运行时支持过少，且使用了 **预览版运行时**。

是否打包为支持多运行时的包，特别是长期支持的运行时。

**Comment by dogdie233** [comment]
因为会用到高版本的新功能

**Comment by nilaoda** [comment]
Release 版本无需关注运行时，另外 .NET8 正式版也没差几个月就发布了，.NET8 会是 LTS 版。
