### ISSUE TITLE
【2023/2/25】  net_http_message_not_success_statuscode_reason,404,not found

### ISSUE THREAD

**Issue by GPQ2333** [nilaoda/BBDown#700]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
。。。Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。Win11

#### 3. 你使用的完整命令是什么？
```
BBDown.exe https://www.bilibili.com/...........
```
#### 4. 遇到了什么问题？
net_http_message_not_success_statuscode_reason,404,not found

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
-加载本地cookie...
-检测账号登陆...
-获取aid...
net_http_message_not_success_statuscode_reason,404,not found
‘vd_source’不是内部或外部命令，也不是可运行程序或批处理文件

**Comment by dogdie233** [comment]
请↓升↑级↓到↑1.6.1

**Comment by GPQ2333** [comment]
> 请↓升↑级↓到↑1.6.1

我喜欢你

**Comment by dogdie233** [comment]
> > 请↓升↑级↓到↑1.6.1
> 
> 我喜欢你

感谢喜欢，你可以把issue关掉了😊
