### ISSUE TITLE
net_http_message_not_success_statuscode_reason, 404, Not Found

### ISSUE THREAD

**Issue by Cans518** [nilaoda/BBDown#702]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Release v1.6.1  

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
windows
#### 3. 你使用的完整命令是什么？
```
BBDown -tv "https://www.bilibili.com/video/BV1qt4y1X7TW"
```
#### 4. 遇到了什么问题？
在本地网络正常的情况下，出现404报错。

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
<img width="1118" alt="image" src="https://github.com/nilaoda/BBDown/assets/52856665/f0bef442-c40b-42b8-a7da-a1f2965e9e3d">

**Comment by specked2527** [comment]
重复问题 更新到v1.6.1

**Comment by dogdie233** [comment]
虽然你issue写了是1.6.1但是运行打印显示还是1.6.0，请检查是否正确更新

**Comment by Cans518** [comment]
感想大家，确认了自己犯蠢更新未完成
