### ISSUE TITLE
希望自定义文件名时，可以增加字符串的部分选中功能

### ISSUE THREAD

**Issue by xiexie2001** [nilaoda/BBDown#704]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
。。。
1.61.1
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。
Windows 10 22H2
#### 3. 你使用的完整命令是什么？
```
BBDown https://www.bilibili.com/video/BV1Mp4y1N7vQ -p 1 --audio-only -M "<pageTitle>"
```
#### 4. 遇到了什么问题？
我下载该链接对应的音频时，由于博主上传的分p文件带序号，下载后我希望得到无序号文件，因此需要对分p名称做切片操作，而目前版本未找到相关功能

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by nilaoda** [comment]
这个可行性待验证

**Comment by dogdie233** [comment]
快进到把bbdown做成Powershell模块，定义IFileNameProvider接口，在Powershell中定义实现此接口的方法再传入bbdown中(
