### ISSUE TITLE
下载不了

### ISSUE THREAD

**Issue by caijidu** [nilaoda/BBDown#705]
报错信息为：net_http_message_not_success_statuscode, 404, Not Found

**Comment by caijidu** [comment]
版本1.5.4

**Comment by dogdie233** [comment]
# 发issue之前先看看置顶issue
# 发issue之前先看看是否有相同的issue
# 发issue之前先确定自己为最新版本
![39e827dc9708ba6619187437f76e1420](https://github.com/nilaoda/BBDown/assets/42267840/75929185-ef79-47d7-b894-c8664b751aa6)

另外本问题已在 Release 1.6.1 中得到修复
