### ISSUE TITLE
Response status code does not indicate success: 404 (Not Found).

### ISSUE THREAD

**Issue by Jiang10086** [nilaoda/BBDown#707]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
。。。
1.6.0，DotnetTool，个人太愚笨了，不知道怎样才能将 dotnet 的 BBDown 更新到 1.6.1，抱歉
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。
Windows 11
#### 3. 你使用的完整命令是什么？
BBDown BV1w3411v7jd

#### 4. 遇到了什么问题？
报错无法下载

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。
![image](https://github.com/nilaoda/BBDown/assets/67213568/c4fe5685-2312-48f7-a192-70c90aa79eb1)

**Comment by dogdie233** [comment]
`dotnet tool update bbdown --global`

**Comment by Jiang10086** [comment]
![image](https://github.com/nilaoda/BBDown/assets/67213568/b3fd838f-6c95-46d7-9b31-db3bade253ca)

**Comment by dogdie233** [comment]
> ![image](https://user-images.githubusercontent.com/67213568/265632955-b3fd838f-6c95-46d7-9b31-db3bade253ca.png) 无法升级

在资源管理器进入这个路径 `%AppData%\..\..\.dotnet\tools`
把里面的 `BBDown.exe` 和 `.store`文件夹里面的`bbdown`文件夹扬了

**Comment by Jiang10086** [comment]
恢复正常了，谢谢

**Comment by Jiang10086** [comment]
恢复正常了，谢谢！
