### ISSUE TITLE
最新版的BBDown和ffmpeg ，下载下来依旧带有原视频的logo，求助！

### ISSUE THREAD

**Issue by sobad123** [nilaoda/BBDown#717]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
。。。
release
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。
win
#### 3. 你使用的完整命令是什么？
```
BBDown ...
BBDown --video-only
#### 4. 遇到了什么问题？
xxx
视频画面中的水印依旧存在，已经是最新版本的
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。
![image](https://github.com/nilaoda/BBDown/assets/144236855/809c9891-f461-486b-affc-7a6c82f44821)

**Comment by specked2527** [comment]
什么机器人🤬

**Comment by specked2527** [comment]
> #### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
> 。。。 release
> 
> #### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
> 。。。 win
> 
> #### 3. 你使用的完整命令是什么？
> ```
> BBDown ...
> BBDown --video-only
> #### 4. 遇到了什么问题？
> xxx
> 视频画面中的水印依旧存在，已经是最新版本的
> #### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
> 。。。
> ![image](https://github.com/nilaoda/BBDown/assets/144236855/809c9891-f461-486b-affc-7a6c82f44821)
> ```
什么机器人🤬

**Comment by dogdie233** [comment]
#714

**Comment by ZoeyKong** [comment]
请问你解决了吗？我也遇到了

**Comment by sobad123** [comment]
没有解决，还在困惑中
