### ISSUE TITLE
net_http_message_not_success_statuscode_reason, 404, Not Found

### ISSUE THREAD

**Issue by denjhang** [nilaoda/BBDown#718]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
[修复跨平台无法获取`Console.Title`问题](https://github.com/nilaoda/BBDown/actions/runs/6099241977)
Build Latest #170: Commit [0391679](https://github.com/nilaoda/BBDown/commit/03916792e9ffcba361575f031c83987d5977b4bb) pushed by [nilaoda](https://github.com/nilaoda)

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win10

#### 3. 你使用的完整命令是什么？
bbdown https://www.bilibili.com/video/av915627399
#### 4. 遇到了什么问题？
服了，全都下不了。

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）

![sshot-20230908-223740](https://github.com/nilaoda/BBDown/assets/61811583/a221de6c-3a63-4272-9ae0-d5068977b7dc)

**Comment by dogdie233** [comment]
但是你的bbdown版本是1.5.9

**Comment by dogdie233** [comment]
应该是用了dotnet下载的版本？
换成./bbdown试试

**Comment by nilaoda** [comment]
非最新版.
