### ISSUE TITLE
下载的视频有水印，需要怎么解决

### ISSUE THREAD

**Issue by hellowsxiaoyang** [nilaoda/BBDown#719]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
 Release 

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win
#### 3. 你使用的完整命令是什么？
```
BBDown.exe BV1wh4y1N7e3 -tv
```
#### 4. 遇到了什么问题？
下载的视频有水印

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by specked2527** [comment]
@hellowsxiaoyang   你们都不看说明？_普通内容下载（Web|电视|应用）(TV接口可以下载部分UP主的无水印内容)_  

 搜索水印 ，有 _16 Closed ，3 打开_ 的问题 
你是第18个问的。

@nilaoda 软件作者真是不在乎在说明 添加一句  _不支持去水印，但视频本身没有水印的可以下载_

**Comment by hellowsxiaoyang** [comment]
好的，我没注意到，多谢回答。
我下午看了下，主要是合并音视频，但是有的视频没有水印，以为有去水印操作，就好奇问下。
