### ISSUE TITLE
QR code is incorrect

### ISSUE THREAD

**Issue by girod2033** [nilaoda/BBDown#722]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Release (1.6.1)

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
BBDown logintv
```
#### 4. 遇到了什么问题？
Hello.
I have a question about "BBDown logintv". I have a Bilibili Premium subscription (Philippines). I execute the command “BBDown logintv”, the QR code appears, I launch the bilibili application on my phone, then I select scan the QR code, but it tells me that the QR code is incorrect.
Tell me, please, what is the problem?

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by nilaoda** [comment]
`BBDown logintv` is for Chinese mainland only.

For Intl version of Bilibili, you can pass `token` to BBDown (`--access-token YOUR_TOKEN_HERE`). You can obtain the token by Packet Capture.

**Comment by specked2527** [comment]
> > `BBDown logintv` is for Chinese mainland only.
> > For Intl version of Bilibili, you can pass  to BBDown (). You can obtain the token by Packet Capture.`token``--access-token YOUR_TOKEN_HERE`
> 
> Thank you for the clarification.
> 
> Please explain these parameters: --host : I need to specify --host BiliPlus --ep-host : I need to specify --host BiliPlus EP --area : Does this only apply to three options? (hk|tw|th) What's the point?
> 
> What settings can I use to get the maximum bitrate for 1080 or 4K versions with an international subscription?

 What settings can I use to get the maximum bitrate for 1080 or 4K versions with an international subscription?
这不是破解，你必须登入要有VIP权限，-q, --dfn-priority <dfn-priority>

**Comment by girod2033** [comment]
Thanks everyone for the explanation.
