### ISSUE TITLE
应有跳过检测版本选项

### ISSUE THREAD

**Issue by macheteHot** [nilaoda/BBDown#724]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
V1.6.1

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Mac

#### 3. 你使用的完整命令是什么？
```
BBDown BV 
```
#### 4. 遇到了什么问题？
检测新版本更新 github 在国内连接不稳定 耗费时间

#### 5.
期望能有参数跳过检测版本更新 或者异步连接github检测

**Comment by nilaoda** [comment]
现在就是异步的 不发生异常的情况下不会阻塞主线程

**Comment by macheteHot** [comment]
原因找到了。是因为我 ipv6 的 dns down 了 不是卡在版本检测上
