### ISSUE TITLE
stucking on 98%

### ISSUE THREAD

**Issue by kucingkembar** [nilaoda/BBDown#734]
sorry I am not a Chinese or native English speaker, I translated it using Google Translate, I hope you understand

#### 1. What version of BBDown are you using? (specify Release/Actions/DotnetTool)
BBDown.exe -version
BBDown version 1.6.1, Bilibili Downloader.
#### 2. On what system are you using this software? (Win/Linux/Mac)
Windows 11
#### 3. What is the complete command you used?
BBDown.exe https://www.bilibili.com/video/XXXXXXXXXXXX/
#### 4(A). What problems did you encounter?
after some time, the downloading gets stuck, even if waiting for hours,
the / - \ |  is still Spinning, but the progress bar, percentage, and kbps or mbps speed are stuck,
#### 4(B). future request
1. please add English output
2. please add features like yt-dlp --download-archive downloaded.txt, when a link is successfully downloaded, it will write in downloaded.txt, 
#### 5. Run screenshot (it is best to turn on `--debug`; be careful to hide sensitive information such as Cookie/Token by yourself)
![Untitled](https://github.com/nilaoda/BBDown/assets/47294266/ede3e0b9-60f1-4868-9865-16c4bcdb1464)

**Comment by nilaoda** [comment]
You can try use Aria2c.

And `--download-archive` will support in future.
