### ISSUE TITLE
The remote server returned an error: (412) Precondition Failed.

### ISSUE THREAD

**Issue by qingyi11** [nilaoda/BBDown#74]
解决不了这个问题了求助

**Comment by nilaoda** [comment]
可以重新登录试试。 如果不行的话使用记事本打开程序目录下的BBDown.data，后从网页f12-application左侧cookies 找到对应的值替换保存。

**Comment by kurakikyrakiujarod** [comment]
我也遇到了同样的问题，从网页cookies-SESSDATA 找到对应的值替换保存，也不好使。

**Comment by nilaoda** [comment]
#83
