### ISSUE TITLE
仅解析 某个分辨率的视频

### ISSUE THREAD

**Issue by Lxingy** [nilaoda/BBDown#754]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.1
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win

#### 3. 你使用的完整命令是什么？
```
BBDown ss -p '1080 高清'
```
#### 4. 遇到了什么问题？
仅需要1080P的视频，但解析了多个流，无法自定义，或者是否没有匹配就跳过下载

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/90240960/4b316680-7347-4a61-aeb6-686b0c05dd1a)

**Comment by nilaoda** [comment]
`-q` 不是 `-p`
