### ISSUE TITLE
保存单独的封面，视频，音频

### ISSUE THREAD

**Issue by JIUCAIMI** [nilaoda/BBDown#755]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.1Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win

#### 3. 你使用的完整命令是什么？

BBDown url
#### 4. 遇到了什么问题？
直接下载时 自动合成音视频了，我想把下载的封面，视频，和音频保留下载。现在当成临时文件自动清理了

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
现在下载完只有这一个<img width="705" alt="image" src="https://github.com/nilaoda/BBDown/assets/134661380/0ff03c89-05a2-48b6-b35c-cef89bd2bee3">

我想要是这样的

<img width="533" alt="image" src="https://github.com/nilaoda/BBDown/assets/134661380/335b0066-97b2-4449-9a1a-c1981ae0b9cd">

或者这样

<img width="658" alt="image" src="https://github.com/nilaoda/BBDown/assets/134661380/36fce9ee-00bd-433b-a06f-2e469b7060cf">

**Comment by nilaoda** [comment]
```
--skip-mux                                     跳过混流步骤
```
