### ISSUE TITLE
mac 电脑怎么使用？

### ISSUE THREAD

**Issue by DerrickTel** [nilaoda/BBDown#757]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
。。。
1.6.1

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。
mac
#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
xxx

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by specked2527** [comment]
https://github.com/nilaoda/BBDown/discussions/149
