### ISSUE TITLE
您好，程序的API服务器模式如何启动？ 按文档的例子启动不了实例

### ISSUE THREAD

**Issue by kzwr** [nilaoda/BBDown#760]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
。。。
BBDown_1.6.1_20230818_win-x64

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。
Windows 
#### 3. 你使用的完整命令是什么？
```
BBDown.exe  server -l http://0.0.0.0:12450
```
#### 4. 遇到了什么问题？
Unrecognized command or argument '-l'.
请使用 BBDown --help 查看帮助

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/15187811/b12e8b36-1d62-4061-b4e5-5171b515ffd3)

**Comment by gnattu** [comment]
需要用actions版本：https://github.com/nilaoda/BBDown/actions

目前的正式版本还没包含服务器相关的代码

**Comment by nilaoda** [comment]
1. 使用actions版本
2. 不是server, 是serve
3. Release版本也会在近期发布

**Comment by kzwr** [comment]
> 1. 使用actions版本
> 
>     2. 不是server, 是serve
> 
>     3. Release版本也会在近期发布

谢谢您们的解答，问题解决了

**Comment by nexmoe** [comment]
@gnattu @nilaoda Actions 版本中的 Artifacts 全部过期了
