### ISSUE TITLE
您好， add-task 接口的 FilePattern 属性不起效果

### ISSUE THREAD

**Issue by kzwr** [nilaoda/BBDown#761]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
#759 from My-Responsitories/master  最新自动构建版本

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows

#### 3. 你使用的完整命令是什么？
```
{
    "Url": "https://www.bilibili.com/video/BV1ms411Q7vw?p=3",
    "FFmpegPath":"D:\\BaiduNetdiskDownload\\ffmpeg.exe",
    "FilePattern": "C:\\Users\\Administrator\\Desktop\\BBDown_win-x64\\output\\<aid>"
}
```
#### 4. 遇到了什么问题？
FilePattern 设置的路径规则没起作用，

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/15187811/b269a7e5-ef60-4c47-b610-7119af936a66)

**Comment by gnattu** [comment]
多分P视频需要使用`MultiFilePattern`, 如同命令行一样。 比如：

```
"MultiFilePattern": "C:\\Users\\Administrator\\Desktop\\BBDown_win-x64\\output\\<aid>\\[P<pageNumberWithZero>]<pageTitle>" }'
```
