### ISSUE TITLE
指定单P存储文件名后报错：Arg_IndexOutOfRangeException

### ISSUE THREAD

**Issue by cherinyy** [nilaoda/BBDown#762]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）

Actions https://github.com/nilaoda/BBDown/commit/bf3f08f2b9dba1ef97cecfef280c72350068371a

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）

Windows 10 22H2

#### 3. 你使用的完整命令是什么？

```
BBDown BV1BG4y137mG
```
BBDown.config

```
--allow-pcdn
-F
<videoTitle> [<bvid>]
--force-http
false
--force-replace-host
false
-e
avc, hevc, av1
-M
<videoTitle> [<bvid>]/[P<pageNumberWithZero>] <pageTitle>
-q
杜比视界, HDR 真彩, 8K 超高清, 4K 超清, 1080P 高帧率, 1080P 高码率
```

#### 4. 遇到了什么问题？

报错：Arg_IndexOutOfRangeException

实测发现是由于无法以 `<videoTitle> [<bvid>]` 格式存储文件。

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）

![image](https://github.com/nilaoda/BBDown/assets/9050713/4a5c2183-236f-41ed-94c7-622a827bcbaa)

**Comment by nilaoda** [comment]
已修复
