### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by wincss** [nilaoda/BBDown#763]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
dotnet tool 1.6.1
BBDown version 1.6.1, Bilibili Downloader.

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Intel Mac macOS 14.0

#### 3. 你使用的完整命令是什么？
```
BBDown login
```
#### 4. 遇到了什么问题？
The given key was not present in the dictionary.

```
% BBDown login
[2023-11-11 16:29:26.748] - 获取登录地址...
[2023-11-11 16:29:27.321] - The given key was not present in the dictionary.
```

有时候能显示出二维码，但不等扫描就会提示 The given key was not present in the dictionary. 然后退出

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
login 命令并不支持 `--debug`

**Comment by nilaoda** [comment]
这个actions版本已经修复 正式版本最近更新一下
