### ISSUE TITLE
<url>参数不能填写ep或ss号 需要填写完整url地址

### ISSUE THREAD

**Issue by caomeiguojiang** [nilaoda/BBDown#764]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）

Actions: [修复BV计算问题 fix #762](https://github.com/nilaoda/BBDown/actions/runs/6799082578)

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Linux

#### 3. 你使用的完整命令是什么？
```
bbdown ss708 -p 1 --debug
```
#### 4. 遇到了什么问题？
url参数不能填写课堂的ss 即ss708 使用url路径可以运行(bbdown https://www.bilibili.com/cheese/play/ss708 -p 1 --debug 正常工作)

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/56473710/b734caf4-b3fb-4911-af6e-6f9a05bc7a61)

**Comment by ChanJohann** [comment]
我这里显示“访问权限不足”，账号已登录、课程已购买。

#### {"code":-403,"message":"访问权限不足"}

**Comment by lc6464** [comment]
已修复此问题，但是在课程与番剧存在相同 ep 或 ss ID 时，番剧优先。
只有给定的 ep 或 ss ID 找不到对应的番剧时才会去找课程。
相当于在一定程度上保留了原来的逻辑。

另外，可以通过输入 `cheese/ep\d+` 或 `cheese/ss\d+` 实现直接按课程解析。
