### ISSUE TITLE
下载已购入的课堂视频返回{"code":-403,"message":"访问权限不足"} 解析此分P失败

### ISSUE THREAD

**Issue by caomeiguojiang** [nilaoda/BBDown#765]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）

Actions: [修复BV计算问题 fix #762](https://github.com/nilaoda/BBDown/actions/runs/6799082578)

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Linux

#### 3. 你使用的完整命令是什么？
```
bbdown https://www.bilibili.com/cheese/play/ep27460 -p 4 --debug
```
#### 4. 遇到了什么问题？
已购入的课堂的视频无法正常下载 可以正常获取视频信息、分P标题等 解析分P、下载时 api.bilibili.com{"code":-403,"message":"访问权限不足"}；
同时测试BV视频可以正常下载)

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/56473710/07eea45b-95a5-478e-9438-533fedfe1dbd)

**Comment by aantior** [comment]
我也有购买课程，还没有尝试过下载。
等下试试。

**Comment by caomeiguojiang** [comment]
> 我也有购买课程，还没有尝试过下载。 等下试试。
> 
> 尝试过了，是可以正常下载的，但是不能将课程一个链接下载完毕，需要一集一集下载。

弱智了 我使用web端命令 没配cookie 加了字符串cookie后鉴权就过了。
不能多P的话 看看是不是这个原因 课堂的单P点进去 url是这样的 https://www.bilibili.com/cheese/play/epXXXX
需要从我的课堂进入的 如下url 才能指定分P https://www.bilibili.com/cheese/play/ssXXX
刚命令行测试BBDown https://www.bilibili.com/cheese/play/ssXXX -p xx-xx是可用的

**Comment by HBSpy** [comment]
确实，但是我扫码也成功了，生成了BBDown.data，但data中的内容不太可用，手动替换成了chrome里导出来的cookies内容后正常了
