### ISSUE TITLE
bbdown login 报错 Arg_KeyNotFound

### ISSUE THREAD

**Issue by HandsomeNo2** [nilaoda/BBDown#767]
输入bbdown login出现了二维码，但是又马上出现Arg_KeyNotFound

**Comment by nilaoda** [comment]
使用[Actions](https://github.com/nilaoda/BBDown/actions)版

**Comment by HandsomeNo2** [comment]
使用了Actions版还是有这个问题

**Comment by huruhasusaiko** [comment]
我也是有这个问题，但我换了actions版的就行了
