### ISSUE TITLE
关于使用自建BiliPlus代理之后遇到的鉴权问题

### ISSUE THREAD

**Issue by FarawayBIKON** [nilaoda/BBDown#769]
我使用泰国节点搭建了一个反代国际站的BiliPlus代理，反代配置如下：

        location /intl/gateway/v2/ogv/playurl {
                proxy_pass https://api.biliintl.com;
        }

        location /intl/gateway/v2/app/subtitle {
                proxy_pass https://app.bilibili.tv;
        }

        location /intl/gateway/v2/app/search {
                proxy_pass https://app.bilibili.tv;
        }

        location /intl/gateway/v2/ogv/season/index/result {
                proxy_pass https://api.bilibili.tv;
        }

        location /intl/gateway/ogv/m/view {
                proxy_pass https://api.bilibili.tv;
        }

        location /intl/gateway/ogv/view/app/subtitle {
                proxy_pass https://api.bilibili.tv;
        }

        location /intl/gateway/v2/ogv/view/app/season {
                proxy_pass https://api.bilibili.tv;
        }
  
前期非常顺利，一直来到了获取视频本体的下载链接的时候，被拦住了
![image](https://github.com/nilaoda/BBDown/assets/118461881/e986d707-33e9-44b5-b3e7-6f10fa0789bf)
不清楚到底是哪里有问题，望指点，顺便贴一下配置文件：
![image](https://github.com/nilaoda/BBDown/assets/118461881/f751ae6f-7f51-4874-aee5-5e43eabacc95)

我发现我没有设定--area，然后我设定好之后重试了一下，还是不行

**Comment by FarawayBIKON** [comment]
我尝试手动将链接里的appkey参数删掉，同时关掉配置文件里的--area之后，问题得到了解决。
请问作者大大是否可以在下一个自动构建版本中去掉关于appkey的参数呢？
![image](https://github.com/nilaoda/BBDown/assets/118461881/a230b1f9-fcaa-4fea-8fd0-b46697f75cef)

**Comment by nilaoda** [comment]
使用Actions版本再试

**Comment by FarawayBIKON** [comment]
> 使用Actions版本再试

![image](https://github.com/nilaoda/BBDown/assets/118461881/38ac170c-71af-4774-a1f8-48794fa4b954)
如图，这咋办

**Comment by nilaoda** [comment]
@FarawayBIKON 提供一下返回的json信息

**Comment by FarawayBIKON** [comment]
> @FarawayBIKON 提供一下返回的json信息

https://api.bilibili.tv/intl/gateway/v2/ogv/view/app/season?ep_id=12996116&platform=android&s_locale=zh_SG&mobi_app=bstar_a&access_key=9b9c0859887f36c7ba88eb1df1d0a6b10046

**Comment by FarawayBIKON** [comment]
> @FarawayBIKON 提供一下返回的json信息

https://api.bilibili.tv/intl/gateway/v2/ogv/view/app/season?ep_id=12961523&platform=android&s_locale=zh_SG&mobi_app=bstar_a&access_key=9b9c0859887f36c7ba88eb1df1d0a6b10046

**Comment by FarawayBIKON** [comment]
> @FarawayBIKON 提供一下返回的json信息

看起来要复制之后打开，直接点击会403

**Comment by nilaoda** [comment]
请提供JSON文件内容 我没有代理

**Comment by FarawayBIKON** [comment]
> 请提供JSON文件内容 我没有代理

{"code":0,"message":"success","result":{"season_id":2089932,"alias":"","comment_restriction":"非常抱歉，根据版权方要求，您所在地区不支持查看评论","no_comment":"抱歉，暂无剧集可供评论","title":"香格里拉 边境~粪作猎人向神作游戏发起挑战~","subtitle":"","dynamic_subtitle":"","season_title":"","square_cover":"","refine_cover":"","share_url":"https://www.bilibili.tv/en/play/2089932","share_copy":"","short_link":"https://b23.tv/ss2089932","evaluate":"对着显示器玩游戏已经过时了，现今沉浸式VR游戏才是主流。相较于极少的大作，市面上充斥着大量影像技术优良，系统却完全跟不上的游戏，也就是那些被称作「粪作」的东西。而有一些人（变态），就是喜欢玩这种被一般人嫌弃的「粪作」，阳务乐郎就是其中之一，「粪作猎人」说的就是他。 为了换换口味，阳务乐郎这次向神作「香格里拉边境」发起了进攻，在游戏的过程中，遇见了许多奇特 的冒险，结识了各种各样的伙伴，作品由此展开。","link":"","type":1,"type_name":"动画","mode":2,"status":13,"total":0,"rights":{"copyright":"","allow_bp":0,"area_limit":0,"allow_review":0,"is_preview":0,"allow_bp_rank":0,"can_watch":1,"forbidPre":0,"onlyVipDownload":0},"publish":{"pub_time":"","pub_time_show":"","is_started":0,"is_finish":0,"weekday":0,"release_date_show":"2023/10/01 开播","time_length_show":"更新至7集","unknow_pub_date":0},"detail":"","staff":null,"actor":{"title":"","info":""},"origin_name":"シャングリラ?フロンティア?クソゲーハンター、神ゲーに挑まんとす?（前半）","styles":[{"id":1210,"url":"bstar://pgc/bangumi/index?style_id=1210","name":"冒险"},{"id":11004,"url":"bstar://pgc/bangumi/index?style_id=11004","name":"剧情"},{"id":11011,"url":"bstar://pgc/bangumi/index?style_id=11011","name":"游戏"}],"modules":[{"id":1,"style":"positive","title":"选集","more":"","can_ord_desc":0,"data":{"episodes":[{"aid":2089932,"cid":12960867,"cover":"https://i0.hdslb.com/bfs/intl/management/6c0e38f946f7c3e83f3df7d6ead0ecdb55596bc3.png","id":12960867,"title":"1","long_title":"","status":2,"from":"bangumi","share_url":"https://www.bilibili.tv/en/play/2089932/12960867","dimension":{"width":3840,"height":2160,"rotate":0},"jump":{"op":{"start":172,"start_ms":172173,"end":249,"end_ms":249916},"ed":{"start":0,"start_ms":0,"end":0,"end_ms":0}},"title_display":"第1集","long_title_display":"第1集","subtitles":[{"id":1617629756962,"key":"zh-Hans","title":"中文（简体）","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/a7b214a9229594809f7c4ffc3c8bb6b28c51142d.json?hdnts=exp=1699868710~hmac=88b7d2f68853ee2690b4f4865ea9b4109c4b2ce306b9c30768126c5d1a7588f2","is_machine":false},{"id":1617629755248,"key":"en","title":"English","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/8fd5223fedb7d6dd5e92482d98a840a347afae30.json?hdnts=exp=1699868710~hmac=da72def932ea078dc44e782a66be586a253ae688d0502676f277357e1b6d78fb","is_machine":false},{"id":1617629755189,"key":"th","title":"???????","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/3f8f50be3e31cf809f54b55c41eda55c4506adfa.json?hdnts=exp=1699868710~hmac=4374898b3d0f5ed29e17ebb7ce78897de0598bdcd0ca33def1b28a188a29fae0","is_machine":false},{"id":1617629755188,"key":"id","title":"Bahasa Indonesia","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/6ffcf97baafa1b9e4bd2ef3c091953dc66d79000.json?hdnts=exp=1699868710~hmac=69ff1436971ea7fd5a4b8ae59d962bd020cab2b8e703c482931f152d62207b7c","is_machine":false}]},{"aid":2089932,"cid":12960978,"cover":"https://i0.hdslb.com/bfs/intl/management/ee37f7589d68d294b7927029f95d34970e1d4353.png","id":12960978,"title":"2","long_title":"","status":2,"from":"bangumi","share_url":"https://www.bilibili.tv/en/play/2089932/12960978","dimension":{"width":3840,"height":2160,"rotate":0},"jump":{"op":{"start":70,"start_ms":70071,"end":147,"end_ms":147981},"ed":{"start":1330,"start_ms":1330081,"end":1415,"end_ms":1415165}},"title_display":"第2集","long_title_display":"第2集","subtitles":[{"id":1617629756964,"key":"zh-Hans","title":"中文（简体）","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/eb4c2ec03ef0f5b27097394108abebc55de910f1.json?hdnts=exp=1699868710~hmac=6c14d0e691237426c2d67094d069d8e7ac9273274172941f60700a2924fb0572","is_machine":false},{"id":1617629755801,"key":"en","title":"English","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/899b2521f92556a1dec2cdd641ac8dd69ae56aad.json?hdnts=exp=1699868710~hmac=0f48a77870a89f68106fa8192efc8737cb273bdb802791ba09f54c3c8606f928","is_machine":false},{"id":1617629755829,"key":"th","title":"???????","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/a8ab216d7dce115a42e050788895d557abb34498.json?hdnts=exp=1699868710~hmac=51ae26b77b5b43ce8fe536c76ee595ee28eb6420734655b84cac9fd7aa3bddd4","is_machine":false},{"id":1617629755852,"key":"id","title":"Bahasa Indonesia","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/cdd073a717d3b037516448f069fcdfc226a64e93.json?hdnts=exp=1699868710~hmac=2cc30538f5c6e8f0000093fa7a1364c18907b9a99d3b1033e5554077d244d79f","is_machine":false}]},{"aid":2089932,"cid":12961092,"cover":"https://i0.hdslb.com/bfs/intl/management/abad28ca45424ed564a2bea387cb077eb29b7844.png","id":12961092,"title":"3","long_title":"","status":2,"from":"bangumi","share_url":"https://www.bilibili.tv/en/play/2089932/12961092","dimension":{"width":3840,"height":2160,"rotate":0},"jump":{"op":{"start":12,"start_ms":12013,"end":89,"end_ms":89923},"ed":{"start":1333,"start_ms":1333084,"end":1418,"end_ms":1418168}},"title_display":"第3集","long_title_display":"第3集","subtitles":[{"id":1617629757917,"key":"zh-Hans","title":"中文（简体）","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/e92b7cdaa1fd76c2e33e1dab52f3d3227cfe924b.json?hdnts=exp=1699868710~hmac=1af071abe359679edb3271d17aae7bb6fd88ee0400db082ecf2313b6fc598031","is_machine":false},{"id":1617629757075,"key":"en","title":"English","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/40293df60d6347ce2978d641bc740672c7291426.json?hdnts=exp=1699868710~hmac=b2af0065d935efdb3c5d578f7090c6b9d9effe8f5a0c91a3c2531662ae784336","is_machine":false},{"id":1617629757062,"key":"th","title":"???????","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/6341380ad131a81970b7a21af3fb09c3aca56227.json?hdnts=exp=1699868710~hmac=68b71361537a68285fcce95ff7a11fa6ab896da00c5c5275923be70263d5b95c","is_machine":false},{"id":1617629757076,"key":"id","title":"Bahasa Indonesia","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/546b0f0830eeef03bc0b694eb59641390917febf.json?hdnts=exp=1699868710~hmac=5c1b0317f628a9d067db62b40d5076ff394a154cc991d44f1455fccaa94cf781","is_machine":false}]},{"aid":2089932,"cid":12961225,"cover":"https://i0.hdslb.com/bfs/intl/management/f1f4f4db4802046580216d69b43357d244d3dce1.png","id":12961225,"title":"4","long_title":"","status":2,"from":"bangumi","share_url":"https://www.bilibili.tv/en/play/2089932/12961225","dimension":{"width":3840,"height":2160,"rotate":0},"jump":{"op":{"start":53,"start_ms":53054,"end":130,"end_ms":130797},"ed":{"start":1275,"start_ms":1275067,"end":1360,"end_ms":1360151}},"title_display":"第4集","long_title_display":"第4集","subtitles":[{"id":1617629757918,"key":"zh-Hans","title":"中文（简体）","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/7e6d697a56700c3c074c5404827bcab51552898c.json?hdnts=exp=1699868710~hmac=fedeeda7052f1f0bd4f9c374ab390e84ea02046ec0f8fe7d14f6c5da74cc8105","is_machine":false},{"id":1617629757842,"key":"en","title":"English","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/3eeada6995df1919391a42c5e56ce2065b2165c9.json?hdnts=exp=1699868710~hmac=85a2e4a2a6f8b8fb11d67a8c38536d4a5022ec834e1235124188c991b40df584","is_machine":false},{"id":1617629757836,"key":"th","title":"???????","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/d84cad5663d2fefab8ad09405d1f12f8d1501e75.json?hdnts=exp=1699868710~hmac=ec68b96ae9eda762eea881eaa6f87cfa0a692d896a440b0487f6df597869b731","is_machine":false},{"id":1617629757840,"key":"id","title":"Bahasa Indonesia","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/b03c767e73b18d86b32e85de6140350d62fa72ae.json?hdnts=exp=1699868710~hmac=860d75c95ccfbe0a5c84c9ca8d609def102521e29bb640f546ed608dd164124e","is_machine":false}]},{"aid":2089932,"cid":12961345,"cover":"https://i0.hdslb.com/bfs/intl/management/1e5f675395690396f90ad482579563e6f54fca2b.png","id":12961345,"title":"5","long_title":"","status":2,"from":"bangumi","share_url":"https://www.bilibili.tv/en/play/2089932/12961345","dimension":{"width":3840,"height":2160,"rotate":0},"jump":{"op":{"start":53,"start_ms":53054,"end":130,"end_ms":130964},"ed":{"start":1333,"start_ms":1333084,"end":1418,"end_ms":1418335}},"title_display":"第5集","long_title_display":"第5集","subtitles":[{"id":1617629759538,"key":"zh-Hans","title":"中文（简体）","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/628966380757f1f998be637452f308d5acf722d8.json?hdnts=exp=1699868710~hmac=87db85a70454aac6b1c2bcb5ca8affe3fc27d9a225cea89811b16c8f0ffc870e","is_machine":false},{"id":1617629758560,"key":"en","title":"English","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/a4fea678b08a7dbc53dcbfc8a58100ddbb8246bf.json?hdnts=exp=1699868710~hmac=b51af3c12e8150f8f8aa8812539cc0f78c077746528b097247b4992e7a22a625","is_machine":false},{"id":1617629758555,"key":"th","title":"???????","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/2340dbb6b3505091de14b9b9571ff8e0679ebd47.json?hdnts=exp=1699868710~hmac=ee259a98a02e5e351f5da399ea148089d732f13319cce77ec7fa92d669ca2f3f","is_machine":false},{"id":1617629758559,"key":"id","title":"Bahasa Indonesia","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/410290c13fb9c5b864ca703a74d3732d53821b3d.json?hdnts=exp=1699868710~hmac=22375c0e7ad27362661c053ed414432f3d9706c23a04c9ac43109943076492b3","is_machine":false}]},{"aid":2089932,"cid":12961441,"cover":"https://i0.hdslb.com/bfs/intl/management/e7e8fa24d27b2b174d14b142323aac784b326fae.png","id":12961441,"title":"6","long_title":"","status":2,"from":"bangumi","share_url":"https://www.bilibili.tv/en/play/2089932/12961441","dimension":{"width":3840,"height":2160,"rotate":0},"jump":{"op":{"start":12,"start_ms":12013,"end":89,"end_ms":89923},"ed":{"start":1333,"start_ms":1333084,"end":1418,"end_ms":1418168}},"title_display":"第6集","long_title_display":"第6集","subtitles":[{"id":1617629759168,"key":"zh-Hans","title":"中文（简体）","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/1fc11aab23e3af6f3b535b53f6303bb3e4eadf07.json?hdnts=exp=1699868710~hmac=97b25f7ab1851b68232250f136d03589cf04acac792aded07d1f349934970323","is_machine":false},{"id":1617629759239,"key":"en","title":"English","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/68fa0504586c758cd3c8bbad8fc27b73fa37ace0.json?hdnts=exp=1699868710~hmac=644912883884ea70a2f1f91343a29bf7ca18021f2fa6a1800112b5fd0a3975d0","is_machine":false},{"id":1617629759223,"key":"th","title":"???????","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/f5a509b0c766bf9fb05695961fa700b0f99e9364.json?hdnts=exp=1699868710~hmac=15af706e536544e86b345561ba22a860f263c9450f8041ce40c38c6a0f335011","is_machine":false},{"id":1617629759240,"key":"id","title":"Bahasa Indonesia","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/0badd8c8a3e217cd7c4352b21eaa16712cd28099.json?hdnts=exp=1699868710~hmac=4b8518e7bad383b7b0178a6297d3b4e4a722f65b04eab577e643552995018783","is_machine":false}]},{"aid":2089932,"cid":12961523,"cover":"https://i0.hdslb.com/bfs/intl/management/1e9ea27351254a6d792f9630cfe73f3ffe62d573.png","id":12961523,"title":"7","long_title":"","status":13,"from":"bangumi","share_url":"https://www.bilibili.tv/en/play/2089932/12961523","dimension":{"width":3840,"height":2160,"rotate":0},"jump":{"op":{"start":53,"start_ms":53054,"end":130,"end_ms":130964},"ed":{"start":1239,"start_ms":1239990,"end":1325,"end_ms":1325241}},"title_display":"第7集","long_title_display":"第7集","subtitles":[{"id":1617629760087,"key":"zh-Hans","title":"中文（简体）","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/d32a0f4268fdf7097e856fb5b40e042175655c48.json?hdnts=exp=1699868710~hmac=a1f6c3f3a78e15f99205cca723c51791123d8d5e44cb61dcd3369c3bce3db55f","is_machine":false},{"id":1617629760152,"key":"en","title":"English","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/f844a64dcaf4ceb2a0ca56e24d0dc398c385a059.json?hdnts=exp=1699868710~hmac=ddb124d84bdd4e28eb0b5421e08321e5eb8f20f3f89343c6ece96212aae7f41c","is_machine":false},{"id":1617629760131,"key":"th","title":"???????","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/2b48ea497b7e64e44ba689c88e6aa394b7fc3d37.json?hdnts=exp=1699868710~hmac=05e335d719765a1225987d418521fd0218d14ed84b732cbcb97cc28d8a4c1c12","is_machine":false},{"id":1617629760141,"key":"id","title":"Bahasa Indonesia","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/c47f0ad0ca58553dfa49b878c4ef7a7b3b2307a2.json?hdnts=exp=1699868710~hmac=2f7706962c3e8568aa93574a89d70c32f5e22b7a9032781f4f4f0afc9133f99f","is_machine":false}]}]},"module_style":{"line":0,"hidden":0,"show_pages":null},"partition":20},{"id":2,"style":"section","title":"其他","more":"","can_ord_desc":0,"data":{"id":0,"title":"其他","episodes":[{"aid":2089932,"cid":12963487,"cover":"https://i0.hdslb.com/bfs/intl/management/3ec7fbc91860024b5728a1a4e0001692b15f0aea.png","id":12963487,"title":"PV","long_title":"","status":2,"from":"bangumi","share_url":"https://www.bilibili.tv/en/play/2089932/12963487","dimension":{"width":1280,"height":720,"rotate":0},"jump":null,"title_display":"第PV集","long_title_display":"第PV集","subtitles":[{"id":1617629754076,"key":"en","title":"English","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/9c6b67b9180e1695ce6d74b64832984aa0ad98d3.json?hdnts=exp=1699868710~hmac=8361071e343cac422565b92256e2a5a73cea2e92c24b93ea90c553b0036c8db3","is_machine":false},{"id":1617629753803,"key":"th","title":"???????","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/cd109d9180c4be6c58dccd8dd6d699e17a98ef5d.json?hdnts=exp=1699868710~hmac=aa1ea0956d33f021570003b3558094fd0e811dacb48d99e2cc089d1f932a121e","is_machine":false},{"id":1617629754009,"key":"id","title":"Bahasa Indonesia","url":"https://s-bstarstatic.akamaized.net/ogv/subtitle/846bff2488a871c19b699a90c8e78e08f1e7962e.json?hdnts=exp=1699868710~hmac=5558b1cd4210abaf6fdcd6ae46b70528cf23abd29409d8ce9a7367f01244bbbf","is_machine":false}]}]},"module_style":{"line":0,"hidden":0,"show_pages":null},"partition":0}],"up_info":null,"user_status":{"follow":0,"vip":1,"like_state":0,"demand_no_pay_epids":null},"new_ep":{"id":12961523,"title":"7","new_ep_display":"更新至7集"},"rating":null,"stat":{"favorites":0,"views":2955265,"danmakus":0,"coins":0,"reply":67,"share":0,"hot":0,"play":"","followers":"","series_play":"","likes":24358},"stat_format":{"play":"295.5万播放","likes":"2.4万","share":"","reply":"67"},"cover":"https://i0.hdslb.com/bfs/intl/management/0c1f68c3a6b4b393af750a30ec0d2b95ea75c394.png","horizon_cover":"https://i0.hdslb.com/bfs/intl/management/68e664cd29659a805e4a1858fbf80e1d92fb9a52.png","areas":[{"id":2,"name":"日本"}],"limit":null,"payment":{"pay_mode_display":"会员抢先"},"activity_dialog":null,"login_dialog":null,"update_partten":"每周日 17:00更新","subtitle_suggest_key":"zh-Hans","open_skip_switch":true},"success":true}

**Comment by FarawayBIKON** [comment]
> 请提供JSON文件内容 我没有代理

大佬修的真快，爱你

**Comment by FarawayBIKON** [comment]
> 请提供JSON文件内容 我没有代理

![image](https://github.com/nilaoda/BBDown/assets/118461881/645a5031-6804-4bb9-86d4-85d9943bb34e)
还是同样的JSON内容，这回出现了这些问题（）

**Comment by FarawayBIKON** [comment]
> 请提供JSON文件内容 我没有代理

![image](https://github.com/nilaoda/BBDown/assets/118461881/860500c5-b3c2-4c93-a966-92fe5f392151)
这下又有新问题了，呜呜呜

**Comment by FarawayBIKON** [comment]
> 请提供JSON文件内容 我没有代理

而且我看他获取网页内容的链接，并没有用上我设置的反代域名

**Comment by FarawayBIKON** [comment]
> 请提供JSON文件内容 我没有代理

有一些用上了，有一些没用上

**Comment by FarawayBIKON** [comment]
> 请提供JSON文件内容 我没有代理

大佬再看看我的问题吧，呜呜呜

**Comment by FarawayBIKON** [comment]
> > > 请提供JSON文件内容 我没有代理
> > 
> > 
> > 大佬再看看我的问题吧，呜呜呜
> 
> 使用`curl "https://passport.bilibili.com/web/site/user/info?access_key=******"`检查你的access_key是否正确, 若正确, 返回`{code":0,"data":{"account_info":***,"account_sns":***,"account_other":***}}`, 不正确, 返回`{"message":"user not login","ts":***,"code":-101}`, 还不行换一个`--host`指定的反代服务器, 试试是不是服务器被拉黑了

东南亚的Token也是用这个吗？

**Comment by FarawayBIKON** [comment]
> > > 请提供JSON文件内容 我没有代理
> > 
> > 
> > 大佬再看看我的问题吧，呜呜呜
> 
> 使用`curl "https://passport.bilibili.com/web/site/user/info?access_key=******"`检查你的access_key是否正确, 若正确, 返回`{code":0,"data":{"account_info":***,"account_sns":***,"account_other":***}}`, 不正确, 返回`{"message":"user not login","ts":***,"code":-101}`, 还不行换一个`--host`指定的反代服务器, 试试是不是服务器被拉黑了

我觉得应该不是我Token有问题，因为我在非action版本里使用这个Token是能正常下载视频的

**Comment by FarawayBIKON** [comment]
> > 我觉得应该不是我Token有问题，因为我在非action版本里使用这个Token是能正常下载视频的
> > 直接访问`https://bili.cycity.moe/intl/gateway/v2/ogv/playurl?***`返回以下内容
> 
> ```
> 错误号:412
> 由于触发哔哩哔哩安全风控策略，该次访问请求被拒绝。
> The request was rejected because of the bilibili security control policy.
> ```
> 
> 不是token那可能是服务器ip被b站拉黑了, 试试换一个`--host`的反代服务器

关于这个问题，你看看你的链接参数里是不是有area参数，把这个去掉就正常了

**Comment by FarawayBIKON** [comment]
> > 关于这个问题，你看看你的链接参数里是不是有area参数，把这个去掉就正常了
> 
> 删了`area=th`后发现参数缺了`s_locale=en_us`, 加上即可获取. 但是大部分[公共解析服务器](https://github.com/yujincheng08/BiliRoaming/wiki/%E5%85%AC%E5%85%B1%E8%A7%A3%E6%9E%90%E6%9C%8D%E5%8A%A1%E5%99%A8)需要`area`参数以区分地区, 并不是单纯对host重定向, 删了`area`后 , 如果使用你的服务器, 可能需要的是东南亚账号的cookie而不是token, 因为`-intl`使用的是网页端的api, 你可以尝试fork仓库后apply以下patch
> 
> ```diff
> diff --git a/BBDown.Core/Parser.cs b/BBDown.Core/Parser.cs
> index 214c756..3c07ba2 100644
> --- a/BBDown.Core/Parser.cs
> +++ b/BBDown.Core/Parser.cs
> @@ -90,8 +90,8 @@ namespace BBDown.Core
>              StringBuilder paramBuilder = new();
>              if (Config.TOKEN != "") paramBuilder.Append($"access_key={Config.TOKEN}&");
>              paramBuilder.Append($"aid={aid}");
> -            if (isBiliPlus) paramBuilder.Append($"&appkey=7d089525d3611b1c&area={(Config.AREA == "" ? "th" : Config.AREA)}");
> -            paramBuilder.Append($"&cid={cid}&ep_id={epId}&platform=android&prefer_code_type={code}&qn={qn}");
> +            if (isBiliPlus) paramBuilder.Append("&appkey=7d089525d3611b1c");
> +            paramBuilder.Append($"&cid={cid}&ep_id={epId}&platform=android&prefer_code_type={code}&qn={qn}&s_locale=en_us");
>              if (isBiliPlus) paramBuilder.Append($"&ts={GetTimeStamp(true)}");
>  
>              string param = paramBuilder.ToString();
> ```

感谢大佬，问题得到了解决！另外无论是使用cookie还是token都是没有问题的
