### ISSUE TITLE
报错Error reading JObject from JsonReader. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by byf3332** [nilaoda/BBDown#77]
运行命令
@echo off
BBDown.exe -c "SESSDATA=有大会员的sessdata" -p 2-14 "https://www.bilibili.com/bangumi/play/ss24588/"
pause

在解析第二话时出现如题报错

**Comment by scoltzero** [comment]
同样遇到次问题。望及时回复。谢谢。

**Comment by nilaoda** [comment]
输入全部的cookie，参考https://github.com/nilaoda/BBDown/discussions/87

**Comment by Jerry-informal** [comment]
Error reading JObject from JsonReader. Path '', line 0, position 0. 换了电脑后用dotnet安装出现了相同的问题，之前是手动下载后配置环境变量，不知道是什么原因。

**Comment by byf3332** [comment]
在程序目录下建立BBDown.data, 编辑其内容为“SESSDATA=******”（不包括引号），然后再运行程序试试
或者用login命令登录
