### ISSUE TITLE
登陆报错问题

### ISSUE THREAD

**Issue by yhgzs-111** [nilaoda/BBDown#772]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
GitHub Release版。
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows 10 x64

#### 3. 你使用的完整命令是什么？
```
BBDown login
```
#### 4. 遇到了什么问题？
使用此命令登陆时还没扫码就返回"Arg_KeyNotFound"，中间间隔仅为2秒，尝试在这个报错后扫码登陆仍然不行
#### 5. 运行截图
![image](https://github.com/nilaoda/BBDown/assets/77568569/f7520968-5141-4cfe-8f2b-1202f7289412)

**Comment by yhgzs-111** [comment]
重启了后正常了，没事了

**Comment by yhgzs-111** [comment]
换台电脑后又出现了此问题

**Comment by nilaoda** [comment]
关注新版本发布
