### ISSUE TITLE
您好，部分 URL 无法获取视频信息，提示 NoMatch

### ISSUE THREAD

**Issue by kzwr** [nilaoda/BBDown#773]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
最新的 Actions  版本

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
 .\BBDown.exe  --ffmpeg-path "./ffmpeg.exe" https://www.bilibili.com/video/BV1Kz4y117YZ
```
#### 4. 遇到了什么问题？
无法获取视频信息

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/15187811/0ccb318e-04cd-478d-b080-9462f80a7b93)

**Comment by aantior** [comment]
同样尝试了链接，确实会有提示升级。
![image](https://github.com/nilaoda/BBDown/assets/131586786/a22dc408-5aa7-4e4a-aafd-01030af45575)

**Comment by kzwr** [comment]
已解决，视频版权的区域限制

**Comment by kzwr** [comment]
> 同样尝试了链接，确实会有提示升级。 ![image](https://user-images.githubusercontent.com/131586786/282288612-a22dc408-5aa7-4e4a-aafd-01030af45575.png)

我发现该视频存在版权区域限制 ，不知道是否是该原因导致的错误。

**Comment by nilaoda** [comment]
Actions版本已经修复此问题
