### ISSUE TITLE
使用命令bbdown_command=BBDown --config-file BBDown.config.win --dfn-priority "1080P 高清"却首先下载高码率视频

### ISSUE THREAD

**Issue by aantior** [nilaoda/BBDown#775]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Action [1a2acde](https://github.com/nilaoda/BBDown/commit/1a2acde1e71f2642b97ad3b63ef9ee51bdf34e51)

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
BBDown --config-file BBDown.config.win --dfn-priority "1080P 高清" "https://www.bilibili.com/cheese/play/ep48781?csource=common_myclass_purchasedlecture_null&spm_id_from=333.874.selfDef.mine_paid_list"
```
#### 4. 遇到了什么问题？
使用命令bbdown_command=BBDown --config-file BBDown.config.win --dfn-priority "1080P 高清"却首先下载高码率视频
可以看到下面的截图，有高清视频可以下载，但是却首先选择了高码率

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/131586786/c33b8d5b-5e07-46bd-b644-c461308c6d03)

**Comment by nilaoda** [comment]
请将bat编码修改为ANSI
