### ISSUE TITLE
1.6.1版本无法扫码登录

### ISSUE THREAD

**Issue by ElevenDanRan** [nilaoda/BBDown#782]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.1
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win

#### 3. 你使用的完整命令是什么？

BBDown login

#### 4. 遇到了什么问题？
二维码下方多处一行字：Arg_KeyNotFound
无法扫码登录

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![11210](https://github.com/nilaoda/BBDown/assets/15827063/ad60b349-7495-4cf6-bc4a-ab8d85bedbeb)

**Comment by youshaoXG** [comment]
我遇到了同样的问题，bbdown版本、系统完全一样

**Comment by zuishirenjianliubuzhu** [comment]
我也遇到了这个问题，据说用action版可以解决，但我还不会相关操作。

**Comment by happylittle2010** [comment]
https://github.com/nilaoda/BBDown/actions/runs/6655920743
去这个链接**底部**下载actions版本

**Comment by zuishirenjianliubuzhu** [comment]
感谢，原来是这么下载的。登录没问题了，使用成功！

**Comment by youshaoXG** [comment]
> https://github.com/nilaoda/BBDown/actions/runs/6655920743 去这个链接**底部**下载actions版本

感谢大佬，确实解决了这个问题，actions版本是最新版构建版本吗？还未正式发布的release版？

**Comment by happylittle2010** [comment]
> > https://github.com/nilaoda/BBDown/actions/runs/6655920743 去这个链接**底部**下载actions版本
> 
> 感谢大佬，确实解决了这个问题，actions版本是最新版构建版本吗？还未正式发布的release版？

是集成了一些修复的构建版本，并非发布版，作者说下一个发布版本会集成进这个bug修复

**Comment by yuyanghua** [comment]
链接底部下载actions版本都失效了Expired，还有其他办法吗

**Comment by happylittle2010** [comment]
> 链接底部下载actions版本都失效了Expired，还有其他办法吗

换一个actions下载

**Comment by yuyanghua** [comment]
非常感谢
















在 2024-01-29 16:50:35，"happylittle" ***@***.***> 写道：

链接底部下载actions版本都失效了Expired，还有其他办法吗

换一个actions下载

**Comment by firetail-zhy** [comment]
> > 链接底部下载actions版本都失效了Expired，还有其他办法吗
> 
> 换一个actions下载

现在全是过期的
