### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by Richardjjjj** [nilaoda/BBDown#788]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Release 

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
BBDown login
```
#### 4. 遇到了什么问题？
Arg_KeyNotFound

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。![Snipaste_2023-11-29_13-43-54](https://github.com/nilaoda/BBDown/assets/21980080/4c4e8336-cb1c-4395-84c3-e5b5c187eb91)

**Comment by bysdxt** [comment]
不能登录+1，一样的提示，有时候能拿到二维码，但几秒后也提示Arg_KeyNotFound然后退出了

**Comment by jdy159753** [comment]
用Actions版本可以登录，但是下载会员视频，现在只能下试看版本，不知道什么问题

**Comment by PlantCase** [comment]
web端登录失效了，但tv端没有问题 。

**Comment by le1239-ch** [comment]
BBDown.data 文件文件在哪里呢？

**Comment by bysdxt** [comment]
> BBDown.data 文件文件在哪里呢？

就在 BBDown.exe 所在的文件夹里，如果没有，自己新建就好

**Comment by draftman9** [comment]
> 打开浏览器的F12控制台，然后访问 https://api.bilibili.com/x/space/v2/myinfo 这个链接，然后在请求中找到 Cookie，复制到 BBDown.data 文件里面就可以了

你是怎么复制的，chrome没办法复制Cookie。

**Comment by jdy159753** [comment]
> > > 打开浏览器的F12控制台，然后访问 https://api.bilibili.com/x/space/v2/myinfo 这个链接，然后在请求中找到 Cookie，复制到 BBDown.data 文件里面就可以了
> > 
> > 
> > 你是怎么复制的，chrome没办法复制Cookie。
> 
> 复制这一块的内容
> 
> <img alt="image" width="1082" src="https://private-user-images.githubusercontent.com/84970296/287642497-5e61fbb9-8c88-4f6e-ae3a-d94373df7c9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODQ1MjUsIm5iZiI6MTcwMTY4NDIyNSwicGF0aCI6Ii84NDk3MDI5Ni8yODc2NDI0OTctNWU2MWZiYjktOGM4OC00ZjZlLWFlM2EtZDk0MzczZGY3YzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEwMDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NWM5OWRiZjk1ZjZjMDVlZjQ5ZjVmMzc3ODljMGViNDYzNzBkNmRlMWY1NjYyMjhkZjM5YjRhNGM1MDQ0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gkIRV9TgmubUVBVldQVnYo_-DoAE44xIEdGei8h1AuI">
您好，用本地Cookie我可以用1.6.1的版本登录了，不过还是下载不了会员内容，这是什么问题啊

**Comment by XingYueY** [comment]
其实关于改BBDown.data文件，如果之前登过不换号，只需要获取cookie中的SESSDATA和bilibili_jct这两项的值，粘贴到文件里对应位置就可以了。

data文件内的文本格式为：
`DedeUserID=xxxxx;DedeUserID__ckMd5=xxxxx;Expires=15551000;SESSDATA=xxxxx;bili_jct=xxxxx;gourl=https%253A%252F%252Fwww.bilibili.com%252F`
其中的`xxxxx`需要根据自己的cookie替换。

**Comment by Richardjjjj** [comment]
重新下载了最新版本，问题已解决

**Comment by M3R8L3RUN** [comment]
作者你应该升级一下了
