### ISSUE TITLE
怎么下载AI字幕

### ISSUE THREAD

**Issue by daoyuchuan** [nilaoda/BBDown#791]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
BBDown 版本1.6.1

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
windows 10系统

不知道怎么下载AI字幕？

**Comment by dodorz** [comment]
是啊，参数中有个`--skip-ai`，说是`跳过AI字幕下载(默认开启)`，那么不开启（不跳过）是什么参数呢？不解。

**Comment by LinEvil** [comment]
`--skip-ai=false`

**Comment by hanc44** [comment]
> `--skip-ai=false`

这个不行呀

**Comment by GaryNotGay** [comment]
> > `--skip-ai=false`
> 
> 这个不行呀

--skip-ai=false --sub-only 搭配使用可以下载单独的字幕文件

**Comment by Aqua256** [comment]
可以的，你将`--skip-ai=false`放到配置文件里就不需要每次下载都写这个
