### ISSUE TITLE
Mac (ARM) 登陆失败

### ISSUE THREAD

**Issue by qinmz** [nilaoda/BBDown#793]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Mac

#### 3. 你使用的完整命令是什么？
```
./BBDown login 
```
#### 4. 遇到了什么问题？
Arg_KeyNotFound  , 会出现二维码，但是没过几秒就是出现Arg_KeyNotFound
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。

**Comment by qinmz** [comment]
已经解决

**Comment by M3R8L3RUN** [comment]
yes i fixed!!!
