### ISSUE TITLE
充电专属只能下载480p的吗？设置优先级也没有用

### ISSUE THREAD

**Issue by smj123456** [nilaoda/BBDown#795]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.1

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。
win
#### 3. 你使用的完整命令是什么？
BBDown.exe BV1494y1V7Vx -tv -q "4K 超清"

#### 4. 遇到了什么问题？
充电专属视频只能下载480p

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by smj123456** [comment]
好像是看视频，有些可以下载1080p，有些就只能下载480p

**Comment by arexepan12345** [comment]
试了几个都是480有一个能下1080求指教

**Comment by specked2527** [comment]
你对UP充电了吗

**Comment by Tommytangmi** [comment]
不到一周前还能下，现在不知道为什么不行了，显示解析失败

**Comment by liuruidong4** [comment]
> 不到一周前还能下，现在不知道为什么不行了，显示解析失败

处理了呗

**Comment by Tommytangmi** [comment]
> > 不到一周前还能下，现在不知道为什么不行了，显示解析失败
> 
> 处理了呗

可惜了
