### ISSUE TITLE
tv模式无法解析4K

### ISSUE THREAD

**Issue by kimifetch** [nilaoda/BBDown#796]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.1 Release和Actions都试了

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win11

#### 3. 你使用的完整命令是什么？
```
BBDown --use-tv-api --encoding-priority hevc --use-aria2c BV1Pu4y1r7eT
```
#### 4. 遇到了什么问题？
tv模式无法解析4K，同一个视频以前是可以解析的。且登录云视听小电视查看，该视频是有4K的。

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![289234279-5596dbb1-cfe8-46a8-9537-5a2c04b4c792](https://github.com/nilaoda/BBDown/assets/5071649/7210a5ad-b25a-4758-886b-1ba1c2c217dd)

**Comment by specked2527** [comment]
你开大会员了吗？为啥一定要用-tv 其他接口呢？

**Comment by kevinlai2009** [comment]
有大会员兼电视大会员，出现楼主一样情况，现在-tv只能解析到1080P视频流
用-tv是为了下载无水印视频
两个月前用-tv是可以正常解析并下载4K无水印视频的

**Comment by niu541412** [comment]
同无法解析TV版的4K

**Comment by kimifetch** [comment]
> 同无法解析TV版的4K。 已经有人修复。#802 测试可用。

编译试了下，确实可以了。
