### ISSUE TITLE
无法白嫖下载b站充电视频

### ISSUE THREAD

**Issue by SamSAM-WWW** [nilaoda/BBDown#799]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
。。。release最新版

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。win

#### 3. 你使用的完整命令是什么？
``` BBDown.exe BVhao -tv
BBDown ...
```
#### 4. 遇到了什么问题？
无法白嫖下载b站充电视频，我看网上说这个被b站修了555

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by specked2527** [comment]
到底谁说可以免费下载充电视频的？不认识中文是吧??

**Comment by maxhuangping** [comment]
刚去试了一下确实不能下了，反正我都之前都下完了：）

**Comment by aqaqaqs** [comment]
。。。

**Comment by aqaqaqs** [comment]
我要是早发现就好了
