### ISSUE TITLE
视频合并失败

### ISSUE THREAD

**Issue by ljodan** [nilaoda/BBDown#80]
The file '/home/ljz/Desktop/797299458/797299458.P001.240089729.m4a' already exists.
无法合并视音频，

**Comment by ljodan** [comment]
开始一个任务后，下载视音频后，就提示音频已经存在，感觉没有调用或者调用ffmpeg失败一样，是软件被和谐了吗

**Comment by RyanL-29** [comment]
你的命令行參數可以分享出來嗎?

**Comment by daihxu** [comment]
这种问题就不用麻烦作者了
1.1 删除原下载.m4a和.mp4，选择 次一个清晰度或者音频文件下载一下，基本就合并正常了。
2.1 使用FFmpeg工具手动合一下即可。
      2.0.1 以79637573为例，合并 音视频文件如下：
     ffmpeg -i 79637573.P1.136294450.mp4 -i 79637573.P1.136294450.m4a -vcodec copy -acodec copy output.mp4
      2.0.2 合并视频封面文件如下：
      ffmpeg -i 79637573.mp4 -i 79637573.jpg -map 0 -map 1 -c copy -c:v:1 png -disposition:v:1 attached_pic 79637573_output.mp4
