### ISSUE TITLE
无法使用web登录

### ISSUE THREAD

**Issue by Hti-0683** [nilaoda/BBDown#808]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Release v1.6.1

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows 10 版本22H2（操作系统内部版本19045.3803）

#### 3. 你使用的完整命令是什么？
```
.\BBDown.exe --debug login
```
#### 4. 遇到了什么问题？
登录时程序报错“**Arg_KeyNotFound**”，随后自动退出，导致无法正常登录

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![图片](https://github.com/nilaoda/BBDown/assets/66823771/8cb92cad-ec54-4958-b0e2-3081e93007ac)

**Comment by Hti-0683** [comment]
对了，今天使用时突然提示“**你尚未登录B站账号**”我才尝试重新登录，但是出现了上面的问题
之前一直登着账号也没出现过这个提示

**Comment by MUskby** [comment]
原来不止我有问题，我以为我的网有问题了

**Comment by caomeiguojiang** [comment]
Release v1.6.1版本很久都不能扫码登录了 用Actions版本

**Comment by dfinity-web3** [comment]
> Release v1.6.1版本很久都不能扫码登录了 用Actions版本

actions版本，怎么使用呢？有没有说明？

**Comment by MUskby** [comment]
> Release v1.6.1版本很久都不能扫码登录了 用Actions版本

我用action版本也会这样，只是登录没有问题了，下载还是不行，呃
