### ISSUE TITLE
bbdown 无法登录B站账号

### ISSUE THREAD

**Issue by ShrekCharles716** [nilaoda/BBDown#809]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Release BBDown-1.6.0

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win10ltsc

#### 3. 你使用的完整命令是什么？
```
D:\soft\BBDown-1.6.0-x64>bbdown ep791312
BBDown version 1.6.0, Bilibili Downloader.
欢迎到讨论区交流：
https://github.com/nilaoda/BBDown/discussions

[2023-12-28 18:54:41.916] - 检测账号登录...
[2023-12-28 18:54:41.917] - 你尚未登录B站账号, 解析可能受到限制
[2023-12-28 18:54:41.918] - 获取aid...
[2023-12-28 18:54:41.918] - 获取aid结束: ep:791312
[2023-12-28 18:54:41.918] - 获取视频信息...
[2023-12-28 18:54:42.050] - 视频标题: 葬送的芙莉莲
[2023-12-28 18:54:42.051] - 发布时间: 2023-10-24 20:00:00
[2023-12-28 18:54:42.051] - P1: [1339446971] [1 冒险的结束] [00m00s]
[2023-12-28 18:54:42.051] - P2: [1339446381] [2 也不一定要是魔法…] [00m00s]
[2023-12-28 18:54:42.052] - P3: [1355131682] [3 杀人魔法] [00m00s]
[2023-12-28 18:54:42.052] - P4: [1339447305] [4 灵魂安眠之地] [00m00s]
[2023-12-28 18:54:42.052] - P5: [1339446394] [5 死者的幻影] [00m00s]
[2023-12-28 18:54:42.052] - ......
[2023-12-28 18:54:42.052] - P13: [1381584510] [13 同类厌恶] [00m00s]
[2023-12-28 18:54:42.052] - 程序已自动选择你输入的集数, 如果要下载其他集数请自行指定分P(如可使用-p ALL代表全部)
[2023-12-28 18:54:42.053] - 共计 13 个分P, 已选择：13
[2023-12-28 18:54:42.053] - 开始解析P13...
[2023-12-28 18:54:42.175] - 下载封面...
[2023-12-28 18:54:44.073] - 共计1条流(共有1个分段).
                            0. [480P 清晰] [AVC] [~496 kbps] [10.90 MB]
[2023-12-28 18:54:44.075] - 开始多线程下载P13视频, 片段(1/1)...
[2023-12-28 18:54:56.272] - 合并视频分片...
[2023-12-28 18:54:56.273] - 清理分片...
[2023-12-28 18:54:56.279] - 下载P13完毕
[2023-12-28 18:54:56.279] - 开始合并分段...
[2023-12-28 18:54:56.280] - 开始混流视频...
[2023-12-28 18:54:56.560] - 清理临时文件...
[2023-12-28 18:54:56.769] - 任务完成

D:\soft\BBDown-1.6.0-x64>
```
#### 4. 遇到了什么问题？
无法登录B站账号，下载番剧已有13集只能下载第一集，并且只能下载前3分钟
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/112491914/0908bbab-931c-4aa5-bcb2-4e58c4c431d6)
![image](https://github.com/nilaoda/BBDown/assets/112491914/26e78d1f-7604-4071-939d-549634f2df6e)

**Comment by specked2527** [comment]
你 为什要用旧版 😅

**Comment by ShrekCharles716** [comment]
> 你 为什要用旧版 😅

z最初用的是1.6.1，发现不能登录，以为是新版的bug便换成老版试试看，依然不能登录才发的issue

**Comment by specked2527** [comment]
去使用actions版

**Comment by Cody-Travers** [comment]
我也登录不上去，失败提示和你的一样，不过不影响下载。

**Comment by swordzsx123** [comment]
> 去使用行动版

请教下，怎么下载Actions版本

**Comment by specked2527** [comment]
> > 去使用行动版
> 
> 请教下，怎么下载Actions版本

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

**Comment by Cody-Travers** [comment]
已解决，下载actions版本可正常登录。

**Comment by BeastSenpai1919810** [comment]
> > > 去使用行动版
> > 
> > 
> > 请教下，怎么下载Actions版本
> 
> https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

希望这种急躁的老哥少一点，不是所有人都会整天泡在github
Actions选项卡里面，选择最新的workflow。拉到最底部，才能找到编译好的版本

**Comment by yinxing123456** [comment]
![图片1](https://github.com/nilaoda/BBDown/assets/156333466/902eec2c-87d9-49e1-b714-7d4b86e30b43)
扫码成功了还是登不上啊

**Comment by BenjaminLN** [comment]
> > > > 去使用行动版
> > > 
> > > 
> > > 请教下，怎么下载Actions版本
> > 
> > 
> > https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
> 
> 希望这种急躁的老哥少一点，不是所有人都会整天泡在github
> 
> 首先要登录，**不登陆看不到编译的行动版** Actions选项卡里面，选择最新的workflow。拉到最底部，才能找到编译好的版本

我确实被他优越到了😅

**Comment by IotaHydrae** [comment]
> > > > > 去使用行动版
> > > > 
> > > > 
> > > > 请教下，怎么下载Actions版本
> > > 
> > > 
> > > https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md
> > 
> > 
> > 希望这种急躁的老哥少一点，不是所有人都会整天泡在github
> > 首先要登录，**不登陆看不到编译的行动版** Actions选项卡里面，选择最新的workflow。拉到最底部，才能找到编译好的版本
> 
> 我确实被他优越到了😅

畜生一样的东西

**Comment by nilaoda** [comment]
请关注新版本发布

**Comment by LazaruX512** [comment]
> 请关注新版本发布

请问，能发布正式版吗？
行动版不方便未登录的用户下载

**Comment by nilaoda** [comment]
> > 请关注新版本发布
> 
> 请问，能发布正式版吗？ 行动版不方便未登录的用户下载

已发布

**Comment by Cody-Travers** [comment]
> > > 请关注新版本发布
> > 
> > 
> > 请问，能发布正式版吗？ 行动版不方便未登录的用户下载
> 
> 已发布

大佬，新版本我这边还是无法二维码登录，大佬有时间可以看下麻烦了

**Comment by Cody-Travers** [comment]
> > > 请关注新版本发布
> > 
> > 
> > 请问，能发布正式版吗？ 行动版不方便未登录的用户下载
> 
> 已发布

大佬，新版本1.6.2
![bbdown](https://github.com/nilaoda/BBDown/assets/139093182/b7b280a1-5cf8-43e7-91b8-807312c851eb)
我这边还是无法二维码登录，大佬有时间可以看下麻烦了

**Comment by LazaruX512** [comment]
> > > > 请关注新版本发布
> > > 
> > > 
> > > 请问，能发布正式版吗？ 行动版不方便未登录的用户下载
> > 
> > 
> > 已发布
> 
> 大佬，新版本1.6.2 ![bbdown](https://private-user-images.githubusercontent.com/139093182/329906879-b7b280a1-5cf8-43e7-91b8-807312c851eb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODYyMDcsIm5iZiI6MTcxNTU4NTkwNywicGF0aCI6Ii8xMzkwOTMxODIvMzI5OTA2ODc5LWI3YjI4MGExLTVjZjgtNDNlNy05MWI4LTgwNzMxMmM4NTFlYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNzM4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjRkYWY5MmRlYjUyMmI4NjA0NjhhYzY5YmFmNWEyODcyY2JiMmM5YWY4MDEwZjRjMDk2NTNjMDg1MmUzMjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jTzPKJYamwH2DO7wMVfrlkVaFRK_vlGPnlueHN_xdxw) 我这边还是无法二维码登录，大佬有时间可以看下麻烦了

你的命令是错误的
请直接输入`BBDown login`

**Comment by Cody-Travers** [comment]
> > > > > 请关注新版本发布
> > > > 
> > > > 
> > > > 请问，能发布正式版吗？ 行动版不方便未登录的用户下载
> > > 
> > > 
> > > 已发布
> > 
> > 
> > 大佬，新版本1.6.2 ![bbdown](https://private-user-images.githubusercontent.com/139093182/329906879-b7b280a1-5cf8-43e7-91b8-807312c851eb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODYyMDcsIm5iZiI6MTcxNTU4NTkwNywicGF0aCI6Ii8xMzkwOTMxODIvMzI5OTA2ODc5LWI3YjI4MGExLTVjZjgtNDNlNy05MWI4LTgwNzMxMmM4NTFlYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNzM4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjRkYWY5MmRlYjUyMmI4NjA0NjhhYzY5YmFmNWEyODcyY2JiMmM5YWY4MDEwZjRjMDk2NTNjMDg1MmUzMjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jTzPKJYamwH2DO7wMVfrlkVaFRK_vlGPnlueHN_xdxw) 我这边还是无法二维码登录，大佬有时间可以看下麻烦了
> 
> 你的命令是错误的 请直接输入`BBDown login`

谢谢大佬解答，给您添麻烦了
