### ISSUE TITLE
部分链接无法正确被提取解析，需手动复制BV号

### ISSUE THREAD

**Issue by abandonstudy** [nilaoda/BBDown#811]
BBdown版本：actions中的最新版本（#187）
OS版本：Windows11
命令：bbdown https://www.bilibili.com/festival/genshin2023?bvid=BV1P24y1a7Lt&spm_id_from=333.337.search-card.all.click
报错

[2023-12-30 14:35:33.672] - 加载本地cookie...
[2023-12-30 14:35:33.836] - 检测账号登录...
[2023-12-30 14:35:33.836] - 获取aid...
Arg_KeyNotFound
请尝试升级到最新版本后重试!
'spm_id_from' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
![image](https://github.com/nilaoda/BBDown/assets/94209629/2d5dfff2-478c-4df5-a4b8-2ed2a1405b6d)

手动提取BV号并执行bbdown BV1P24y1a7Lt可以正常下载

**Comment by specked2527** [comment]
**这个不是程序的问题**  你可以使用https://greasyfork.org/zh-CN/scripts/393995-bilibili-干净链接

**Comment by bysdxt** [comment]
你命令行里有 & 字符，这个会被 cmd 识别成 命令串联，要想是当成参数的一部分传递，要用双引号，
例如 bbdown "https://........&spm_id...." 这样
