### ISSUE TITLE
番剧仅能解析到480P清晰度，无法取得1080P

### ISSUE THREAD

**Issue by wifi-left** [nilaoda/BBDown#812]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
最近的Actions版本（Commit Hash为：1196918e709f883eabfe3122ccad824b8f551381）
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win11
#### 3. 你使用的完整命令是什么？
```
bbdown ss29325 -q 116 -ia
```
#### 4. 遇到了什么问题？
无法下载1080p
已经登陆，并且其他视频可以获得1080p

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
```
[2023-12-31 15:54:13.782] - 加载本地cookie...
[2023-12-31 15:54:13.906] - 检测账号登录...
[2023-12-31 15:54:13.906] - 获取aid...
[2023-12-31 15:54:14.001] - 获取aid结束: ep:307247
[2023-12-31 15:54:14.001] - 获取视频信息...
[2023-12-31 15:54:14.100] - 视频标题: 某科学的超电磁炮T
[2023-12-31 15:54:14.101] - 发布时间: 2020-01-11 00:05:00 +08:00
[2023-12-31 15:54:14.101] - P1: [143589043] [1 LEVEL5超能力者] [00m00s]
[2023-12-31 15:54:14.101] - P2: [144089354] [2 大霸星祭] [00m00s]
[2023-12-31 15:54:14.101] - P3: [145105889] [3 气球猎人] [00m00s]
[2023-12-31 15:54:14.101] - P4: [146872367] [4 篡改] [00m00s]
[2023-12-31 15:54:14.101] - P5: [149347233] [5 信赖] [00m00s]
[2023-12-31 15:54:14.101] - ......
[2023-12-31 15:54:14.101] - P25: [238907859] [25 我重要的朋友] [00m00s]
[2023-12-31 15:54:14.101] - 程序已自动选择你输入的集数, 如果要下载其他集数请自行指定分P(如可使用-p ALL代表全部)
[2023-12-31 15:54:14.101] - 共计 25 个分P, 已选择：1
[2023-12-31 15:54:14.101] - 开始解析P1: 82846771... (1 of 1)
[2023-12-31 15:54:14.429] - 共计6条视频流.
                            0. [480P 清晰] [852x480] [AVC] [24.390] [571 kbps] [~96.77 MB]
                            1. [480P 清晰] [852x480] [AV1] [23.976] [293 kbps] [~49.99 MB]
                            2. [480P 清晰] [852x480] [HEVC] [23.810] [236 kbps] [~39.99 MB]
                            3. [360P 流畅] [640x360] [AVC] [24.390] [352 kbps] [~59.67 MB]
                            4. [360P 流畅] [640x360] [AV1] [23.976] [205 kbps] [~35.03 MB]
                            5. [360P 流畅] [640x360] [HEVC] [23.810] [157 kbps] [~26.72 MB]
[2023-12-31 15:54:14.430] - 共计3条音频流.
                            0. [M4A] [323 kbps] [~55.99 MB]
                            1. [M4A] [134 kbps] [~23.23 MB]
                            2. [M4A] [68 kbps] [~11.79 MB]
[2023-12-31 15:54:14.430] - 请选择一条视频流(输入序号):
```

**Comment by wifi-left** [comment]
经过测试，API访问：
```
https://api.bilibili.com/x/player/playurl?bvid=BV1BJ411H7dF&cid=143589043&fnval=1168&fourk=1&qn=80
```
带上Cookie后是可以获取到1080P的
![image](https://github.com/nilaoda/BBDown/assets/63381531/d0575cf8-cf80-4b2b-bafb-47d165f3449a)

**Comment by wifi-left** [comment]
顺带一提，其他视频是可以获取到1080p
![image](https://github.com/nilaoda/BBDown/assets/63381531/a4ccec3c-9020-4434-8439-15c559f583ec)

**Comment by yosandev** [comment]
同样得问题，ep打头的剧是没有1080，BV号可以

**Comment by timk-lalala** [comment]
同

**Comment by mengyvleihen** [comment]
我这里也是番剧只有480p，其它视频一切正常。

**Comment by bysdxt** [comment]
我可以，用 -info 可以获得1080P
![a](https://github.com/nilaoda/BBDown/assets/13766766/61e74560-1fd4-4869-a450-e66900fa2633)
![b](https://github.com/nilaoda/BBDown/assets/13766766/f6df88be-05bc-4e94-b6a7-48c2afea3c52)

**Comment by yosandev** [comment]
> 我可以，用 -info 可以获得1080P ![a](https://private-user-images.githubusercontent.com/13766766/297108431-61e74560-1fd4-4869-a450-e66900fa2633.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTM2ODQsIm5iZiI6MTcwNTQ5MzM4NCwicGF0aCI6Ii8xMzc2Njc2Ni8yOTcxMDg0MzEtNjFlNzQ1NjAtMWZkNC00ODY5LWE0NTAtZTY2OTAwZmEyNjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEyMDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkY2Q0YzU2NTNmY2Y4M2Y3MzRmNjZmZGU4MmRkNmM0NjgwYmQ4Zjg2OTBmOWQxOGQ4MTUxYWM4NTNjMWMyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tWvs4M3iGkKA9MFbeRE4e-jlwjMlMzsuXlR9JkYOSq4) ![b](https://private-user-images.githubusercontent.com/13766766/297108441-f6df88be-05bc-4e94-b6a7-48c2afea3c52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTM2ODQsIm5iZiI6MTcwNTQ5MzM4NCwicGF0aCI6Ii8xMzc2Njc2Ni8yOTcxMDg0NDEtZjZkZjg4YmUtMDViYy00ZTk0LWI2YTctNDhjMmFmZWEzYzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEyMDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMjBlMWE4MTc2MWRmNGU0ZTk0ODIwNjMyYWM0ZjNiNzJiNjRlYTA4NTRhNjNjOTc3NTk4NzI1NjU4NTE4OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h9nUXE4Gqu602gB5sPuMnQPlDkaVgPiqxFeVxEPT9Fc)

可以告知下全命令和exe版本吗

**Comment by wifi-left** [comment]
![image](https://github.com/nilaoda/BBDown/assets/63381531/6dfaaa5f-e3f3-47bb-8bff-3660466eaa7c)

**Comment by bysdxt** [comment]
@wifi-left 
神奇了，试下bbdown重新登录？我现在都是每次都手动到浏览器复制cookie到bbdown.data的，也试试？
![a](https://github.com/nilaoda/BBDown/assets/13766766/667a7124-57f5-4d67-9454-89c12202f5a5)

**Comment by donaghyXu** [comment]
这个问题有解决办法了么
