### ISSUE TITLE
如何才能使下载的视频不包含封面图

### ISSUE THREAD

**Issue by cnnbdb** [nilaoda/BBDown#813]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.1

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win10 64位

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
下载的视频都有封面图 导致多P合成时会提示stream 0, timescale not set 网上查询发现是加了视频封面导致合成的视频只有封面与音频
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![微信截图_20240103162907](https://github.com/nilaoda/BBDown/assets/154965202/95e8e672-4c9c-44ea-b90b-715e27f91ec0)

**Comment by cnnbdb** [comment]
补充：当我在下载时 临时的数字文件夹内 会有一个数字JPG文件生成 把这个封面图片删除时 下载的视频就不会有封面图了 希望能把封面图不下载下来加载进去的功能 谢谢

**Comment by cnnbdb** [comment]
已解决 发现help有skip cover 功能

**Comment by tianyiyuna** [comment]
> 已解决 发现help有skip cover 功能

这个功能是怎么用的
