### ISSUE TITLE
奇怪，不能下载字幕，到底要怎么才能下字幕呢？  BBDown.exe https://www.bilibili.com/video/BV18g4y1U7zR -tv

### ISSUE THREAD

**Issue by bk111** [nilaoda/BBDown#817]
奇怪，不能下载字幕，到底要怎么才能下字幕呢？  BBDown.exe https://www.bilibili.com/video/BV18g4y1U7zR -tv

**Comment by specked2527** [comment]
https://lug.ustc.edu.cn/wiki/doc/smart-questions/

**Comment by bysdxt** [comment]
试下 --sub-only 单独下载字幕？
