### ISSUE TITLE
奇怪现象：没登录可以拉取1080p视频流

### ISSUE THREAD

**Issue by abandonstudy** [nilaoda/BBDown#820]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Actions 1196918

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows 11 22631.3007

#### 3. 你使用的完整命令是什么？
```
bbdown --debug -p 1 https://www.bilibili.com/video/BV17D4y1t74j/
```
#### 4. 遇到了什么问题？
一个奇怪的现象，没登录可以拉取1080p视频流

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
https://github.com/nilaoda/BBDown/assets/94209629/44c3e0ab-f614-4ccc-930a-f193794639c6

日志
[debug_20240120142442560.json](https://github.com/nilaoda/BBDown/files/13996970/debug_20240120142442560.json)

**Comment by cnnbdb** [comment]
有啥奇怪的 看版妆本更新说明 接口变更

**Comment by cnnbdb** [comment]
1.5.9就可以了
