### ISSUE TITLE
部分番剧不带上-tv参数只能拿到480p的流

### ISSUE THREAD

**Issue by abandonstudy** [nilaoda/BBDown#822]
version: action 1196918	OS: windows 10

问题结论
视频皆正常，番剧使用网页端(不带-tv)参数时时，只能获取480p的视频，但是电脑浏览器网页端可以正常观看1080p。番剧带上-tv后正常，无水印1080p
命令

验证过程
只有BBDown.data，番剧
bbdown -tv https://www.bilibili.com/bangumi/play/ss46089 -p 1-2   能正常获取1080p的无水印流
bbdown https://www.bilibili.com/bangumi/play/ss46089 -p 1-2   只能获取有水印480p的流

只有BBDown.data，视频
bbdown -tv https://www.bilibili.com/video/BV1fe411H7z4/ 正常获取1080p无水印的流
bbdown https://www.bilibili.com/video/BV1fe411H7z4/      正常获取1080p有水印的流

存在BBDown.data 和 BBDownTV.data  视频
bbdown https://www.bilibili.com/video/BV1fe411H7z4/ 正常获取1080p有水印的流
bbdown -tv https://www.bilibili.com/video/BV1fe411H7z4/ 正常获取1080p无水印的流

存在BBDown.data 和 BBDownTV.data  番剧
bbdown https://www.bilibili.com/bangumi/play/ep779777 -p 1-2 只能获取480p有水印的流
bbdown -tv https://www.bilibili.com/bangumi/play/ep779777 -p 1-2 正常获取1080p无水印的流

**Comment by specked2527** [comment]
老问题了，一直没修，你可以使用其他工具下载

**Comment by donaghyXu** [comment]
我也碰到了，以前可以获取4K的流，现在最高只能480了

**Comment by git-070** [comment]
**刚刚试了下如下这个，是可以下载1080P的。
具体操作：一是要获取登录cookie。二是加上参数--encoding-priority av1,hevc,avc。av1,hevc,avc这三者可以自行调整顺序，程序是从左往右排，如果没有AV1视频，就会下HEVC，如果这两个都没有就会下AVC**
`bbdown https://www.bilibili.com/bangumi/play/ss46089 -p 1-2 只能获取有水印480p的流`

**Comment by HOO-AH** [comment]
> **刚刚试了下如下这个，是可以下载1080P的。 具体操作：一是要获取登录cookie。二是加上参数--encoding-priority av1,hevc,avc。av1,hevc,avc这三者可以自行调整顺序，程序是从左往右排，如果没有AV1视频，就会下HEVC，如果这两个都没有就会下AVC** `bbdown https://www.bilibili.com/bangumi/play/ss46089 -p 1-2 只能获取有水印480p的流`

请问怎么操作呢。我的理解是 ，重新login登录后就会自动更新cookie了吧，还需要手动写入配置文件吗？第二个，这个参数是在有的选的时候才有用吧，480p这种情况就是只能解析到一条流，没有别的可选了

**Comment by git-070** [comment]
加载Cookie了就不只480P了。附件是我做好的批处理程序，每次下载只需将视频地址复制到【视频path.txt】中，另外Cookie输入在【bilibili_cookie.txt】中(cookie一般不会变动，此操作不会太频繁)，之后运行【下载B站视频-【调用：视频path.txt】.bat】即可。

Cookie的SESSDATA值，可以在浏览器中，按F12打开开发工具去查看，嫌麻烦那就在【Microsoft Edge 扩展商店】搜索安装【Cookie获取器】或【Cookie与UserAgent获取】，均可以轻松获取到SESSDATA值。

[下载B站视频-【调用：视频path.txt】.zip](https://github.com/nilaoda/BBDown/files/14802526/B.-.path.txt.zip)

**Comment by git-070** [comment]
> > **刚刚试了下如下这个，是可以下载1080P的。具体操作：一是要获取登录cookie。二是加上参数--encoding-priority av1，hevc，avc。av1，hevc，avc这三者可以自行调整顺序，程序是从左往右排，如果没有AV1视频，就会下HEVC，如果这两个都没有就会下AVC** `bbdown https://www.bilibili.com/bangumi/play/ss46089 -p 1-2 只能获取有水印480p的流`
> 
> 请问怎么操作呢。我的理解是 ，重新登录登录后就会自动更新cookie了吧，还需要手动写入配置文件吗？第二个，这个参数是在有的选的时候才有用吧，480p这种情况就是只能解析到一条流，没有别的可选了

**上一楼已回复，并提供了批处理程序，和使用说明。**

**Comment by HOO-AH** [comment]
> 加载Cookie了就不只480P了。附件是我做好的批处理程序，每次下载只需将视频地址复制到【视频path.txt】中，另外Cookie输入在【bilibili_cookie.txt】中(cookie一般不会变动，此操作不会太频繁)，之后运行【下载B站视频-【调用：视频path.txt】.bat】即可。
> 
> Cookie的SESSDATA值，可以在浏览器中，按F12打开开发工具去查看，嫌麻烦那就在【Microsoft Edge 扩展商店】搜索安装【Cookie获取器】或【Cookie与UserAgent获取】，均可以轻松获取到SESSDATA值。
> 
> [下载B站视频-【调用：视频path.txt】.zip](https://github.com/nilaoda/BBDown/files/14802526/B.-.path.txt.zip)

感谢你提供的程序，使用你的程序发现确实可以获取到1080P或更高清晰度的多个视频流。
通过与你的文件对比排查，导致之前问题的原因还是在cookie的sessdata值。然而我使用BBDown login后返回的sessdata仍然不行，后来发现使用网页获取到的sessdata就可以了。我觉得最有效快捷的方式是使用浏览器扩展获取sessdata值，这里推荐edge扩展“Cookie-Editor”，在BBDown或 .cogfig里使用这个扩展获取到的sessdata值就可以解决问题了（-c   SESSDATA=*******）。（当然，需要BBDown login）
↓Cookie-Editor扩展截图
![PixPin_2024-03-31_21-44-07](https://github.com/nilaoda/BBDown/assets/164996495/c552d4e1-0c8b-4a20-89bd-e8db1ca4e5ed)
以上就是我使用的方法，供大家参考。
最后，再次感谢你的回复和程序。

**Comment by git-070** [comment]
> > 加载Cookie了就不只480P了。附件是我做好的批处理程序，每次下载只需将视频地址复制到【视频path.txt】中，另外Cookie输入在【bilibili_cookie.txt】中（cookie一般不会变动，此操作不会太频繁），之后运行【下载B站视频-【调用：视频path.txt】.bat】即可。
> > Cookie的SESSDATA值，可以在浏览器中，按F12打开开发工具去查看，嫌麻烦那就在【Microsoft Edge 扩展商店】搜索安装【Cookie获取器】或【Cookie与UserAgent获取】，均可以轻松获取到SESSDATA值。
> > [下载B站视频-【调用：视频path.txt】.zip](https://github.com/nilaoda/BBDown/files/14802526/B.-.path.txt.zip)
> 
> 感谢你提供的程序，使用你的程序发现确实可以获取到1080P或更高清晰度的多个视频流。 通过与你的文件对比排查，导致之前问题的原因还是在cookie的sessdata值。然而，我使用BBDown login后返回的sessdata仍然不行，后来发现使用网页获取到的sessdata就可以了。我觉得最有效快捷的方式是使用浏览器扩展获取sessdata值，这里推荐edge扩展“Cookie-Editor”，在BBDown或 .cogfig里使用这个扩展获取到的sessdata值就可以解决问题了（-c SESSDATA=*******）。（当然，需要BBDown login） ↓Cookie-Editor扩展截图 ![PixPin_2024-03-31_21-44-07](https://private-user-images.githubusercontent.com/164996495/318273415-c552d4e1-0c8b-4a20-89bd-e8db1ca4e5ed.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTM3NTYsIm5iZiI6MTcxMTg5MzQ1NiwicGF0aCI6Ii8xNjQ5OTY0OTUvMzE4MjczNDE1LWM1NTJkNGUxLTBjOGItNGEyMC04OWJkLWU4ZGIxY2E0ZTVlZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxMzU3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGY1MjdjNDc3MWFjODU1NjU4NmRhNzUxNGQ5NWM1Y2ZhZDNiYTViMTc3MTA0MDRlOWNkMWM0NDExNDM2N2I1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.00AQZzlEFVBne_txar-nLQkFQ9JauVL7ydeLa46DDKY) 以上就是我使用的方法，供大家参考。 最后，再次感谢你的回复和程序。

**解决了就好。**
获取Cookie的SESSDATA值，你说的edge扩展“Cookie-Editor”，确实比我上面推荐的两款要好些，可以直接获取SESSDATA值，上面两款还必须手动从一大堆数据中筛选出来。谢谢分享！
**可惜BBDown作者不更新了，要是像如下 bilix、yt-dlp这样，程序可以直接获取到就更好了。**
bilix  -fb edge 
yt-dlp.exe --cookies-from-browser edge
**打算找找看有没有获取Cookie信息的命令行工具，批处理直接调用，到时就不用再手动操作。**

**Comment by Matsuubayashii** [comment]
找到sessdate后 怎么用 可以给张图吗  谢谢

**Comment by HOO-AH** [comment]
> 找到sessdate后 怎么用 可以给张图吗 谢谢

把复制的sessdata写到配置文件里就行了。或者命令行里面自己写这个参数和sessdata值。
![Clip_2024-05-18_19-47-36](https://github.com/nilaoda/BBDown/assets/164996495/9ed0b4f9-40c8-4fbf-92ae-7669c3d47a90)

**Comment by Matsuubayashii** [comment]
哎😑 我开了tv会员 迎刃而解 难绷啊
ps：非常感谢！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: HOO-AH ***@***.***>
发送时间: Saturday, May 18, 2024 7:51:07 PM
收件人: nilaoda/BBDown ***@***.***>
抄送: Matsuubayashii ***@***.***>; Manual ***@***.***>
主题: Re: [nilaoda/BBDown] 部分番剧不带上-tv参数只能拿到480p的流 (Issue #822)


找到sessdate后 怎么用 可以给张图吗 谢谢

把复制的sessdata写到配置文件里就行了。或者命令行里面自己写这个参数和sessdata值。
Clip_2024-05-18_19-47-36.png (view on web)<https://github.com/nilaoda/BBDown/assets/164996495/9ed0b4f9-40c8-4fbf-92ae-7669c3d47a90>
