### ISSUE TITLE
你好Python可以调用吗？？？？？？？？？？？？？？？

### ISSUE THREAD

**Issue by szxchj** [nilaoda/BBDown#824]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
。。。

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
xxx

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by szxchj** [comment]
你好Python可以调用bbdown吗？？？？？？？？？？？？？？

**Comment by specked2527** [comment]
你为何不尝试之后 再提问

**Comment by xiexie2001** [comment]
可以。你可以直接调用执行系统命令的语句，比如
```
os.system('BBDown '+URL_Path)
```
