### ISSUE TITLE
login时输出二维码后提示Arg_KeyNotFound

### ISSUE THREAD

**Issue by ksblkcjy** [nilaoda/BBDown#826]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.1_20230818 release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win

#### 3. 你使用的完整命令是什么？
```
BBDown login
```
#### 4. 遇到了什么问题？
输出二维码后提示Arg_KeyNotFound

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
<img width="685" alt="Snipaste_2024-01-26_23-46-20" src="https://github.com/nilaoda/BBDown/assets/65875161/104810ec-86fc-458a-b42c-597f937412c0">

**Comment by LynxCatTheThird** [comment]
臣附议。同时发现cookie失效，可能是叔叔改了登陆策略。

**Comment by TaylorAndTony** [comment]
同报错 Arg_KeyNotFound，无法登陆，版本 1.6.1

**Comment by MUskby** [comment]
使用最新的actions版本吧，基本能保证可以打开，把之前的登录信息文件，生成的缓存文件什么的都删了

**Comment by LynxCatTheThird** [comment]
> linux 下如何整，没搞过

如果是 Arch 系的，可以执行：
``` shell
paru -Rs bbdown-bin
paru -S bbdown-git --removemake
```

如果不是，那就删掉所有残余文件，按照第一次安装走一遍。

**Comment by turbochoo** [comment]
> > linux 下如何整，没搞过
> 
> 如果是 Arch 系的，可以执行：
> 
> ```shell
> paru -Rs bbdown-bin
> paru -S bbdown-git --removemake
> ```
> 
> 如果不是，那就删掉所有残余文件，按照第一次安装走一遍。

哈哈，我以为要自己搭建配置环境，我用yay -S bbdown-git 即可，之前装的bin版本

**Comment by turbochoo** [comment]
> > > linux 下如何整，没搞过
> > 
> > 
> > 如果是 Arch 系的，可以执行：
> > ```shell
> > paru -Rs bbdown-bin
> > paru -S bbdown-git --removemake
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果不是，那就删掉所有残余文件，按照第一次安装走一遍。
> 
> 哈哈，我以为要自己搭建配置环境，我用yay -S bbdown-git 即可，之前装的bin版本

谢谢 兄弟

**Comment by X-funbean** [comment]
> 使用最新的actions版本吧，基本能保证可以打开，把之前的登录信息文件，生成的缓存文件什么的都删了

请问win下应该怎么整呀

**Comment by Tinyu-Zhao** [comment]
+1

**Comment by Jax-Yang** [comment]
### 解决办法：（自己试出来的，已解决）
1. 用编辑器修改 BBDown.data 文件，文件内容实际是登录之后获取的登录信息，用于识别用户是否登录，更新其中 `bili_jct `与`SESSDATA `这两项的值就行了
2. 值去已经登录的浏览器里，直接看 Cookie 找这两项即可

其他的：
DedeUserID 每个用户固定的
DedeUserID__ckMd5 每个用户固定的
gourl 固定的
Expires 删了也没事

如果没有  BBDown.data  文件，自己创建一个就行了，内容包括
DedeUserID=;DedeUserID__ckMd5=;Expires=;SESSDATA=;bili_jct=;gourl=

@X-funbean @Tinyu-Zhao @TaylorAndTony

**Comment by X-funbean** [comment]
> > 使用最新的actions版本吧，基本能保证可以打开，把之前的登录信息文件，生成的缓存文件什么的都删了
> 
> 请问win下应该怎么整呀

参考https://github.com/nilaoda/BBDown/issues/809#issuecomment-1876699078 下载actions版本
感谢 @BeastSenpai1919810

**Comment by Jax-Yang** [comment]
<img width="397" alt="image" src="https://github.com/nilaoda/BBDown/assets/36981616/32199654-e02e-4d4a-8233-26a81ad263c8">
windows 下载最后一个即可 [BBDown_win-x64](https://github.com/nilaoda/BBDown/actions/runs/6851227729/artifacts/1046205618) 解压缩之后就是 exe 程序 @Tinyu-Zhao @TaylorAndTony

**Comment by TaylorAndTony** [comment]
> <img alt="image" width="397" src="https://private-user-images.githubusercontent.com/36981616/300831885-32199654-e02e-4d4a-8233-26a81ad263c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODcwMTgsIm5iZiI6MTcwNjc4NjcxOCwicGF0aCI6Ii8zNjk4MTYxNi8zMDA4MzE4ODUtMzIxOTk2NTQtZTAyZS00ZDRhLTgyMzMtMjZhODFhZDI2M2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDExMjUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNGZjN2I3OGQyOTM1ZjBkNjhiODEyOWY1MDljMWE0MzRjZDg2MTYwYWFlOTNjZGRiN2FlYmI1N2FkNjY3ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tmn9eboRP0yZQtMKamk7lx8nqVC09jTW5Zfa02K7ni8"> windows 下载最后一个即可 [BBDown_win-x64](https://github.com/nilaoda/BBDown/actions/runs/6851227729/artifacts/1046205618) 解压缩之后就是 exe 程序 @Tinyu-Zhao @TaylorAndTony

感谢，换用 action 版本后正常

**Comment by grandzzr** [comment]
解决的最新文件也过期了

**Comment by spyps** [comment]
我也出现了这个问题，解决方法是拷贝旧电脑上的BBdown验证文件到新电脑上。

action版本显示expired，是我的下载方法不对吗？

**Comment by jyeric** [comment]
> 我也出现了这个问题，解决方法是拷贝旧电脑上的BBdown验证文件到新电脑上。
> 
> action版本显示expired，是我的下载方法不对吗？

只需fork一下再actions重新构建即可。artifact有3个月的有效期。
懒得构建可以直接从我这里下载 https://github.com/jyeric/BBDown/actions/runs/7883215503

**Comment by CaTM1Int** [comment]
我这里也是出现了这个问题，但是是在解析视频的时候出现的，并且发现只要把bv号转换成av号就能够正常解析。
![Snipaste_2024-02-13_20-50-05](https://github.com/nilaoda/BBDown/assets/110894944/5314ef56-8458-49de-8b79-6c91e96bfe40)

**Comment by 025896** [comment]
> 使用最新的actions版本吧，基本能保证可以打开，把之前的登录信息文件，生成的缓存文件什么的都删了

过期了
