### ISSUE TITLE
Arg_KeyNotFound

### ISSUE THREAD

**Issue by cloudy-sfu** [nilaoda/BBDown#830]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Release 1.6.1

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows 10 64-bit

#### 3. 你使用的完整命令是什么？
```
BBDown.exe https://www.bilibili.com/video/BV1y7421K7Jv
```
#### 4. 遇到了什么问题？

Arg_KeyNotFound

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）

注：操作系统地区设置非中国，命令行字符集 ASCII ，问号处为无法显示的中文字符（视频标题等），内容与运行逻辑无关。

![image](https://github.com/nilaoda/BBDown/assets/41314224/b08abf82-e483-4eaf-bad0-fcd8e1ddc216)

**Comment by timwuyue** [comment]
> avid计算错误, 使用action版
> 
> duplicated #828


使用action版

不会构建action版，能不能分享一下，感谢

**Comment by tzys** [comment]
从昨天开始，所有视频都提示这个Arg_KeyNotFound了 。

**Comment by benpicho** [comment]
action版文件显示过期，能不能分享一下，感谢
