### ISSUE TITLE
bilibili最新上传的短剧全集解密不了，所以也下载不了

### ISSUE THREAD

**Issue by rufan321** [nilaoda/BBDown#833]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）

[BBDown v1.6.1](https://github.com/nilaoda/BBDown/releases/tag/1.6.1)

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win7
#### 3. 你使用的完整命令是什么？
```
BBDown+bilibili地址
```
#### 4. 遇到了什么问题？
bilibili最新上传的短剧全集解密不了，所以也下载不了

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
显示解密不了

**Comment by rufan321** [comment]
![快照1](https://github.com/nilaoda/BBDown/assets/67855066/0a7937e5-803d-4399-91a0-575d020de25c)
https://www.bilibili.com/video/BV1BC411s78W/?spm_id_from=333.337.search-card.all.click&vd_source=041c2ddd814c3a0d3acc79ab7f40c95c

**Comment by specked2527** [comment]
> ![快照1](https://private-user-images.githubusercontent.com/67855066/304016979-0a7937e5-803d-4399-91a0-575d020de25c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDUxMTMsIm5iZiI6MTcwNzc0NDgxMywicGF0aCI6Ii82Nzg1NTA2Ni8zMDQwMTY5NzktMGE3OTM3ZTUtODAzZC00Mzk5LTkxYTAtNTc1ZDAyMGRlMjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEzMzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYjBkZGQxOGMwOThiZTAyZTlhZjM5ZDRmYzlkZjdjMjlkNTdiMGU0OWE3ODg0ZTZjYTY5ODA0ZGY5NDg4ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cdi4nnh2Z78ZuAisA_9pDOs7UMoxEvbQcfIVJpkZm9g) https://www.bilibili.com/video/BV1BC411s78W/?spm_id_from=333.337.search-card.all.click&vd_source=041c2ddd814c3a0d3acc79ab7f40c95c

1你没登入 2“地址”要加”“

**Comment by spyps** [comment]
我拿稳定版下动新新上传的BV1FJ4m1b7Aa，也是这个提示；其他视频能正常下载。

我这里看action版本显示expired，是我的下载方法不对吗？

**Comment by rufan321** [comment]
> > ![快照1](https://private-user-images.githubusercontent.com/67855066/304016979-0a7937e5-803d-4399-91a0-575d020de25c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDUxMTMsIm5iZiI6MTcwNzc0NDgxMywicGF0aCI6Ii82Nzg1NTA2Ni8zMDQwMTY5NzktMGE3OTM3ZTUtODAzZC00Mzk5LTkxYTAtNTc1ZDAyMGRlMjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEzMzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYjBkZGQxOGMwOThiZTAyZTlhZjM5ZDRmYzlkZjdjMjlkNTdiMGU0OWE3ODg0ZTZjYTY5ODA0ZGY5NDg4ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cdi4nnh2Z78ZuAisA_9pDOs7UMoxEvbQcfIVJpkZm9g) https://www.bilibili.com/video/BV1BC411s78W/?spm_id_from=333.337.search-card.all.click&vd_source=041c2ddd814c3a0d3acc79ab7f40c95c
> 
> 1你没登入 2“地址”要加”“

一直以为都不用1和2，都能直接1080P
