### ISSUE TITLE
[BV号解析aid为负数] • 解析 2024-2-4 之后的视频报错：Arg_KeyNotFound

### ISSUE THREAD

**Issue by yuhang0000** [nilaoda/BBDown#836]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Release v1.6.1.0

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win11 22H2 22621.3007 x86_64
#### 3. 你使用的完整命令是什么？
```
BBDown <BV号>
```
#### 4. 遇到了什么问题？
解析2024-2-4之后的视频报错：Arg_KeyNotFound
具体是BV号转aid时为负数，请求更新BV号解析aid算法

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![屏幕截图 2024-02-15 063708](https://github.com/nilaoda/BBDown/assets/104742794/c8734221-40c8-4ee2-bfec-624fcc44fae6)
![屏幕截图 2024-02-15 063927](https://github.com/nilaoda/BBDown/assets/104742794/72a2a0f6-8b59-4332-8c73-cac6a4a87c74)

**Comment by specked2527** [comment]
去用Actions 版

**Comment by xolyn** [comment]
> 去用Actions 版

在哪里下呢 我看都是expired
