### ISSUE TITLE
网页端登录失败

### ISSUE THREAD

**Issue by VMwareEFI** [nilaoda/BBDown#838]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
。。。
release 1.6.1
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。
Windows 10 1903
#### 3. 你使用的完整命令是什么？
```
BBDown login
```
#### 4. 遇到了什么问题？
xxx
输入命令后直接报错（来不及扫描）
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。
![image](https://github.com/nilaoda/BBDown/assets/109196429/9495bf51-ef98-4e7b-a6c7-5bf02661fa2e)

**Comment by bysdxt** [comment]
用Actions版。
不过好像过期下不了。
我是自己拉源码编译的。

**Comment by bysdxt** [comment]
用Actions版。
不过好像过期下不了。
我是自己拉源码编译的。

**Comment by qingchunnh** [comment]
自己克隆仓库运行自动构建就好了

**Comment by cynosureabu** [comment]
但我是mac要怎么构建。。

**Comment by dreamchonghua** [comment]
> 用Actions版。 不过好像过期下不了。 我是自己拉源码编译的。

可以分享一下吗，谢谢

**Comment by VMwareEFI** [comment]
> 自己克隆仓库运行自动构建就好了

是用C++编译吗

**Comment by qingchunnh** [comment]
> > 自己克隆仓库运行自动构建就好了
> 
> 是用C++编译吗

点Build Latest有个运行

**Comment by dreamchonghua** [comment]
> > > 自己克隆仓库运行自动搭建就好了
> > 
> > 
> > 是用C++编译吗
> 
> 点构建最新的一个运行

不会，哈哈，求教
