### ISSUE TITLE
登录时候也返回 Arg_KeyNotFound

### ISSUE THREAD

**Issue by cynosureabu** [nilaoda/BBDown#840]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6。1

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Linux/Mac

#### 3. 你使用的完整命令是什么？
```
BBDown login
```
#### 4. 遇到了什么问题？
 Arg_KeyNotFound

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

看别人说要用action里面的版本，但好像都过期了。。

**Comment by dreamchonghua** [comment]
我也不会弄，好烦啊

**Comment by cynosureabu** [comment]
copy过来一下
"只需fork一下再actions重新构建即可。artifact有3个月的有效期。
懒得构建可以直接从我这里下载 https://github.com/jyeric/BBDown/actions/runs/7883215503“

**Comment by BAIYUCGUAN** [comment]
怎么下载啊

**Comment by yinqinghe** [comment]
![image](https://github.com/nilaoda/BBDown/assets/70678389/58609d76-e1aa-48fc-9729-abfa5c9badde)

**Comment by honekoneke** [comment]
感谢热心老哥帮忙构建指路，记得登陆github不然下不了…

**Comment by resetn** [comment]
老哥，我还是找不到下载链接，求指路

**Comment by ashantiedemanniuz46** [comment]
> copy过来一下 "只需fork一下再actions重新构建即可。artifact有3个月的有效期。 懒得构建可以直接从我这里下载 [https://github.com/jyeric/BBDown/actions/runs/7883215503“](https://github.com/jyeric/BBDown/actions/runs/7883215503%E2%80%9C)

謝謝你，蒙古人！:)

**Comment by yren110** [comment]
还是不会用啊。下载后提升和我系统不匹配。无法打开。

**Comment by Chocooooo** [comment]
感谢

**Comment by Jacky5863** [comment]
> ![image](https://private-user-images.githubusercontent.com/70678389/306192217-58609d76-e1aa-48fc-9729-abfa5c9badde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMTA4ODcsIm5iZiI6MTcxNzIxMDU4NywicGF0aCI6Ii83MDY3ODM4OS8zMDYxOTIyMTctNTg2MDlkNzYtZTFhYS00OGZjLTk3MjktYWJmYTVjOWJhZGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDAyNTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZjJkOGUxZGViMDgwNjgzNGRlNGQzNDBjZDFhMWQzNmY2ZjgxY2IwMzc1M2ZkMzgxZmFkMzIzYzUyOGRmZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hYh8YAbFFMMIvR9FK_hsdnembohyrEtTQsGpi9oIOjY)

好像下载不了了
![image](https://github.com/nilaoda/BBDown/assets/116953000/7e88f216-58c7-4d42-87af-326ed5fcfb3f)
