### ISSUE TITLE
关于扫码显示失效，并随即出现Arg_KeyNotFound的问题

### ISSUE THREAD

**Issue by xiaoxuhuicode** [nilaoda/BBDown#841]
![image](https://github.com/nilaoda/BBDown/assets/64527312/fe4a0dd3-60af-4433-a1ae-d5ee6f6e90e8)

**Comment by xiaoxuhuicode** [comment]
这里下载 [https://github.com/jyeric/BBDown/actions/runs/7883215503“](https://github.com/jyeric/BBDown/actions/runs/7883215503%E2%80%9C)

**Comment by xiaoxuhuicode** [comment]
![image](https://github.com/nilaoda/BBDown/assets/64527312/97149ed0-0484-4560-ad35-e66d9dd9e2a5)
但是又会出现一个问题，水印还是没有去掉
![image](https://github.com/nilaoda/BBDown/assets/64527312/f12e2848-68bb-4037-8017-d9722acd20d8)

**Comment by wutuyandiao** [comment]
好厉害，帮助我解决了问题

**Comment by RallyQ** [comment]
> ![image](https://private-user-images.githubusercontent.com/64527312/306265479-97149ed0-0484-4560-ad35-e66d9dd9e2a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDIxNTUsIm5iZiI6MTcxMTk0MTg1NSwicGF0aCI6Ii82NDUyNzMxMi8zMDYyNjU0NzktOTcxNDllZDAtMDQ4NC00NTYwLWFkMzUtZTY2ZDlkZDllMmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAzMjQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOTJiNmZmMThlNGM3ZDdhNzFjMzM0M2E3YjVjYjE4NTA0NDcxZjZmZmE4YjRiMjkzZTQxYmQ5MDEyY2U3NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6bThSJuKDJ4sD3pdfApkX6ZuyjfPuw04qqEcxetsvis) 但是又会出现一个问题，水印还是没有去掉 ![image](https://private-user-images.githubusercontent.com/64527312/306265394-f12e2848-68bb-4037-8017-d9722acd20d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDIxNTUsIm5iZiI6MTcxMTk0MTg1NSwicGF0aCI6Ii82NDUyNzMxMi8zMDYyNjUzOTQtZjEyZTI4NDgtNjhiYi00MDM3LTgwMTctZDk3MjJhY2QyMGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAzMjQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NGIzODM3MzE0YTNjMGMwODU2MmRjNTI4MGM2NDJmYWQ0ZThlYjJkOGYyMjBhYzk5MzhmY2MyNGIyZGY4Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.acOj75duuljzxeXz4qvnqlmeaHHaQGjInFAzsScXAbo)

这个软件下载的bili视频一直都有水印啊，哪个版本的没有水印？
