### ISSUE TITLE
关于现在的版本，水印不能正常去掉的问题

### ISSUE THREAD

**Issue by xiaoxuhuicode** [nilaoda/BBDown#842]
![image](https://github.com/nilaoda/BBDown/assets/64527312/34f09c48-ff1b-499a-a3d4-ae57c80860b9)

![image](https://github.com/nilaoda/BBDown/assets/64527312/33a238bd-e48a-4d2d-8967-59e2e74ab365)

![image](https://github.com/nilaoda/BBDown/assets/64527312/4c7e0954-f577-4c20-9b3c-38ebe613b6de)

**Comment by fasdhjadf** [comment]
走tv接口，有些视频可以去水印，有些不行。

**Comment by 86lonewolf** [comment]
可以去水印，但不知道为什么最高只有1080p

**Comment by xiaoxuhuicode** [comment]
我的这些操作有问题吗


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月21日(周三) 上午10:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nilaoda/BBDown] 关于现在的版本，水印不能正常去掉的问题 (Issue #842)




 
可以去水印，但不知道为什么最高只有1080p
 
&mdash;

**Comment by Geckoc** [comment]
确实，我试了，去水印，有些可以，有些试了很多次都不行，走普通接口和tv接口都不行

**Comment by Aqua256** [comment]
软件没有去水印功能 只能原样下载，单纯是up主上传的时候平台不同，那时候就没加上水印。
