### ISSUE TITLE
会解析出负的aid

### ISSUE THREAD

**Issue by FFDVDGD** [nilaoda/BBDown#845]
我知道这个issue已经存在，但是现在所有的action都过期，没有可以下载的版本，因此请求一个新action

**Comment by TTfield** [comment]
![20240308013243](https://github.com/nilaoda/BBDown/assets/64184139/6f15fdd2-6516-4751-9c17-6bc72bb6af5e)
手动改成av号可以正常下载

**Comment by fqyjames** [comment]
如何fork一份代码？？

**Comment by nilaoda** [comment]
请关注新版本发布
