### ISSUE TITLE
在Action过期的情况下下载Action版下载流程

### ISSUE THREAD

**Issue by My-Responsitories** [nilaoda/BBDown#846]
1. 打开 [forks](https://github.com/nilaoda/BBDown/forks?include=active%2Cinactive&page=1&period=6mo&sort_by=last_updated)
2. 找一个最近的有actions的fork
3. 按以前下载action的方法下载

#845 #838 #837 #836

**Comment by lkcozy** [comment]
https://github.com/huanghongbook/BBDown/actions/runs/7999770367

**Comment by resetn** [comment]
您好，有适合小白的教程嘛

**Comment by aidemeiyan** [comment]
这个fork下载的包，登录依然提示Arg_KeyNotFound  https://github.com/nilaoda/BBDown/issues/846#issuecomment-1960761670

**Comment by beeky86** [comment]
@aidemeiyan   我昨天下载的这个可以用，今天又不行了提示Arg_KeyNotFound

**Comment by lkcozy** [comment]
> 这个fork下载的包，登录依然提示Arg_KeyNotFound [#846 (comment)](https://github.com/nilaoda/BBDown/issues/846#issuecomment-1960761670)

可能跟要下载的视频有关系，我使用原版下载一些视频也没有出现这个错误。另外，方便透露一下视频地址吗？我可以尝试下载看看是否能成功。

**Comment by eenlhuoc** [comment]
> 1. 打开 [forks](https://github.com/nilaoda/BBDown/forks?include=active%2Cinactive&page=1&period=6mo&sort_by=last_updated)
> 
>     2. 找一个最近的有actions的fork
> 
>     3. 按以前下载action的方法下载
> 
> 
> #845 #838 #837 #836

这些fork，是单纯的分个流？
还是对N大 Action#187 之后的问题做了改进的？

**Comment by 895127276** [comment]
@lkcozy 解决了

**Comment by FPzxhub** [comment]
可以试试我的https://github.com/FPzxhub/BBDown_plus/actions/runs/8223270690/artifacts/1312998946

**Comment by bluesiboy** [comment]
dotnet解决方案很简单的，直接下载个sdk,克隆项目， dotnet build 编译就行了。

**Comment by longzhigao** [comment]
> 可以试试我的https://github.com/FPzxhub/BBDown_plus/actions/runs/8223270690/artifacts/1312998946

失效了

**Comment by resetn** [comment]
可以给一个自己action的教程嘛，或者认识该功能的文章，谢谢佬

> 1. 打开 [forks](https://github.com/nilaoda/BBDown/forks?include=active%2Cinactive&page=1&period=6mo&sort_by=last_updated)
> 2. 找一个最近的有actions的fork
> 3. 按以前下载action的方法下载
> 
> #845 #838 #837 #836

**Comment by nilaoda** [comment]
本仓库Actions已恢复
