### ISSUE TITLE
希望能新增 -avc, --only-avc 參數

### ISSUE THREAD

**Issue by CurtisJamesgh** [nilaoda/BBDown#85]
老機器只能軟解HEVC, 跑起來還是比較吃力..

目前嘗試的方案, 是修改源碼 BBDownParser.cs

100   // if (hevc && v.codecs == "AVC") continue;
101   if (v.codecs == "HEVC") continue;          

326   // if (hevc && v.codecs == "AVC") { }

雖然成功地過濾掉HEVC, 但是編譯出來的執行檔比原本的大了不少
( 36.7MB 對比 26.1MB, 使用的指令是
  dotnet publish
  -r win-x64
  -p:PublishSingleFile=true
  -p:PublishTrimmed=true
  --self-contained true )

而且無法使用本地cookie
( 讀取不到BBDown.data, 只能用
  BBDown -c "cookie" "url" 來處理 error: (412) )

所以希望能新增 -avc 只下載AVC編碼, 造福我們這些老機器的用戶：）

**Comment by Maple2001** [comment]
+1 痛点是部分iPadOS的画中画解不了HEVC

**Comment by nilaoda** [comment]
[1.4.0](https://github.com/nilaoda/BBDown/releases/tag/1.4.0) 中已经增加
