### ISSUE TITLE
最新测试构建版本登录时依然提示“Arg_KeyNotFound”

### ISSUE THREAD

**Issue by aidemeiyan** [nilaoda/BBDown#851]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
测试构建版本 (https://github.com/nilaoda/BBDown/actions)
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
linux-x64版本 (https://github.com/nilaoda/BBDown/actions)
#### 3. 你使用的完整命令是什么？
BBDown login
#### 4. 遇到了什么问题？
最新测试构建版本登录时依然提示“Arg_KeyNotFound”

**Comment by laosunmaker** [comment]
同样的问题，想问问有人有解决方案了吗

**Comment by monobo1989** [comment]
同样的问题，想问问有人有解决方案了吗

**Comment by ChristmasCC** [comment]
同样的问题，想问问有人有解决方案了吗

**Comment by 13RTK** [comment]
The same problem, I encounter when using the tool downloaded from the release
![image](https://github.com/nilaoda/BBDown/assets/63441399/67ea0057-169f-4903-bb93-ec1f4f97edd2)

**Comment by lbcake** [comment]
> #### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
> 测试构建版本 (https://github.com/nilaoda/BBDown/actions)
> 
> #### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
> linux-x64版本 (https://github.com/nilaoda/BBDown/actions)
> 
> #### 3. 你使用的完整命令是什么？
> BBDown login
> 
> #### 4. 遇到了什么问题？
> 最新测试构建版本登录时依然提示“Arg_KeyNotFound”

没看到 nilaoda 歇了吗！ 短期不会任何修复 +上网冲浪维护

**Comment by Kyouichirou** [comment]
![2024-03-02 15 44 46](https://github.com/nilaoda/BBDown/assets/64763483/2990b567-4fc4-42d6-a536-79fa33d160e2)

**Comment by donaghyXu** [comment]
> > #### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
> > 测试构建版本 (https://github.com/nilaoda/BBDown/actions)
> > #### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
> > linux-x64版本 (https://github.com/nilaoda/BBDown/actions)
> > #### 3. 你使用的完整命令是什么？
> > BBDown login
> > #### 4. 遇到了什么问题？
> > 最新测试构建版本登录时依然提示“Arg_KeyNotFound”
> 
> 没看到 nilaoda 歇了吗！ 短期不会任何修复 +上网冲浪维护

歇了的消息在哪看哒

**Comment by CyberXiaoZheng** [comment]
https://github.com/jyeric/BBDown/actions/runs/7883215503/artifacts/1240726625
先去actions下载一个老版本的BBDown.exe，然后正常登录，得到cookie，把文件放到和ffmpeg和最新的BBdown一起，然后就可以去下载了

**Comment by Anza7i** [comment]
Chrome在b站抓到的cookie拷到BBDown.data文件里，目前似乎可行

**Comment by NingTory** [comment]
> https://github.com/jyeric/BBDown/actions/runs/7883215503/artifacts/1240726625 先去actions下载一个老版本的BBDown.exe，然后正常登录，得到cookie，把文件放到和ffmpeg和最新的BBdown一起，然后就可以去下载了

想请问一下哪个老版的BBDown可以得到cookie，这个教程方便分析吗，我邮箱843826630@qq.com

**Comment by xxgddd** [comment]
> > https://github.com/jyeric/BBDown/actions/runs/7883215503/artifacts/1240726625 先去actions下载一个老版本的BBDown.exe，然后正常登录，得到cookie，把文件放到和ffmpeg和最新的BBdown一起，然后就可以去下载了
> 
> 想请问一下哪个老版的BBDown可以得到cookie，这个教程方便分析吗，我邮箱[843826630@qq.com](mailto:843826630@qq.com)

你好我也是不太会这个，请问你成功了吗？

**Comment by CyberXiaoZheng** [comment]
> > > https://github.com/jyeric/BBDown/actions/runs/7883215503/artifacts/1240726625 先去actions下载一个老版本的BBDown.exe，然后正常登录，得到cookie，把文件放到和ffmpeg和最新的BBdown一起，然后就可以去下载了
> > 
> > 
> > 想请问一下哪个老版的BBDown可以得到cookie，这个教程方便分析吗，我邮箱[843826630@qq.com](mailto:843826630@qq.com)
> 
> 你好我也是不太会这个，请问你成功了吗？

去b站把cookie放到BBDown.data里面，或者直接用之前的版本，点上面那个链接应该可以直接下载，不行的话就点网盘这个吧链接: https://pan.baidu.com/s/15VVcQtuaP4f1GhYID0cGiA?pwd=peyj 提取码: peyj 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by xxgddd** [comment]
感谢感谢，我已经搞好了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月07日 22:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [nilaoda/BBDown] 最新测试构建版本登录时依然提示“Arg_KeyNotFound” (Issue #851) |

https://github.com/jyeric/BBDown/actions/runs/7883215503/artifacts/1240726625 先去actions下载一个老版本的BBDown.exe，然后正常登录，得到cookie，把文件放到和ffmpeg和最新的BBdown一起，然后就可以去下载了

***@***.***

你好我也是不太会这个，请问你成功了吗？

去b站把cookie放到BBDown.data里面，或者直接用之前的版本，点上面那个链接应该可以直接下载，不行的话就点网盘这个吧链接: https://pan.baidu.com/s/15VVcQtuaP4f1GhYID0cGiA?pwd=peyj 提取码: peyj 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by Weydon-Ding** [comment]
本来想调试一下，但是在vs2022下调试没问题

**Comment by CeresY** [comment]
> Chrome在b站抓到的cookie拷到BBDown.data文件里，目前似乎可行

感谢感谢，可以登录了

**Comment by 113737038537** [comment]
> > > > https://github.com/jyeric/BBDown/actions/runs/7883215503/artifacts/1240726625 先去actions下载一个老版本的BBDown.exe，然后正常登录，得到cookie，把文件放到和ffmpeg和最新的BBdown一起，然后就可以去下载了
> > > 
> > > 
> > > 想请问一下哪个老版的BBDown可以得到cookie，这个教程方便分析吗，我邮箱[843826630@qq.com](mailto:843826630@qq.com)
> > 
> > 
> > 你好我也是不太会这个，请问你成功了吗？
> 
> 去b站把cookie放到BBDown.data里面，或者直接用之前的版本，点上面那个链接应该可以直接下载，不行的话就点网盘这个吧链接: https://pan.baidu.com/s/15VVcQtuaP4f1GhYID0cGiA?pwd=peyj 提取码: peyj 复制这段内容后打开百度网盘手机App，操作更方便哦

感谢，可以正常用

**Comment by fare1well** [comment]
> > > > > https://github.com/jyeric/BBDown/actions/runs/7883215503/artifacts/1240726625 先去actions下载一个老版本的BBDown.exe，然后正常登录，得到cookie，把文件放到和ffmpeg和最新的BBdown一起，然后就可以去下载了
> > > > 
> > > > 
> > > > 想请问一下哪个老版的BBDown可以得到cookie，这个教程方便分析吗，我邮箱[843826630@qq.com](mailto:843826630@qq.com)
> > > 
> > > 
> > > 你好我也是不太会这个，请问你成功了吗？
> > 
> > 
> > 去b站把cookie放到BBDown.data里面，或者直接用之前的版本，点上面那个链接应该可以直接下载，不行的话就点网盘这个吧链接: https://pan.baidu.com/s/15VVcQtuaP4f1GhYID0cGiA?pwd=peyj 提取码: peyj 复制这段内容后打开百度网盘手机App，操作更方便哦
> 
> 感谢，可以正常用

功德无量！回退版本后即可正常使用 (づ￣3￣)づ╭❤～
