### ISSUE TITLE
没有找到符合要求的音频流

### ISSUE THREAD

**Issue by MC-dusk** [nilaoda/BBDown#855]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Actions 
https://github.com/nilaoda/BBDown/actions/runs/6851227729 
对应https://github.com/nilaoda/BBDown/commit/1196918e709f883eabfe3122ccad824b8f551381 

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win11

#### 3. 你使用的完整命令是什么？
```
BBDown https://www.bilibili.com/video/BV14a4y1E7oM -p 1
```
注意这个视频没有音频

#### 4. 遇到了什么问题？
红色提示：没有找到符合要求的音频流，然后就退出，没有下载视频。
按理说没有音频直接下载视频流再封装就好了，以前（指目前最新的稳定版1.6.1）也是这样的没有问题。
（那为什么不用1.6.1呢？因为会有其他问题比如Arg_KeyNotFound）

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
--

**Comment by kemi-20** [comment]
用--video-only不就可以了

**Comment by Aqua256** [comment]
按照这工具的角度想因为有  `--video-only`，`--audio-only`和默认同时下载视频音频流合并的功能，默认参数就不应该擅作主张，在没视频或者没音频流的时候还继续下载
