### ISSUE TITLE
[Feature Request] 设置禁用 bilivideo.cn 域

### ISSUE THREAD

**Issue by RtYkk** [nilaoda/BBDown#86]
个人有点小强迫症，讨厌这种 mcdn，所以在 clash 里面是直接把这个域名 REJECT 的，在网页端看视频没有问题，因为网页端会自动重试，就能给我分发一个正常的 CDN。然后 BBDown 就不行，直接会出现 #9 的问题。刚刚跑了遍`--debug`才发现。
我这要求略有点奇葩+鸡肋，如果您认为不会做就直接 close 掉吧。感谢！

**Comment by nilaoda** [comment]
已经强制替换pcdn
