### ISSUE TITLE
为什么下载电影资源只能下载6分钟 我已经登陆了

### ISSUE THREAD

**Issue by dyzczy** [nilaoda/BBDown#864]
为什么下载电影资源只能下载6分钟 我已经登陆了

**Comment by XingZhe-Li** [comment]
the same , 解析只有AVC 480p

**Comment by XingZhe-Li** [comment]
手动从网页端抓Cookie下来又能下了，或许对你能有帮助，自带的扫码登录还是不能用

**Comment by Aqua256** [comment]
最好带上问题template吧，软件版本可能不是最新的，建议自己build个最新版。

**Comment by specked2527** [comment]
> 为什么下载电影资源只能下载6分钟 我已经登陆了

截图日志都没有你说个？你电影有会员？

**Comment by Aqua256** [comment]
#861
