### ISSUE TITLE
请问如何加载cookie？

### ISSUE THREAD

**Issue by StrollStars** [nilaoda/BBDown#866]
程序给出了参数`-c, --cookie <cookie>`
请问<cookie>，可以是文件吗，还是只能字符串？
应该用怎么样的格式？

**Comment by Aqua256** [comment]
跟字符串就行了 用双引号围住就行 可以是文件。

**Comment by StrollStars** [comment]
@Aqua256 感谢指教，字符串用双引号导入成功了，但是文件导入失败。

**Comment by Aqua256** [comment]
写配置文件里，不是cookie单独放txt

**Comment by StrollStars** [comment]
@Aqua256 确实可以，感谢再次指教。
