### ISSUE TITLE
B站最近上新的一些视频似乎下载不了了呢

### ISSUE THREAD

**Issue by qinkaii-126** [nilaoda/BBDown#870]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Release v1.6.1

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
BBDown https://www.bilibili.com/video/BV17j421o7XE/
```
#### 4. 遇到了什么问题？
下载进行到【获取视频信息...】时，出现【Arg_KeyNotFound】错误，下载过程终止

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by TKOT** [comment]
同样是这个问题

**Comment by Chengxcy** [comment]
同样这个问题，不能下载了，出现【Arg_KeyNotFound】错误

**Comment by Aqua256** [comment]
#865 我认为我已经在这个issue里说了解决方法

**Comment by Chengxcy** [comment]
> #865 我认为我已经在这个issue里说了解决方法

没看到解决方法啊，不是说编译的有问题吗

**Comment by Aqua256** [comment]
并没有说编译的有问题，BlueSkyXN也只是说自己配置有问题，目前的问题是给出的Release版本是有问题的需要自己手动编译master分支。

**Comment by Chengxcy** [comment]
> 并没有说编译的有问题，BlueSkyXN也只是说自己配置有问题，目前的问题是给出的Release版本是有问题的需要自己手动编译master分支。

因为从一开始就不懂构建。看到提供的方法，经过尝试和学习终于正常了，感谢。方法：fork项目后，手动Action，构建成功后下载压缩包，解压缩得到程序。感谢感谢

**Comment by zhdetn** [comment]
> > 并没有说编译的有问题，BlueSkyXN也只是说自己配置有问题，目前的问题是给出的Release版本是有问题的需要自己手动编译master分支。
> 
> 因为从一开始就不懂构建。看到提供的方法，经过尝试和学习终于正常了，感谢。方法：fork项目后，手动Action，构建成功后下载压缩包，解压缩得到程序。感谢感谢

专属视频下载不了，报:76150，稿件消失错误
