### ISSUE TITLE
去水印

### ISSUE THREAD

**Issue by chenmg2020** [nilaoda/BBDown#871]
请问现在是不是下载的视频都不能去水印了？有什么办法去掉水印吗

**Comment by specked2527** [comment]
没有去水印功能

**Comment by specked2527** [comment]
> 请问现在是不是下载的视频都不能去水印了？有什么办法去掉水印吗

https://github.com/nilaoda/BBDown/commit/17e06df484dd0205a11dfa0242e5386ce823f6bf

**Comment by Aqua256** [comment]
只当它是视频下载软件，它只能帮你处理视频的下载归档，具体的视频处理要再找脚本。
