### ISSUE TITLE
服务器可能并不支持多线程下载, 请使用 --multi-thread false 关闭多线程

### ISSUE THREAD

**Issue by iyzyi** [nilaoda/BBDown#874]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
自行fork构建最新actions版本

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win10

#### 3. 你使用的完整命令是什么？
```
BBDown https://www.bilibili.com/video/BVxxxxxxxxxx/
```
#### 4. 遇到了什么问题？
下载进度频繁卡在99%，等待巨久之后报错：服务器可能并不支持多线程下载, 请使用 --multi-thread false 关闭多线程
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/49014178/f66dd185-bc51-46d5-a477-7b1d2c0115f4)

**Comment by specked2527** [comment]
BBDown https://www.bilibili.com/video/BVxxxxxxxxxx/  --multi-thread false

**Comment by iyzyi** [comment]
> BBDown https://www.bilibili.com/video/BVxxxxxxxxxx/ --multi-thread false

谢谢你，不过感觉有用但不优雅o.o。这个是被风控了嘛？

**Comment by specked2527** [comment]
> > BBDown https://www.bilibili.com/video/BVxxxxxxxxxx/ --multi-thread false
> 
> 谢谢你，不过感觉有用但不优雅o.o。这个是被风控了嘛？

你为何不用yt-dlp ，又不是每个链接都要这样，懒的话就默认，把这个写到BBDown.config
```
#本文件是BBDown程序的配置文件
#以#开头的都会被程序忽略
#然后剩余非空白内容程序逐行读取，对于一个选项，其参数应当在下一行出现

#例如下面将设置输出文件名格式 ./创建目录/ 结束
--file-pattern
./<ownerName>/<videoTitle>[<dfn>]

#--debug   

#关闭多线程下载
--multi-thread 
False
```

**Comment by zwj064276714** [comment]
怎么解决啊
