### ISSUE TITLE
如何跳过章节下载

### ISSUE THREAD

**Issue by 96827123** [nilaoda/BBDown#876]
1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
使用Release 1.62

2. 你在什么系统使用本软件？（Win/Linux/Mac）
win10

3. 你使用的完整命令是什么？
bbdown -tv --dfn-priority "1080P 高码率 , 1080P 高帧率" https://www.bilibili.com/bangumi/play/epXXXXXX
4. 遇到了什么问题？
下载遇到自动下载章节，并且混流了章节

5. 运行截图（最好开启--debug；注意自行将Cookie/Token等敏感信息隐藏）
![20240513185522](https://github.com/nilaoda/BBDown/assets/54199210/a548ea1d-513d-4fbf-84cf-c6931f3c10cf)
已经使用 bbdwon -h 查看那条命令可以跳过下载章节了，但是没发现。想知道跳过的命令

**Comment by nilaoda** [comment]
same: #876
