### ISSUE TITLE
1.3.7 下载不了视频了

### ISSUE THREAD

**Issue by github-keep** [nilaoda/BBDown#88]
问题：**无法正常下载视频**
版本：BBDown 1.3.7 

报错：
执行 BBDown BV1hW411F7MK 
The remote server returned an error: (412) Precondition Failed.

错误发生位置：
抓包发现，错误发生在第二步的请求。链接：https://api.bilibili.com/x/web-interface/view?aid=24935845
按下面方法修改 UA 后可以正常使用

临时解决方法：
修改请求头 UA
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
------------------------------------------------------------------------------------------------------------------------------------------
其他问题改进建议：
下载过快时会被限制下载，建议增加错误重试机制。

**Comment by nilaoda** [comment]
下载不了视频是哪一步有问题？

**Comment by github-keep** [comment]
> 下载不了视频是哪一步有问题？

已经更新了问题描述哈，大佬及时修复下呗。

**Comment by 1422384664** [comment]
我下tv版也是报这个错误 ，大佬什么时候修复一下

**Comment by nilaoda** [comment]
请各位遇到问题，翻阅软件中所示网址：
https://github.com/nilaoda/BBDown/discussions

https://github.com/nilaoda/BBDown/discussions/87

**Comment by nilaoda** [comment]
> > 下载不了视频是哪一步有问题？
> 
> 已经更新了问题描述哈，大佬及时修复下呗。

确实可以解决，感谢
