### ISSUE TITLE
有大会员，也扫码登录成功了，但是还显示需要会员才能下载

### ISSUE THREAD

**Issue by ryanzhoumr** [nilaoda/BBDown#881]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
。。。
1.6.2
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。
win10
#### 3. 你使用的完整命令是什么？
```
BBDown.exe BV13C4y1Z7uC  --dfn-priority "720P 高清" -p all
--



#### 4. 遇到了什么问题？
bbdown login 扫码登录成功后，还是显示需要大会员才能下载

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。
![2](https://github.com/nilaoda/BBDown/assets/170097582/da7aae21-392c-4198-85f2-8d57c7786951)
![1](https://github.com/nilaoda/BBDown/assets/170097582/ec31560d-17e2-4bc3-9982-6deb7229f143)

**Comment by eenlhuoc** [comment]
附议，敲碗等修正

**Comment by lczyellow** [comment]
![1716791970545](https://github.com/nilaoda/BBDown/assets/145742296/c5b75752-8c69-4cd8-9a31-2af3625cc25e)
win10下 1.62版本，有大会员也扫码登录成功了

**Comment by lczyellow** [comment]
![1716791970545](https://github.com/nilaoda/BBDown/assets/145742296/44cf18df-aa9c-4d66-8e1a-db6622bc7bc5)
Win10下  1.62版本，大会员扫码登录成功，试了好多剧都是这样

**Comment by guang-yu-zhu** [comment]
同样的问题
