### ISSUE TITLE
下载购买的课程，遇到部分视频只能解析 480p，并且只有五分钟

### ISSUE THREAD

**Issue by Ltjwork** [nilaoda/BBDown#885]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.2 版
#### 4. 遇到了什么问题？
下载购买的课程，会遇到只能解析出 480p，而且只有五分钟视频，但不是所有视频分 p 都这样，不知道是为什么

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by BlueSkyXN** [comment]
没登陆？哪个课程
