### ISSUE TITLE
今天刚发现的一个问题，命令-tv 就会提示解析此分P失败(建议--debug查看详细信息) 、{"code":-400,"message":"请求错误","ttl":1} -web就没有问题，今天之前都是没有问题的

### ISSUE THREAD

**Issue by 7lumen** [nilaoda/BBDown#886]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.2Release 
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win&Linux
#### 3. 你使用的完整命令是什么？
BBDown.exe  "https://www.bilibili.com/video/BV1zn4y1d7A8/?spm_id_from=333.1007.tianma.1-2-2.click"  --dfn-priority "360P 流畅"  -tv  --ffmpeg-path "C:\Users\os\Desktop\BBDown_GUI\ffmpeg.exe"  --work-dir "C:\Users\os\Desktop

#### 4. 遇到了什么问题？
提示：解析此分P失败(建议--debug查看详细信息) 、{"code":-400,"message":"请求错误","ttl":1}

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![222](https://github.com/nilaoda/BBDown/assets/164745147/8dd491e7-0789-41f0-98f9-fa2768e1c6bb)

**Comment by celozaga** [comment]
我遇到了同样的问题。

**Comment by ericleeutd** [comment]
俺也一样

**Comment by abandonstudy** [comment]
加一，补充一下，就算加上--debug,也是只有这一行{"code":-400,"message":"请求错误","ttl":1}，任何视频tv接口都无法下载

**Comment by adangran** [comment]
俺也一样

**Comment by uNICO-rn** [comment]
俺也一样

**Comment by YYRPSQ** [comment]
俺也一样。有没有解决办法呀

**Comment by UnderCooled** [comment]
下载这个Fork的版本就行了：https://github.com/Jared-02/BBDown/releases

**Comment by 7lumen** [comment]
其实目前虽然 -tv 报错， 但是只要更改为 -web 就没有任何问题了

**Comment by HuXuanPast** [comment]
> 下载这个Fork的版本就行了：https://github.com/Jared-02/BBDown/releases

但是你这个版本没办法下TV版的60帧率啊

**Comment by UnderCooled** [comment]
> > 下载这个Fork的版本就行了：[Jared-02/BBDown/releases](https://github.com/Jared-02/BBDown/releases)
> 
> 但是你这个版本没办法下TV版的60帧率啊

去这个分支提个issue试试？

**Comment by pandady** [comment]
同样问题

**Comment by 9694368924** [comment]
同样的问题

**Comment by puteulanus** [comment]
同遇到，加上 --debug 之后能看到是这个请求失败了

[2024-06-06 00:02:22.491] - aid=380945537,cid=492999764,epId=,tvApi=True,IntlApi=False,appApi=False,qn=0
[2024-06-06 00:02:22.491] - bangumi=False,cheese=False
[2024-06-06 00:02:22.491] - 获取网页内容: Url: https://api.snm0516.aisee.tv/x/tv/ugc/playurl?avid=380945537&cid=492999764&fnval=4048&fnver=0&fourk=1&device=android&platform=android&mobi_app=android_tv_yst&npcybs=0&force_host=2&build=102801&otype=json&qn=0, Headers: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64) Gecko/20100101 Firefox/93.585
Accept-Encoding: gzip, deflate
Cookie:
Cache-Control: no-cache
[2024-06-06 00:02:22.652] - Response: {"code":-400,"message":"请求错误","ttl":1}
[2024-06-06 00:02:22.655] - 解析此分P失败(建议--debug查看详细信息)
[2024-06-06 00:02:22.655] - {"code":-400,"message":"请求错误","ttl":1}
[2024-06-06 00:02:22.655] - {"code":-400,"message":"请求错误","ttl":1}
[2024-06-06 00:02:22.655] - 任务完成

<img width="1075" alt="图片" src="https://github.com/nilaoda/BBDown/assets/4849177/29428c73-edb5-4d6f-a08c-b7a765bf948f">

**Comment by qingfeng6868** [comment]
用了fork版本又不能下最高画质，求解

**Comment by pandady** [comment]
看样子是不搞了

**Comment by XUANHLGG** [comment]
> 用了fork版本又不能下最高画质，求解

先用正式版本手机扫码登录Web，然后将 BBDown.data 复制到Fork版本软件目录，再解析即可

**Comment by XUANHLGG** [comment]
> 先用正式版本手机扫码登录Web，然后将 BBDown.data 复制到Fork版本软件目录，再解析即可

先用正式版本手机扫码登录Web，然后将 BBDown.data 复制到Fork版本软件目录，再解析即可

**Comment by XUANHLGG** [comment]
> > 下载这个Fork的版本就行了：https://github.com/Jared-02/BBDown/releases
> 
> 但是你这个版本没办法下TV版的60帧率啊

先用正式版本手机扫码登录Web，然后将 BBDown.data 复制到Fork版本软件目录，再解析即可

**Comment by pandady** [comment]
> > > 下载这个Fork的版本就行了：https://github.com/Jared-02/BBDown/releases
> > 
> > 
> > 但是你这个版本没办法下TV版的60帧率啊
> 
> 先用正式版本手机扫码登录Web，然后将 BBDown.data 复制到Fork版本软件目录，再解析即可

有用了几天 又不行了。。。 老样子 还是爆这个错

**Comment by XUANHLGG** [comment]
> > > > 下载这个Fork的版本就行了：https://github.com/Jared-02/BBDown/releases
> > > 
> > > 
> > > 但是你这个版本没办法下TV版的60帧率啊
> > 
> > 
> > 先用正式版本手机扫码登录Web，然后将 BBDown.data 复制到Fork版本软件目录，再解析即可
> 
> 有用了几天 又不行了。。。 老样子 还是爆这个错

确实又不行了

**Comment by Developer78-sgyuijhgygwtdwgyhutre45r5t** [comment]
我可以郑重地证明，带着最坚定不移的信念，那个主要版本以及其他尊敬用户提出的分支变体，现在都陷入了破损的状态。可以想象，不，应该说是非常可能，造成这一令人遗憾情况的罪魁祸首正是这些程序所严重依赖的应用程序编程接口（API）。

**Comment by YYRPSQ** [comment]
那现在要咋办呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nilaoda/BBDown"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月23日(星期天) 上午10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nilaoda/BBDown] 今天刚发现的一个问题，命令-tv 就会提示解析此分P失败(建议--debug查看详细信息) 、{"code":-400,"message":"请求错误","ttl":1} -web就没有问题，今天之前都是没有问题的 (Issue #886)





 
我可以郑重地证明，带着最坚定不移的信念，那个主要版本以及其他尊敬用户提出的分支变体，现在都陷入了破损的状态。可以想象，不，应该说是非常可能，造成这一令人遗憾情况的罪魁祸首正是这些程序所严重依赖的应用程序编程接口（API）。

**Comment by Zhaokugua** [comment]
接口又坏掉啦，fork的版本也不能用了qwq

**Comment by spongebai** [comment]
又挂啦，救救tv接口

**Comment by YYRPSQ** [comment]
请问有解决方法了吗

**Comment by hanc44** [comment]
同样问题。。。

**Comment by secret-zou** [comment]
同样问题，请尽快解决

**Comment by chenkongming** [comment]
同样问题，希望尽快解决

**Comment by Linux2010** [comment]
@nilaoda  这个问题我看被老大关闭了， 是解决了吗？ 能升级个tag么？

**Comment by puteulanus** [comment]
> @nilaoda 这个问题我看被老大关闭了， 是解决了吗？ 能升级个tag么？

自动构建版 https://github.com/nilaoda/BBDown/actions 的 Mac x64 binary 实测 -tv 选项已经正常工作了

以及 Mac 上使用 brew 安装的 mp4box（gpac）时 --debug 参数会使 mp4box 报错：
```
[2024-07-29 16:48:17.011] - 开始合并音视频...
[2024-07-29 16:48:17.012] - mp4box命令:  -verbose  -inter 500 -noprog  -add "446150236/446150236.P1.1203931368.mp4#trackID=1:name="  -add "446150236/446150236.P1.1203931368.m4a:lang=und"  -itags tool=:cover="446150236/446150236.jpg":title="一片栏杆引发的物理危机":comment="技术支持：海拉鲁火鸡工程院
部分参考：
栏杆科技原理解析BV1Cm4y1j791
飞天栏杆操控方法以及极简喷气式飞机BV1CN411m7Zo
原来我对火箭的力量一无所知BV1Gh4y1M77U":artist="lolo今天玩什么" -new -- "一片栏杆引发的物理危机.mp4"
[2024-07-29 16:48:17.066] - Option -verbose unknown, please check usage.
[2024-07-29 16:48:17.066] - Possible options are:
--mvex
[2024-07-29 16:48:17.067] -
[2024-07-29 16:48:17.068] - 合并失败
[2024-07-29 16:48:17.068] - 任务完成
```
mp4box 已尝试升到 homebrew 最新 2.2.1_1 -> 2.4.0，情况依旧，从 help 看应该改成 -v ？

```
 $ mp4box -h
MP4Box [option] input [option]


General Options:

-h (string):                   print help
	* general: general options help
	* hint: hinting options help
	* dash: DASH segmenter help
	* split: split options help
	* import: import options help
	* encode: scene description encoding options help
	* meta: meta (HEIF, MPEG-21) handling options help
	* extract: extraction options help
	* dump: dump options help
	* swf: Flash (SWF) options help
	* crypt: ISMA E&A options help
	* format: supported formats help
	* live: BIFS streamer help
	* core: libgpac core options
	* all: print all the above help screens
	* opts: print all options
	* tags: print supported iTunes tags
	* cicp: print various CICP code points
	* VAL: search for option named VAL (without - or --) in MP4Box, libgpac core and all filters

-hx (string):                  look for given string in name and descriptions of all MP4Box and filters options
-nodes:                        list supported MPEG4 nodes
-nodex:                        list supported MPEG4 nodes and print nodes
-node (string):                get given MPEG4 node syntax and QP infolist
-xnodes:                       list supported X3D nodes
-xnodex:                       list supported X3D nodes and print nodes
-xnode (string):               get given X3D node syntax
-snodes:                       list supported SVG nodes
-languages:                    list supported ISO 639 languages
-boxes:                        list all supported ISOBMF boxes and their syntax
-stats,-fstat:                 print filter session statistics (import/export/encrypt/decrypt/dashing)
-graph,-fgraph:                print filter session graph (import/export/encrypt/decrypt/dashing)
-v:                            verbose mode
-version:                      get build version
-- INPUT:                      escape option if INPUT starts with - character

Return codes are 0 for no error, 1 for error
```

**Comment by nilaoda** [comment]
@puteulanus 这个问题可以新开一个issue用于跟踪
