### ISSUE TITLE
Parameter `--file-pattern` not working

### ISSUE THREAD

**Issue by bropines** [nilaoda/BBDown#894]
#### 1. What version of BBDown are you using? (specify Release / Actions / DotnetTool)
Version 1.6.2

#### 2. What operating system are you using this software on? (Win/Linux/Mac)
Windows

#### 3. What is the complete command you are using?
```
BBDown.exe --skip-cover -tv --debug --show-all ep817481 --file-pattern "Test_<pageNumber>"
```
#### 4. What issue are you encountering?
The parameter `-f` `--file-pattern` is not working.

#### 5. Screenshot of the execution 
![image](https://github.com/nilaoda/BBDown/assets/57861007/2177c4d8-34d3-4536-af61-e9610097129e)

#### 6. Log
[oleg.log](https://github.com/user-attachments/files/15793506/oleg.log)

**Comment by asasas234** [comment]
我也是，请问有人知道怎么解决吗？

**Comment by nilaoda** [comment]
`--multi-file-pattern` for multiple Page
