### ISSUE TITLE
只能下到6分钟试看 登录有效 账号为大会员 电影为会员专属

### ISSUE THREAD

**Issue by bigsk05** [nilaoda/BBDown#897]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.2

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows
#### 3. 你使用的完整命令是什么？
```
bbdown -ia https://www.bilibili.com/bangumi/play/ep741421
```
#### 4. 遇到了什么问题？
登录有效 账号为大会员 电影为会员专属的情况下 下载《深海》只有开头6分钟 4K和杜比视界都一样 只能下到6分钟试看

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/61304326/afdc627f-c2e3-4325-846f-eb0e67854303)

**Comment by Happy-clo** [comment]
本人问题同上

**Comment by xztxy** [comment]
一样的问题。只能等大佬修复了

**Comment by asmoker** [comment]
参见：https://github.com/nilaoda/BBDown/issues/899#issuecomment-2216887273
