### ISSUE TITLE
1.3.7版3月中旬开始无法下载tv端无水印

### ISSUE THREAD

**Issue by liuqiqi79** [nilaoda/BBDown#90]
3月初使用过1.3.7下载tv端无水，中旬开始使用-tv或-intl就不能再下载了：
“D:\DIRECTX\BBDown>bbdown -tv https://www.bilibili.com/video/BV1Mf4y1t7L8
BBDown version 1.3.7, Bilibili Downloader.
欢迎到讨论区交流：
https://github.com/nilaoda/BBDown/discussions

[2021-03-21 14:53:44.756] - 获取aid...
[2021-03-21 14:53:44.929] - 获取aid结束: 289633808
[2021-03-21 14:53:44.931] - 获取视频信息...
The remote server returned an error: (412) Precondition Failed.”

不走tv端可正常下载有水印的高码视频
“D:\DIRECTX\BBDown>bbdown https://www.bilibili.com/video/BV1Mf4y1t7L8
BBDown version 1.3.7, Bilibili Downloader.
欢迎到讨论区交流：
https://github.com/nilaoda/BBDown/discussions

[2021-03-21 14:54:28.812] - 加载本地cookie...
[2021-03-21 14:54:28.815] - 获取aid...
[2021-03-21 14:54:29.025] - 获取aid结束: 289633808
[2021-03-21 14:54:29.026] - 获取视频信息...
[2021-03-21 14:54:29.212] - 视频标题: ##############
[2021-03-21 14:54:29.213] - 发布时间: 2021/3/17 19:33:24
[2021-03-21 14:54:29.214] - P1: [311582992] [#########] [12m50s]
[2021-03-21 14:54:29.215] - 共计 1 个分P, 已选择：ALL
[2021-03-21 14:54:29.215] - 开始解析P1...
[2021-03-21 14:54:29.217] - 下载封面...
[2021-03-21 14:54:30.153] - 共计10条视频流.
                            0. [1080P 高码率] [1920x1080] [AVC] [16000/656] [1838 kbps] [~172.76 MB]
                            1. [1080P 高码率] [1920x1080] [HEVC] [16000/656] [1105 kbps] [~103.86 MB]
                            2. [1080P 高清] [1920x1080] [AVC] [16000/656] [841 kbps] [~79.05 MB]
                            3. [1080P 高清] [1920x1080] [HEVC] [16000/656] [558 kbps] [~52.45 MB]
                            4. [720P 高清] [1280x720] [AVC] [16000/656] [561 kbps] [~52.73 MB]
                            5. [720P 高清] [1280x720] [HEVC] [16000/656] [382 kbps] [~35.91 MB]
                            6. [480P 清晰] [852x480] [AVC] [16000/656] [253 kbps] [~23.78 MB]
                            7. [480P 清晰] [852x480] [HEVC] [16000/656] [230 kbps] [~21.62 MB]
                            8. [360P 流畅] [640x360] [HEVC] [16000/656] [157 kbps] [~14.76 MB]
                            9. [360P 流畅] [640x360] [AVC] [16000/656] [156 kbps] [~14.66 MB]
[2021-03-21 14:54:30.183] - 共计3条音频流.
                            0. [M4A] [128 kbps] [~12.03 MB]
                            1. [M4A] [128 kbps] [~12.03 MB]
                            2. [M4A] [67 kbps] [~6.30 MB]
[2021-03-21 14:54:30.190] - 已选择的流:
                            [视频] [1080P 高码率] [1920x1080] [AVC] [16000/656] [1838 kbps] [~172.76 MB]
                            [音频] [M4A] [128 kbps] [~12.03 MB]
[2021-03-21 14:54:30.193] - 开始下载P1视频...
                            [###-------------------------------------]   9% /”

退回使用1.2.4版本可使用-tv，但只能下载普通1080P版无水印，tv端不显示高码。
大佬能否修复1.3.7版的tv无水通道？

**Comment by nilaoda** [comment]
https://github.com/nilaoda/BBDown/discussions/87

**Comment by liuqiqi79** [comment]
> #87

试了几种写法都不行：[https://www.hualigs.cn/image/6057044eb1143.jpg](url)

**Comment by liuqiqi79** [comment]
> #87

试了几种写法都不行：[https://www.hualigs.cn/image/6057044eb1143.jpg](url)

bbdown -tv finger=28****** _uuid=*******; SESSDATA=4***********; bili_jct=************ https://www.bilibili.com/video/BV1Mf4y1t7L8 也是（此时不应有 Ym）kk。）

**Comment by nilaoda** [comment]
bbdown -tv -c "写cookie" "url"

注意引号

**Comment by liuqiqi79** [comment]
> bbdown -tv -c "写cookie" "url"
> 
> 注意引号

感谢指正。
手动加cookie可以用1.3.7加载tv但依然只能下普通1080P无水，1080P+无水下不了。使用的是大会员的cookie。

**Comment by nilaoda** [comment]
> > bbdown -tv -c "写cookie" "url"
> > 注意引号
> 
> 感谢指正。
> 手动加cookie可以用1.3.7加载tv但依然只能下普通1080P无水，1080P+无水下不了。使用的是大会员的cookie。

你需要使用TV会员。在软件使用logintv登录
