### ISSUE TITLE
tv解析接口失效

### ISSUE THREAD

**Issue by x7jumlIIaIC74HmZ** [nilaoda/BBDown#901]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Merge pull request #890 from nilaoda/fix/cookie_issue #198 使用的这个最新actions版本

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Linux

#### 3. 你使用的完整命令是什么？

bbdown -tv BV1s94y1h7pf  --debug

#### 4. 遇到了什么问题？
tv解析接口失效 解析了所有视频 都是说要购买观看完整视频 

不加 -tv 参数一切功能正常 就能下载视频

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![屏幕截图 2024-06-30 22-51-13](https://github.com/nilaoda/BBDown/assets/173223215/82bd7d43-bd48-4613-baee-5b10567b473f)

**Comment by zcoya** [comment]
一样。。。

**Comment by B1ueH0r1z0n** [comment]
一样！！！

**Comment by JamesWangWuXing** [comment]
一样!!!

**Comment by RCcccj** [comment]
bbdown <bv> --debug

**Comment by RCcccj** [comment]
> bbdown bv --debug

这样的格式看看

**Comment by secret-zou** [comment]
请尽快解决！

**Comment by x7jumlIIaIC74HmZ** [comment]
感谢好心人提供了新的tv解析接口,目前等待主分支合并,要是等不及的,可以先自己修改编译

**Comment by secret-zou** [comment]
> 感谢好心人提供了新的tv解析接口,目前等待主分支合并,要是等不及的,可以先自己修改编译

请问如何修改编译，可以提供详细教程吗

**Comment by nilaoda** [comment]
Merged
