### ISSUE TITLE
怎样取消自动跳过AI字幕

### ISSUE THREAD

**Issue by HongTang-Icode** [nilaoda/BBDown#903]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win

#### 3. 你使用的完整命令是什么？
```
.\BBDown.exe https://www.bilibili.com/video/BV1Jq421c75P/?spm_id_from=333.788.recommend_more_video.4 --sub-only --no-skip-ai
```
#### 4. 遇到了什么问题？
从所有（大概）说明文件中没发现能怎样取消自动跳过AI字幕

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/nilaoda/BBDown/assets/132168928/67fd00e3-6593-4a85-b943-8d9426012756)

**Comment by xiaojiaqi** [comment]
--skip-ai=false  加入这个参数

BBDown.exe https://www.bilibili.com/video/BV1Jq421c75P/?spm_id_from=333.788.recommend_more_video.4 --sub-only --skip-ai=false

**Comment by HongTang-Icode** [comment]
> --skip-ai=false 加入这个参数
> 
> BBDown.exe https://www.bilibili.com/video/BV1Jq421c75P/?spm_id_from=333.788.recommend_more_video.4 --sub-only --skip-ai=false

谢谢
