### ISSUE TITLE
无法解析Bilibili国际

### ISSUE THREAD

**Issue by BotCrab** [nilaoda/BBDown#904]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Release 1.6.2

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Windows11 23H2

#### 3. 你使用的完整命令是什么？
BBDown.exe ep12786680 -intl -p LAST --skip-subtitle --skip-cover --debug -c *****

#### 4. 遇到了什么问题？
无法解析Bilibili国际

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![QQ20240711-123915](https://github.com/nilaoda/BBDown/assets/32790448/01826574-00e0-4e7e-93aa-31a112c41bc8)

**Comment by ChrisShen-github** [comment]
同解析不了，希望作者有空能来更新一下
