### ISSUE TITLE
不知道这样的主机。 (www.bilibili.com:443)

### ISSUE THREAD

**Issue by yqygh** [nilaoda/BBDown#916]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.2

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win

#### 3. 你使用的完整命令是什么？
# 设置txt文件路径
$filePath = "D:\bilibili_download\listA6101A7500.txt"

# 读取文件内容到一个数组
$links = Get-Content -Path $filePath

# 设置下载路径
$downloadPath = "E:\A6101A7500"

# 遍历每个链接并调用BBDown下载视频
foreach ($link in $links) {
    # 调用BBDown程序下载视频并指定下载路径
    BBDown $link --work-dir "$downloadPath"
    
    # 如果需要，可以添加一些延迟
    # Start-Sleep -Seconds 1
}

#### 4. 遇到了什么问题？
不知道这样的主机。 (www.bilibili.com:443)
请尝试升级到最新版本后重试!

之前运行正常，今天突然这样了

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![previewImage](https://github.com/user-attachments/assets/9a283706-ba91-4511-aa27-dcf205de5aca)

**Comment by BlueSkyXN** [comment]
自己参数调用错误怪软件上，6
请用bvid，不容易出错

**Comment by yqygh** [comment]
> 自己参数调用错误怪软件上，6 请用bvid，不容易出错

重试了下单条视频的bvid，也不行呢，原本的脚本一直在用，没出错来着，不知道为啥今天就不行了，以及原本的脚本里遍历的list里头就是一串bvid，不知道今天为啥会这样T T删除了重新下载exe也不行T T
![1723042838372](https://github.com/user-attachments/assets/4be314b0-847e-4085-90d2-5e91558d5914)

**Comment by nilaoda** [comment]
你是不是开了代理
