### ISSUE TITLE
不支持画质”智能修复“

### ISSUE THREAD

**Issue by srsng** [nilaoda/BBDown#924]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
DotnetTool
dotnet tool install --global BBDown
BBDown version 1.6.3
1.6.3+45622f79cd766e0fc6f5cbd49fcf4960340f35c3

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
BBDown <url>

#### 4. 遇到了什么问题？
现有软件不能获取”智能修复“画质的视频流

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/user-attachments/assets/7057bc4e-a190-40fe-b306-e8964e4ac6ba)

**Comment by srsng** [comment]
如果智能修复是本地处理的，那么这个issue可以直接关了。

顺带一提，与此issue无关：
直接携带`--version`不能获取版本号
```
>>> BBDown --version
Required argument missing for command: 'BBDown'.
请使用 BBDown --help 查看帮助
```
```
>>> BBDown.exe --version --help
BBDown version 1.6.3, Bilibili Downloader.
遇到问题请首先到以下地址查阅有无相关信息：
https://github.com/nilaoda/BBDown/issues

1.6.3+45622f79cd766e0fc6f5cbd49fcf4960340f35c3
```

**Comment by UnforgetMemory** [comment]
`quality`: 64
`tag`: 智能修复
