### ISSUE TITLE
版本1.6.3  视频水印无法去掉

### ISSUE THREAD

**Issue by jiangcheng66** [nilaoda/BBDown#936]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
版本1.6.3

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
win10

#### 3. 你使用的完整命令是什么？
```
bbdown -tv BV11XHoeJEP8
```
#### 4. 遇到了什么问题？
1）无论是否登录，都无法去除水印 （请修复）
2）不登录的情况下：可下载高清1080p 30fps，但使用-tv 参数后只能下载720p 。（请修复）
3）加-tv 参数显示：
        0. [1080P 高清] [AVC] [2727 kbps] [~186.87 MB]
        1. [1080P 高清] [HEVC] [1562 kbps] [~107.11 MB]
      不加-tv参数显示：
       0. [1080P 高清] [1920x1080] [AVC] [30.000] [2727 kbps] [~191.74 MB]
       1. [1080P 高清] [1920x1080] [HEVC] [30.000] [1562 kbps] [~109.83 MB]
      两者显示不一致，数据大小也不一样，计算方法有问题？？？
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
debug运行一切正常，根据上述版本和BV号自己去试一下就知道了。*** 最重要的水印去不掉。***

**Comment by BlueSkyXN** [comment]
又不是啥都能去
tv本身限制就很多
