### ISSUE TITLE
win版本最新的release闪退。

### ISSUE THREAD

**Issue by LessIsMoreInSZ** [nilaoda/BBDown#937]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
。。。

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
。。。

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
xxx

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by BlueSkyXN** [comment]
不会提问就不要提问了

**Comment by LessIsMoreInSZ** [comment]
这玩意你让我怎么写？告诉操作系统，难不成我抓个dump给你？

**Comment by nilaoda** [comment]
命令行工具，请在cmd中执行
