### ISSUE TITLE
希望bbdown在下载时把当前下载的视频url打印在屏幕上，理由如下

### ISSUE THREAD

**Issue by gansui** [nilaoda/BBDown#939]
当需要下载多个视频时，我常用的方法是把这些视频url存入一个文件，比如url.log，然后执行
xargs -a url.log -I FF BBDown FF | tee output.log
这样下载时完成后查看output.log看看是否有下载失败，比如看是否有Resource temporarily unavailable，但是这时候只知道有文件下载失败了，但是却不知道具体哪个url下载失败了，入下面的引用的失败的output.log，完全不知道哪个url下载失败了：
-------------------------------------------------------
389 [2024-09-28 00:05:12.030] - 加载配置文件: /usr/bin/BBDown.config
 390 [2024-09-28 00:05:12.034] - 检测账号登录...                                                                           
 391 [2024-09-28 00:05:17.557] - 获取aid...
 392 Resource temporarily unavailable (www.bilibili.com:443)
 393 请尝试升级到最新版本后重试!
 394 BBDown version 1.6.3, Bilibili Downloader.^M
 395 遇到问题请首先到以下地址查阅有无相关信息：^M
 396 https://github.com/nilaoda/BBDown/issues^M
--------------------------------------------------------------------

**Comment by BlueSkyXN** [comment]
这不是你应该写python解决的吗

**Comment by BlueSkyXN** [comment]
参考
https://github.com/BlueSkyXN/Bili-to-Youtube/blob/main/bup-scan-xlsx-bbdown-v2.py
https://github.com/BlueSkyXN/Bili-to-Youtube/blob/main/check-bilidown-xlsx.py

**Comment by gansui** [comment]
可是这在程序里就是几行代码的事，就是把这个视频的ID值，例如BV1aE4m1R7vV，输出到屏幕上而已，再写一个python程序麻烦不说，还涉及到和BBDown版本匹配的问题。

谢谢你给的链接，不过和我的用法不一致

**Comment by nilaoda** [comment]
done
