### ISSUE TITLE
使用--show-all时错误下载了视频

### ISSUE THREAD

**Issue by abandonstudy** [nilaoda/BBDown#946]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.3

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win 10

#### 3. 你使用的完整命令是什么？
bbdown --show-all https://space.bilibili.com/3493265644980448/channel/collectiondetail?sid=2689294

#### 4. 遇到了什么问题？
使用--show-all时下载了视频
按照文档所说使用  --show-all应该展示所有分P标题

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）

**Comment by imgradeone** [comment]
`--show-all` 指的是在程序输出分 P 列表时，将所有分 P 的信息都显示出来（默认情况下，过多分 P 会被折叠，仅显示前几个分 P 和最后一 P）

对于你需要的需求，建议使用 `-info` 或 `--only-show-info`，该参数不会下载视频，仅作解析。

**Comment by abandonstudy** [comment]
感谢解惑

> `--show-all` 指的是在程序输出分 P 列表时，将所有分 P 的信息都显示出来（默认情况下，过多分 P 会被折叠，仅显示前几个分 P 和最后一 P）
> 
> 对于你需要的需求，建议使用 `-info` 或 `--only-show-info`，该参数不会下载视频，仅作解析。
