### ISSUE TITLE
音视频合并失败，"Unrecognized option "-verbose", check usage "gpac -h"

### ISSUE THREAD

**Issue by NAGenius** [nilaoda/BBDown#955]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
DotnetTool
#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win
#### 3. 你使用的完整命令是什么？
```
BBDown https://www.bilibili.com/bangumi/play/ss33378?from_spmid=666.4.mylist.0
```
#### 4. 遇到了什么问题？
![QQ20241119-023942](https://github.com/user-attachments/assets/03896c91-c5c3-43ea-9558-7c4ed1b30937)
#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![QQ20241119-023942](https://github.com/user-attachments/assets/03896c91-c5c3-43ea-9558-7c4ed1b30937)
#### 6. BBDown.config 如下：
```
# 开启弹幕下载功能
--download-danmaku

# 使用MP4Box混流
--use-mp4box

# 交互式选择清晰度
# --interactive

# 开启调试
--debug

# 视频标题为输出文件名
--file-pattern
<videoTitle>[<dfn>]

# mp4box的路径
--mp4box-path
D:\GPAC\gpac.exe

# ffmpeg的路径
--ffmpeg-path
D:\ffmpeg\bin\ffmpeg.exe

# 程序的工作目录
--work-dir
F:/videos

# 画质优先级
--dfn-priority
8K, 4k, HDR, 杜比视界, 1080P, 720p
```
#### 7. ffmpeg、mp4box 的 version 如下：
```
mp4box -version
MP4Box - GPAC version 2.4-rev0-g5d70253a-master
(c) 2000-2024 Telecom Paris distributed under LGPL v2.1+ - https://gpac.io
ffmpeg -version
ffmpeg version 2024-11-18-git-970d57988d-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
```

**Comment by nilaoda** [comment]
已知问题：#914 

暂时使用ffmpeg，等待后续解决
