### ISSUE TITLE
求助一下国际区怎么下载动漫之类的视频

### ISSUE THREAD

**Issue by DMYJS** [nilaoda/BBDown#959]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
Release

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
Win

#### 3. 你使用的完整命令是什么？
```
BBDown ...
```
#### 4. 遇到了什么问题？
怎么样的命令搭配呢？
比如下载这个：https://www.bilibili.tv/en/play/2117403

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
。。。

**Comment by DMYJS** [comment]
用APP拿到的是accesstoken，怎么调用这个进行下载，多谢。

**Comment by nilaoda** [comment]
参考这里的命令 https://github.com/nilaoda/BBDown/pull/963

**Comment by DMYJS** [comment]
> 参考这里的命令 #963

好的，感谢。话说在QQ上私信你了，没有回复啊
