### ISSUE TITLE
请教一下  bbdwon是如何获取到个人空间所有av号的  

### ISSUE THREAD

**Issue by yibingchaoyue** [nilaoda/BBDown#965]
我想了解一下代码   然后gpt写一个直接获取个人空间的bv号的py
每次都是av号得转一次bv号 然后才获取得到bv号

**Comment by nilaoda** [comment]
https://github.com/nilaoda/BBDown/blob/master/BBDown.Core/Fetcher/SpaceVideoFetcher.cs
