### ISSUE TITLE
下载的视频带垃圾广告字幕, 不知道为什么

### ISSUE THREAD

**Issue by baicaiit** [nilaoda/BBDown#966]
#### 1. 你使用的BBDown版本是什么？（指明 Release / Actions / DotnetTool）
1.6.3

#### 2. 你在什么系统使用本软件？（Win/Linux/Mac）
mac

#### 3. 你使用的完整命令是什么？
```
BBDown https://www.bilibili.com/video/BV1BW42197nX?p=4
```
#### 4. 遇到了什么问题？
下载的视频, 有垃圾广告字幕

#### 5. 运行截图（最好开启`--debug`；注意自行将Cookie/Token等敏感信息隐藏）
![image](https://github.com/user-attachments/assets/e599069a-08d0-498e-a4d3-6e37abc605d4)

**Comment by BlueSkyXN** [comment]
又在胡扯了，这不是API风控吗，拒绝返回视频源

**Comment by imgradeone** [comment]
#948

**Comment by nilaoda** [comment]
related: #948
