### ISSUE TITLE
win10上添加环境变量成功，能调用BBdown，可是找不到下载位置

### ISSUE THREAD

**Issue by lyjhyjyes** [nilaoda/BBDown#97]
您好，cmd显示下载成功，但找不到保存目录。我没有设置保存目录。
BBdown login找不到图片所在。
工具很详细，挺不错

**Comment by nilaoda** [comment]
cmd前面应该会打印目录

![image](https://user-images.githubusercontent.com/20772925/114831240-bc853580-9dff-11eb-8d84-89968042e38a.png)

**Comment by lyjhyjyes** [comment]
> cmd前面应该会打印目录
> 
> ![image](https://user-images.githubusercontent.com/20772925/114831240-bc853580-9dff-11eb-8d84-89968042e38a.png)

对的，找到位置。可是，命令说明没有指定保存位置的代码，请问如何指定下载目录

**Comment by github-keep** [comment]
cd到其他目录下载，貌似文件就保存在其他目录

**Comment by nilaoda** [comment]
> cd到其他目录下载，貌似文件就保存在其他目录

对的
